### ISSUE TITLE
Not a script issue, but the download/install has been failing the last week

### ISSUE THREAD

**Issue by L0rdLogan** [LSPosed/MagiskOnWSALocal#100]
![image](https://user-images.githubusercontent.com/5092548/189491568-bc6a2550-85ab-400c-b9d8-81cd1a3b75af.png)

**Comment by Howard20181** [comment]
Network problem, check network connection or set proxy.

**Comment by tignear** [comment]
Upgrading the OpenSSL version may fix it.

**Comment by L0rdLogan** [comment]
Thank you Tig, I’ll try that

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
