### ISSUE TITLE
WSA settings doesn't get installed

### ISSUE THREAD

**Issue by intari** [LSPosed/MagiskOnWSALocal#101]
Magisk and Google Play icons are added to start menu and started by installer but WSA Settings is not.
manually starting WsaSettings.exe from output folder shows errors about missing libs (MSCVCP140_APP.dll, VCRUNTIME140_APP.dll,VCRUNTIME140_1_APP.dll).

Windows 11 21H2 build 22000.918

**Comment by Howard20181** [comment]
To access the Windows Subsystem for Android Settings app, go to: Start > All Apps > Windows Subsystem for Android™️ Settings.
