### ISSUE TITLE
stuck here for over 30 mins

### ISSUE THREAD

**Issue by ifelixculpa** [LSPosed/MagiskOnWSALocal#104]
have tried 3 4 times but still same result

![image](https://user-images.githubusercontent.com/13099434/189761900-1e6cead5-a9af-41a2-a573-4e2c78f2fa05.png)

**Comment by Howard20181** [comment]
Check your Internet connection or setup a proxy.

**Comment by ifelixculpa** [comment]
> Check your Internet connection or setup a proxy.

with poxy it works but then it ends up like this

![image](https://user-images.githubusercontent.com/13099434/189825783-4e95c079-3f0c-459a-9492-32e16352bd87.png)

**Comment by Howard20181** [comment]
Try again, next time you only need to download OpenGApps.

**Comment by ifelixculpa** [comment]
> Try again, next time you only need to download OpenGApps.

![image](https://user-images.githubusercontent.com/13099434/189836279-015a5e5f-4f73-4a4d-9d8c-7fef5127b40c.png)


gapps is creating issue

**Comment by ifelixculpa** [comment]
if i select not to choose gapps everything works
