### ISSUE TITLE
download error for mindthegapps

### ISSUE THREAD

**Issue by briantho** [LSPosed/MagiskOnWSALocal#109]
just did a fresh install of ubuntu, cloned the repo, ran run.sh and got this.
any ideas why the download failed? i just tried copying the url and was able to download it fine on firefox. 

09/13 18:25:51 [ERROR] CUID#11 - Download aborted. URI=https://downloads.sourceforge.net/project/wsa-mtg/x86_64/20220910/MindTheGapps-12.1.0-x86_64-20220910_001624.zip
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://downloads.sourceforge.net/project/wsa-mtg/x86_64/20220910/MindTheGapps-12.1.0-x86_64-20220910_001624.zip
  -> [SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure:  `not signed by known authorities or invalid' `expired'

**Comment by Howard20181** [comment]
Upgrade ca-certificares

**Comment by briantho** [comment]
ok, got it working. I didn't realize there were a ton of packages that were not up to date. after "upgrading" everything, running run.sh worked fine
