### ISSUE TITLE
下载WSA时出错

### ISSUE THREAD

**Issue by abbaccadd0** [LSPosed/MagiskOnWSALocal#11]
选择完选项之后提示
ARCH=x64
RELEASE_TYPE=insider fast
MAGISK_VER=canary
GAPPS_VARIANT=pico
REMOVE_AMAZON=keep
ROOT_SOL=magisk

Download WSA
Traceback (most recent call last):
  File "/home/abbaccadd0/MagiskOnWSALocal/scripts/downloadWSA.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
An error occurs, exit

可以排除是网络问题……能连上google，请问这个是什么原因🤔

**Comment by alex-sandro92** [comment]
you have to install "requests" module:

`python -m pip install requests`

**Comment by Howard20181** [comment]
`sudo apt install python3-pip`
`python3 -m pip install requests`
