### ISSUE TITLE
No WSA settings icon?

### ISSUE THREAD

**Issue by ShadowOfGannicus** [LSPosed/MagiskOnWSALocal#112]
Installation via this script went smooth, everything works, except I don't know how to open WSA settings, it's not in the start menu. 
I didn't have WSA installed before.
Trying to execute "WsaSettings.exe" from WSA folder turns these errors
![image](https://user-images.githubusercontent.com/67431721/190347351-92ddd0c7-dac9-41ba-9cb4-8e082a4ad250.png)
![image](https://user-images.githubusercontent.com/67431721/190347430-779a3800-d600-4ce7-8b5b-42bbc4202fe4.png)
![image](https://user-images.githubusercontent.com/67431721/190347476-24284dbd-a1af-4f42-98e6-6291b331ad99.png)

Windows 11 Beta (22622.598)
How to proceed to access WSA settings?

**Comment by Howard20181** [comment]
It looks like it was unsuccessfully installed, take a screenshot of the installation script running results and upload it.
You shouldn't run WsaSettings.exe directly from the directory, this will definitely not work.

**Comment by ShadowOfGannicus** [comment]
Results of installation script
![image](https://user-images.githubusercontent.com/67431721/190385983-c30f0a8d-c65e-4904-aab3-41d504fd7019.png)

**Comment by Howard20181** [comment]
So you are able to open the Android app but can't access the settings?

**Comment by ShadowOfGannicus** [comment]
I can open Google Play Store and Magisk. I can login fine and download apps from google store, which then also get added to my Start, so I can open them. No Android or WSA Settings entry though.

**Comment by Howard20181** [comment]
No Android built-in settings are normal
But no WSA settings do not know why, only feedback to Microsoft

**Comment by ShadowOfGannicus** [comment]
Mystery solved, the WSA Settings entry not appearing was due to Explorer Patcher.
Thanks and sorry for wasting time, I should definitely confirm in clean environment first.
