### ISSUE TITLE
No output folder

### ISSUE THREAD

**Issue by TheDingOfTheHud** [LSPosed/MagiskOnWSALocal#117]
So, after I let the program download and do its stuff there's no output folder and I get this error

`sudo: unable to execute /tmp/wsa-build-Dgy0zfd0bG_/magisk/magiskpolicy: Permission denied`

**Comment by Howard20181** [comment]
Which system is used?
Please describe the environment.

**Comment by TheDingOfTheHud** [comment]
Well I fixed it, something to do with kali so I just switched to the default Ubuntu
