### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by cyurd** [LSPosed/MagiskOnWSALocal#121]
hi, thanks for scripts.
I have permission issue. su command not work therefore i work with sudo -i and bash commands. I got these errors after tried to many way to fix it 

done
/dev/y1qJWwX5(/.*)?    u:object_r:magisk_file:s0
/data/adb/magisk(/.*)?   u:object_r:magisk_file:s0
sudo: unable to execute /tmp/wsa-build-MlelFQu0aA_/magisk/magiskpolicy: Permission denied

what should I do?
Thanks in advance

**Comment by Howard20181** [comment]
Which system is used?
Please describe the environment.

**Comment by cyurd** [comment]
Ubuntu 22.04.1 LTS on WSL (Win11)

**Comment by Howard20181** [comment]
Is it WSL version 1 or 2?

**Comment by s1204IT** [comment]
@cyurd 
Run the following command in PowerShell or Command Prompt
```
wsl --status
```
And then share their output with us.

**Comment by s1204IT** [comment]
Or, run `wslfetch` in the WSL and tell us the output of "**KERNEL**".

**Comment by ilkerbey-01** [comment]
solved by chmod 777 -R (file location here)

apperantly files had missing permissions
