### ISSUE TITLE
Install script fails unless the xaml and vclib commands are removed and pico apps and beta or stable magisk

### ISSUE THREAD

**Issue by kpcintegrations** [LSPosed/MagiskOnWSALocal#122]
I've been building these in WSL2 ubuntu and I've tried a lot of combinations. It seems to only work with the newest WSA build if using pico gapps and beta or stable magisk. Also if I don't remove the ADD-AppxPackage lines from Install.ps1 Terminal just crashes and nothing happens. All other methods have WSA loading screens that stay for a few minutes and disappear with nothing loaded or installed. Any ideas?

**Comment by ifelixculpa** [comment]
atleast it works for you with gapps , mine never builds gapps and fails always

**Comment by PeterNjeim** [comment]
As for OpenGApps, pico is the only supported variant for version 11.0 (which is what this repo uses). If you want something else, you'll need to build OpenGApps yourself. I did this several months ago when the old repo wasn't banned yet. You can get the pre-builts from here: https://github.com/PeterNjeim/MagiskOnWSA/releases/latest. I offer the Full variant for x86_64 builds.

As for Magisk, any version should work.

As for the Install.ps1 issue, no issue arises on my end.

I personally only use the latest WSA build, as they're actually stable releases and simply misnomers. There should be no reason to go to earlier builds, they're not more stable.

**Comment by ifelixculpa** [comment]
> As for OpenGApps, pico is the only supported variant for version 11.0 (which is what this repo uses). If you want something else, you'll need to build OpenGApps yourself. I did this several months ago when the old repo wasn't banned yet. You can get the pre-builts from here: https://github.com/PeterNjeim/MagiskOnWSA/releases/latest. I offer the Full variant for x86_64 builds.
> 
> As for Magisk, any version should work.
> 
> As for the Install.ps1 issue, no issue arises on my end.
> 
> I personally only use the latest WSA build, as they're actually stable releases and simply misnomers. There should be no reason to go to earlier builds, they're not more stable.

i always end up like this no matter I use proxy or what

https://github.com/LSPosed/MagiskOnWSALocal/issues/104#issuecomment-1244955369

**Comment by PeterNjeim** [comment]
> i always end up like this no matter I use proxy or what
> 
> [#104 (comment)](https://github.com/LSPosed/MagiskOnWSALocal/issues/104#issuecomment-1244955369)

Looks like an issue with MindTheGapps, try using OpenGApps instead

**Comment by PeterNjeim** [comment]
> i always end up like this no matter I use proxy or what
> 
> [#104 (comment)](https://github.com/LSPosed/MagiskOnWSALocal/issues/104#issuecomment-1244955369)

Not sure to be honest. Regardless, I made my fork a long time ago specifically because I disagreed with MagiskOnWSA's philosophy of making people build it themselves. It was slow, redundant, and abusive to GitHub. Now they make people build it themselves locally, again, redundant and slow. I recommend just using the builds I offer, or if the build you want isn't available, to fork my repo and build the specific variant you want.

**Comment by ifelixculpa** [comment]
> > i always end up like this no matter I use proxy or what
> > [#104 (comment)](https://github.com/LSPosed/MagiskOnWSALocal/issues/104#issuecomment-1244955369)
> 
> Not sure to be honest. Regardless, I made my fork a long time ago specifically because I disagreed with MagiskOnWSA's philosophy of making people build it themselves. It was slow, redundant, and abusive to GitHub. Now they make people build it themselves locally, again, redundant and slow. I recommend just using the builds I offer, or if the build you want isn't available, to fork my repo and build the specific variant you want.

have forked let me test it out , what if in future I want build specific what steps would I need

**Comment by PeterNjeim** [comment]
> have forked let me test it out , what if in future I want build specific what steps would I need

You shouldn't fork it unless you want to build something that isn't available. Just give a star instead :). If you want to build something specific, go to the `Actions` tab, then the `Build MagiskOnWSA` workflow, then click `Run workflow`, then choose the options you want

**Comment by ifelixculpa** [comment]
> > have forked let me test it out , what if in future I want build specific what steps would I need
> 
> You shouldn't fork it unless you want to build something that isn't available. Just give a star instead :). If you want to build something specific, go to the `Actions` tab, then the `Build MagiskOnWSA` workflow, then click `Run workflow`, then choose the options you want

simply superb man, ur a savior.... will test it right away

**Comment by ifelixculpa** [comment]
> > have forked let me test it out , what if in future I want build specific what steps would I need
> 
> You shouldn't fork it unless you want to build something that isn't available. Just give a star instead :). If you want to build something specific, go to the `Actions` tab, then the `Build MagiskOnWSA` workflow, then click `Run workflow`, then choose the options you want

Sorry for late response bro , was wsiting for 22H2 release for fresh install and magisk on local dint worked as usual and your worked flawlessly ... thanks again bro

**Comment by PeterNjeim** [comment]
@s1204IT I've noticed you reacted with a "confused" emoji to my earlier message. Instead of doing that (since it's unhelpful), please tell me what you need more information about, I'd be happy to share

**Comment by Howard20181** [comment]
>  If I don't remove the ADD-AppxPackage lines from Install.ps1 Terminal just crashes and nothing happens. 



What is your system version?
Windows 11 22H1 or 22H2?

**Comment by PeterNjeim** [comment]
I've tested on both versions and both work fine, so I doubt that information is relevant to the issue. He might've used some "debloater" software that broke parts of Windows. That's my best guess. Also he hasn't participated in the discussion at all, so I'm going to @ him and hope he responds. @kpcintegrations

**Comment by kpcintegrations** [comment]
I've been trying to get this to work both with a release from your repo and WSAGAppsScript and doing it manually. Either way it fails to launch both Magisk and Google Play upon install. Also I was hoping to edit some apps in the system_ext.img file to remove restrictions, and I don't quite know how to edit the workflows or source to make those changes. I've been installing your release build and then attempting to edit system_ext.img and reload WSA, but that doesn't work either. Is there some trick to this to get it to accept custom apks and such?

**Comment by kpcintegrations** [comment]
> > If I don't remove the ADD-AppxPackage lines from Install.ps1 Terminal just crashes and nothing happens.
> 
> What is your system version? Windows 11 22H1 or 22H2?

I'm on the newest Windows 11 Insider Dev Channel Build.

**Comment by PeterNjeim** [comment]
@kpcintegrations 

I'm not sure what you mean by "custom APK". I'm almost certain you know how to sideload apps via ADB, so it seems like you're trying to modify system APK's? In which case I have no experience with that.

Just for clarity, if you install one of my releases, and don't modify anything system-wise, does WSA launch at all? Like try opening the "Files" app, it's the first option in the Windows Subsystem for Android settings (find it in the start menu). Or is it just Magisk and the Google Play store failing to launch.

Also, before you report anything to me, please go to the README page in my repository and follow the "Uninstallation" instructions exactly. Maybe your WSA is in a "glitched" state like a few others were, and following every step of the uninstallation has fixed it for those people. Please note that this will remove every spec of data related to WSA, so make a backup (backup instructions are in my README as well) if you desire.

Also, please tell us your Windows build number, by typing `winver` in the start menu.

**Comment by kpcintegrations** [comment]
> @kpcintegrations
> 
> I'm not sure what you mean by "custom APK". I'm almost certain you know how to sideload apps via ADB, so it seems like you're trying to modify system APK's? In which case I have no experience with that.
> 
> Just for clarity, if you install one of my releases, and don't modify anything system-wise, does WSA launch at all? Like try opening the "Files" app, it's the first option in the Windows Subsystem for Android settings (find it in the start menu). Or is it just Magisk and the Google Play store failing to launch.
> 
> Also, before you report anything to me, please go to the README page in my repository and follow the "Uninstallation" instructions exactly. Maybe your WSA is in a "glitched" state like a few others were, and following every step of the uninstallation has fixed it for those people. Please note that this will remove every spec of data related to WSA, so make a backup (backup instructions are in my README as well) if you desire.
> 
> Also, please tell us your Windows build number, by typing `winver` in the start menu.

Yes by custom apk, I mean one that's been pulled from the img files, decompiled, edited, recompiled, and then replaced in the same img file and location it came from.

If I go the run.sh method, only pico opengapps and editing the install.ps1 file to remove the xaml and vclibs install Add-AppxPackage commands lets the script run in powershell via windows terminal. Otherwise it crashes because apps are open that are using the resources and for some reason -ForceCloseApps parameter doesn't work on my build, just crashes terminal. If I do all of that it will run, but any other combination did not work. And it seems spotty. I've uninstalled and installed a billion times now and only sometimes does magisk and play store actually load. Half the time it will install hang on the two loading WSACLients and then crash and no apps will open until a uninstall reinstall.

On Win 11 25206.1000 by the way.

**Comment by PeterNjeim** [comment]
Just to be clear, when you say "uninstall", you mean the lengthy instructions in my README? Or just clicking the "uninstall" button for WSA.

You can edit system files similarly to how a Magisk module does, look at how this guy did it: (first step is to place the files in your desired Android /system location in the git repository itself (https://github.com/a0533057932/MagiskOnWSA/commit/c2d90822475129082f5d92d7ca8cebf414838857), second step is to edit the build.sh to modify the files to have the correct attributes (https://github.com/a0533057932/MagiskOnWSA/commit/a981c3987b59b0985d04ac4bc4c82d89db785d20)).

The LSPosed repository requires pico opengapps since they still rely on the old 11.0 builds of opengapps. I personally offer Full opengapps in my repository. If you want a different version of opengapps, you'd have to build it yourself using the pull request for Android 12.1/12L (which is what I did).

The xaml and vclibs issue is still a mystery to me, can only assume it's due to the dev channel build.

**Comment by kpcintegrations** [comment]
> Just to be clear, when you say "uninstall", you mean the lengthy instructions in my README? Or just clicking the "uninstall" button for WSA.
> 
> You can edit system files similarly to how a Magisk module does, look at how this guy did it: (first step is to place the files in your desired Android /system location in the git repository itself ([a0533057932/MagiskOnWSA@c2d9082](https://github.com/a0533057932/MagiskOnWSA/commit/c2d90822475129082f5d92d7ca8cebf414838857)), second step is to edit the build.sh to modify the files to have the correct attributes ([a0533057932/MagiskOnWSA@a981c39](https://github.com/a0533057932/MagiskOnWSA/commit/a981c3987b59b0985d04ac4bc4c82d89db785d20))).
> 
> The LSPosed repository requires pico opengapps since they still rely on the old 11.0 builds of opengapps. I personally offer Full opengapps in my repository. If you want a different version of opengapps, you'd have to build it yourself using the pull request for Android 12.1/12L (which is what I did).
> 
> The xaml and vclibs issue is still a mystery to me, can only assume it's due to the dev channel build.
> 
> _Edit: I updated my repository to include the latest changes from this repository (which includes the fix for this issue). Maybe you can test out my new builds and see if they work without modifying the Install.ps1 file_

Yes, lengthy version of uninstalling. And I will try it out. 

Also if I want to replace an apk that's already in the system.img file is that the same process? Would I put it in the repository with the same path it has when mounted? I.E. system_ext/priv-app/apkName.apk or can it be anywhere as long as I reference it in the build script?

**Comment by PeterNjeim** [comment]
I'd assume it has to be in the specific location in the git repository. So just make a new folder called "system_ext" in the same level as the "system" folder in the hierarchy.

**Comment by Howard20181** [comment]
Since it's off topic, lock the thread and you can use the [Discussions](https://github.com/LSPosed/MagiskOnWSALocal/discussions)  to continue the discussion
