### ISSUE TITLE
Play Store Connection

### ISSUE THREAD

**Issue by christianfarmerf** [LSPosed/MagiskOnWSALocal#124]
The Play Store never connects to the internet, claiming it timed out. I can confirm an internet connection is present.

**Comment by gabrielkyle** [comment]
I was having this issue, now the issue is that it doesn't even load past "Checking Info" when clicking "Sign in"

**Comment by Danfun64** [comment]
I don't know if this is the same issue you are having, but I keep having moments where the play store doesn't show the front page and sometimes when I click around I end up seeing this arrow in a loop.

![image](https://user-images.githubusercontent.com/4473635/191396884-df8d26bb-c3ab-4171-afb1-a42424bde13e.png)

**Comment by Howard20181** [comment]
Setup a proxy
