### ISSUE TITLE
error bash ./scripts/run.sh

### ISSUE THREAD

**Issue by callng** [LSPosed/MagiskOnWSALocal#13]
Dependencies
Hit:1 https://mirrors.ustc.edu.cn/ubuntu bionic InRelease
Hit:2 https://mirrors.ustc.edu.cn/ubuntu bionic-updates InRelease
Hit:3 https://mirrors.ustc.edu.cn/ubuntu bionic-backports InRelease
Hit:4 https://mirrors.ustc.edu.cn/ubuntu bionic-security InRelease
Hit:5 https://mirrors.ustc.edu.cn/ubuntu bionic-proposed InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
6 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package wine is a virtual package provided by:
  wine-stable 3.0-1ubuntu1
  wine-development 3.6-1
You should explicitly select one to install.

E: Package 'wine' has no installation candidate
Requirement already satisfied: requests in /usr/lib/python3/dist-packages
./scripts/run.sh: line 65: winetricks: command not found
An error occurs, exit
Cleanup Work Directory

**Comment by alex-sandro92** [comment]
Install wine manually. 
For stable release run:
`sudo apt install wine-stable`
For dev release run:
`sudo apt install wine-development`
Then run the script again.
