### ISSUE TITLE
I can't run it.

### ISSUE THREAD

**Issue by Sunrongguo2008** [LSPosed/MagiskOnWSALocal#133]
![Screenshot_20220923_223411](https://user-images.githubusercontent.com/91547012/191985463-c20e222c-48b1-40a2-9d20-fb0d36278b99.jpg)

What should I do?

**Comment by Howard20181** [comment]
Lack of information.
What is your distribution?

**Comment by Sunrongguo2008** [comment]
![Screenshot_20220923_223823](https://user-images.githubusercontent.com/91547012/191986676-3cb36bc5-d7e6-492d-ba5d-a78a13d079ad.jpg)
![Screenshot_20220923_223411](https://user-images.githubusercontent.com/91547012/191986689-140cf565-a4c8-4393-ba94-427c720769d8.jpg)
Ubuntu 18.04.6 LTS

**Comment by Howard20181** [comment]
如果可以请更新系统，python版本过低而且wine工作不正常
