### ISSUE TITLE
[Feature Request] 跳过手动配置

### ISSUE THREAD

**Issue by Doddddd** [LSPosed/MagiskOnWSALocal#137]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

否

### Describe the solution you'd like/描述你想要的解决方案

保留上一次构建的配置
./run sh
使用上一次的配置？(y/n)

**Comment by Howard20181** [comment]
你看一下run.sh在构建开始会打印出来构建参数，把命令行参数记一下用build.sh直接构建就好
比如 `./build.sh --arch x64 --release-type WIF --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk`

**Comment by Doddddd** [comment]
> 你看一下run.sh在构建开始会打印出来构建参数，把命令行参数记一下用build.sh直接构建就好 比如 `./build.sh --arch x64 --release-type WIF --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk` `./build.sh --release-type WIF`

谢谢
