### ISSUE TITLE
[Bug] Stuck on Magisk Integration.

### ISSUE THREAD

**Issue by lalishansh** [LSPosed/MagiskOnWSALocal#150]
### Steps to reproduce/复现步骤

1. Platform specs. WSL2-Ubuntu 22.04.1 LTS, AMD Ryzen-5800H, 16Gigs RAM
2. Options: x64,  Remove AmazonApp else default

### Expected behaviour/预期行为

Should complete the zip and exit

### Actual behaviour/实际行为

Stuck Indefinitly

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

c770a2ba7decbb64086be1c586a7f3c63fb89751

### Linux distribution info/Linux 发行版信息

NAME="WSL2-Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"

### Windows version/Windows 版本

10.0.22000.829

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type RP --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk --compress
INFO: Architecture: x64
INFO: Release Type: RP
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Release Preview

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>
<summary>
Output
</summary>
COMMAND_LINE=--arch x64 --release-type RP --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk --compress
INFO: Architecture: x64
INFO: Release Type: RP
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Release Preview
Generate Download Links
Generating WSA download link: arch=x64 release_type=Release Preview
download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/<blah-blah-blah-&-blah-blah-blah> to /home/tred/WSA-build-latest/download/xaml-x64.appx
download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/<blah-blah-blah-&-blah-blah-blah> to /home/tred/WSA-build-latest/download/wsa-x64-RP.zip
Generating Magisk download link: release type=stable
download link: https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@25.2/app-release.apk
Generating MindTheGapps download link: arch=x64 variant=pico
download link: https://downloads.sourceforge.net/project/wsa-mtg/x86_64/20220910/MindTheGapps-12.1.0-x86_64-20220910_001624.zip
Download Artifacts

09/27 03:58:15 [NOTICE] Downloading 5 item(s)

09/27 03:58:16 [NOTICE] GID#<token> - Download has already completed: /home/tred/WSA-build-latest/download/xaml-x64.appx

09/27 03:58:16 [NOTICE] Download complete: /home/tred/WSA-build-latest/download/xaml-x64.appx

09/27 03:58:16 [NOTICE] GID#<token> - Download has already completed: /home/tred/WSA-build-latest/download/magisk-stable.zip

09/27 03:58:16 [NOTICE] Download complete: /home/tred/WSA-build-latest/download/magisk-stable.zip

09/27 03:58:16 [NOTICE] CUID#9 - Redirecting to https://download.microsoft.com/download/4/7/c/<blah-blah-blah-blah>appx/Microsoft.VCLibs.x64.14.00.Desktop.appx
[DL:4.8MiB][#xxxxxx 2.2MiB/1.3GiB(0%)][#xxxxx 0B/0B][#xxxxxx 0B/0B]
09/27 03:58:16 [NOTICE] GID# - Download has already completed: /home/tred/WSA-build-latest/download/vclibs-x64.appx

09/27 03:58:16 [NOTICE] Download complete: /home/tred/WSA-build-latest/download/vclibs-x64.appx

09/27 03:58:17 [NOTICE] CUID#11 - Redirecting to https://yer.dl.sourceforge.net/project/wsa-mtg/x86_64/20220910/MindTheGapps-12.1.0-x86_64-20220910_001624.zip
[DL:27MiB][#deb060 47MiB/1.3GiB(3%)][#6b3c9e 0B/0B]
09/27 03:58:18 [NOTICE] GID#<token> - Download has already completed: /home/tred/WSA-build-latest/download/MindTheGapps-x64.zip

09/27 03:58:18 [NOTICE] Download complete: /home/tred/WSA-build-latest/download/MindTheGapps-x64.zip
[#deb060 1.3GiB/1.3GiB(99%) CN:2 DL:23MiB]
09/27 03:59:12 [NOTICE] Download complete: /home/tred/WSA-build-latest/download/wsa-x64-RP.zip

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
6cab0c|OK  |       0B/s|/home/tred/WSA-build-latest/download/xaml-x64.appx
8d26ce|OK  |       0B/s|/home/tred/WSA-build-latest/download/magisk-stable.zip
86f547|OK  |       0B/s|/home/tred/WSA-build-latest/download/vclibs-x64.appx
6b3c9e|OK  |       0B/s|/home/tred/WSA-build-latest/download/MindTheGapps-x64.zip
deb060|OK  |    24MiB/s|/home/tred/WSA-build-latest/download/wsa-x64-RP.zip

Status Legend:
(OK):download completed.
Extract WSA
unzipping to /tmp/wsa-build-6taIZIjZfe_/wsa
unzipping from /tmp/wsa-build-6taIZIjZfe_/wsa/WsaPackage_2208.40000.4.0_x64_Release-Nightly.msix
Extract done

Extract Magisk
done

Extract MindTheGapps
Archive:  ../download/MindTheGapps-x64.zip
signed by SignApk
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/app/GoogleCalendarSyncAdapter/GoogleCalendarSyncAdapter.apk
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/app/PrebuiltExchange3Google/PrebuiltExchange3Google.apk
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/etc/default-permissions/default-permissions-google.xml
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/etc/default-permissions/default-permissions-mtg.xml
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/etc/permissions/com.google.android.dialer.support.xml
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/etc/permissions/privapp-permissions-google-product.xml
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/etc/security/fsverity/gms_fsverity_cert.der
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/etc/sysconfig/d2d_cable_migration_feature.xml
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/etc/sysconfig/google-hiddenapi-package-allowlist.xml
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/etc/sysconfig/google.xml
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/etc/sysconfig/google_build.xml
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/framework/com.google.android.dialer.support.jar
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/lib/libjni_latinimegoogle.so
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/lib64/libjni_latinimegoogle.so
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/overlay/GmsOverlay.apk
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/overlay/GmsSettingsProviderOverlay.apk
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/priv-app/AndroidAutoStub/AndroidAutoStub.apk
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/priv-app/GmsCore/GmsCore.apk
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/priv-app/GooglePartnerSetup/GooglePartnerSetup.apk
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/priv-app/GoogleRestore/GoogleRestore.apk
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/priv-app/Phonesky/Phonesky.apk
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/product/priv-app/Velvet/Velvet.apk
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/system_ext/etc/permissions/privapp-permissions-google-system-ext.xml
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/system_ext/priv-app/GoogleFeedback/GoogleFeedback.apk
  inflating: /tmp/wsa-build-6taIZIjZfe_/gapps/system/system_ext/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk
Extract done

Expand images
system_ext: 83/96 files (1.2% non-contiguous), 33805/33907 blocks
resize2fs 1.46.5 (30-Dec-2021)
Resizing the filesystem on /tmp/wsa-build-6taIZIjZfe_/wsa/x64/system_ext.img to 40690 (4k) blocks.
The filesystem on /tmp/wsa-build-6taIZIjZfe_/wsa/x64/system_ext.img is now 40690 (4k) blocks long.

product: 153/192 files (0.0% non-contiguous), 80777/81020 blocks
resize2fs 1.46.5 (30-Dec-2021)
Resizing the filesystem on /tmp/wsa-build-6taIZIjZfe_/wsa/x64/product.img to 196272 (4k) blocks.
The filesystem on /tmp/wsa-build-6taIZIjZfe_/wsa/x64/product.img is now 196272 (4k) blocks long.

/: 2679/2688 files (0.4% non-contiguous), 211646/226942 blocks
resize2fs 1.46.5 (30-Dec-2021)
Resizing the filesystem on /tmp/wsa-build-6taIZIjZfe_/wsa/x64/system.img to 237302 (4k) blocks.
The filesystem on /tmp/wsa-build-6taIZIjZfe_/wsa/x64/system.img is now 237302 (4k) blocks long.

vendor: 1311/1344 files (0.6% non-contiguous), 80908/81152 blocks
resize2fs 1.46.5 (30-Dec-2021)
Resizing the filesystem on /tmp/wsa-build-6taIZIjZfe_/wsa/x64/vendor.img to 85444 (4k) blocks.
The filesystem on /tmp/wsa-build-6taIZIjZfe_/wsa/x64/vendor.img is now 85444 (4k) blocks long.

Expand images done

Mount images
done

Remove Amazon Appstore
done

Integrate Magisk
#!/system/bin/sh
mkdir -p /data/adb/magisk
cp /sbin/* /data/adb/magisk/
chmod -R 755 /data/adb/magisk
restorecon -R /data/adb/magisk
for module in $(ls /data/adb/modules); do
    if ! [ -f "/data/adb/modules/$module/disable" ] && [ -f "/data/adb/modules/$module/sepolicy.rule" ]; then
        /sbin/magiskpolicy --live --apply "/data/adb/modules/$module/sepolicy.rule"
    fi
done
</details>

**Comment by lalishansh** [comment]
![image](https://user-images.githubusercontent.com/61790879/192395099-229f0e5d-c1d7-4fa1-86c8-30c85b849aa7.png)
is this problematic

**Comment by Howard20181** [comment]
Try again, maybe wine got stuck when "Merge Language Resources"

**Comment by lalishansh** [comment]
Tried a few times (one time even left it for an hour)

**Comment by lalishansh** [comment]
How can I use the github-workflow(sure I'll follow the rules) for the same

**Comment by Howard20181** [comment]
> How can I use the github-workflow(sure I'll follow the rules) for the same

Pre-build version https://github.com/PeterNjeim/MagiskOnWSA

**Comment by PeterNjeim** [comment]
Please note that the link above is now to a banned repository, contacting GitHub to see what the problem is
