### ISSUE TITLE
[Bug] Some files can't download during the build process

### ISSUE THREAD

**Issue by kinver** [LSPosed/MagiskOnWSALocal#156]
### Steps to reproduce/复现步骤

1. 运行run.sh并在选择构建版本后部分文件无法下载成功，这些文件是：wsa-x64-retail.zip，download/xaml-x64.appx，magisk-stable.zip
2. 重复clone和运行run.sh依然出现相同的状况

### Expected behaviour/预期行为

完成上述几项文件的下载

### Actual behaviour/实际行为

下载异常

注：下午我在办公室电脑也是同样的步骤已经构建成功并且安装好了WSA，回到宿舍电脑构建时却出了问题。在办公室时没挂代理，回到宿舍挂了代理。在宿舍不挂代理在获取链接时要很久。

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

ed2529e620c0ccebfa600d046b9e348f96514000

### Linux distribution info/Linux 发行版信息

Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021

### Windows version/Windows 版本

Windows 11 21H2 10.0.22000 暂缺 Build 22000

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --root-sol magisk --compress
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: Root Solution: magisk

### Version requirement/版本要求

- [x] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>
<summary>Details</summary>

下载结果：
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
0c5d6c|ERR |       0B/s|/home/user/MagiskOnWSALocal/download/wsa-x64-retail.zip
7f085b|ERR |       0B/s|/home/user/MagiskOnWSALocal/download/xaml-x64.appx
c58c4d|OK  |   6.6MiB/s|/home/user/MagiskOnWSALocal/download/vclibs-x64.appx
2dc219|OK  |   141KiB/s|/home/user/MagiskOnWSALocal/download/MindTheGapps-x64.zip
f5dd7e|INPR|       0B/s|/home/user/MagiskOnWSALocal/download/magisk-stable.zip

下载magisk时一直提示类似信息：
[#f5dd7e 0B/0B CN:1 DL:0B]
10/01 01:01:19 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

10/01 01:01:19 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

10/01 01:01:19 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

10/01 01:01:20 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

10/01 01:01:20 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

10/01 01:01:20 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk
[#f5dd7e 0B/0B CN:1 DL:0B]
10/01 01:01:20 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

已挂代理：
~/MagiskOnWSALocal$ curl www.google.com
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="TiMtLirNKKbdHjXxE7WyoA">(function(){window.google={kEI:'BSg3Y7zOH-bPkPIP7p-vIA',kEXPI:'0,1302536,56873,6059,206,4804,2316,383,246,5,5367,1123753,1197747,380744,16108,17450,11240,22431,1361,284,12030,2820,14765,4998,13228,3847,10622,22741,2855,2226,1594,1278,2744,147,1103,840,1983,4314,4120,2023,1777,520,14670,3227,2845,7,4773,35,791,28171,1851,15324,432,3,346,1244,1,5445,148,11323,2652,4,1528,2304,7039,20309,1714,5708,7356,16639,1457,15351,1435,5797,2560,4094,4052,3,3541,1,42154,2,14022,2373,342,11401,9865,1758,5679,1021,2380,28742,4568,6255,23419,1254,5835,14968,4332,2204,5280,445,2,2,1,17312,9320,8155,7381,2,3,15964,874,9625,5212,4796,7,1922,9779,7782,11348,12192,4832,5763,5882,4319,1045,6,123,700,4,1,2,2,2,2,1438,6788,5690,1208,15,2306,1606,8745,993,14,82,2852,978,8,1,5,46,84,667,201,1869,122,4814,2619,46,1956,246,488,922,667,197,4,1068,220,235,1351,162,223,115,561,181,2742,190,130,18,3,1,2,1,390,483,378,212,28,796,107,108,1664,199,361,494,370,21,761,1,155,944,946,7,1,417,546,396,2,125,297,464,36,3,6,635,245,561,323,688,1,132,239,226,1290,659,308,258,553,642,471,594,1491,403,104,238,298,338,133,54,208,2,907,329,221,392,763,128,1530,5334892,699,74,17,18,5995815,2803400,3311,141,795,19735,1,1,348,1647,5,3,3,1,1,1,90,20,41,15,2,5,4,2,4,7451778,16496861,4042142,1964,3094,13579,3405,5543,5337,1357290,17173',kBL:'DArb'};google.sn='webhp';google.kHL='en';})();(function(){
var f=this||self;var h,k=[];function l(a){for(var b;a&&(!a.getAttribute||!(b=a.getAttribute("eid")));)a=a.parentNode;return b||h}function m(a){for(var b=null;a&&(!a.getAttribute||!(b=a.getAttribute("leid")));)a=a.parentNode;return b}
function n(a,b,c,d,g){var e="";c||-1!==b.search("&ei=")||(e="&ei="+l(d),-1===b.search("&lei=")&&(d=m(d))&&(e+="&lei="+d));d="";!c&&f._cshid&&-1===b.search("&cshid=")&&"slh"!==a&&(d="&cshid="+f._cshid);c=c||"/"+(g||"gen_204")+"?atyp=i&ct="+a+"&cad="+b+e+"&zx="+Date.now()+d;/^http:/i.test(c)&&"https:"===window.location.protocol&&(google.ml&&google.ml(Error("a"),!1,{src:c,glmm:1}),c="");return c};h=google.kEI;google.getEI=l;google.getLEI=m;google.ml=function(){return null};google.log=function(a,b,c,d,g){if(c=n(a,b,c,d,g)){a=new Image;var e=k.length;k[e]=a;a.onerror=a.onload=a.onabort=function(){delete k[e]};a.src=c}};google.logUrl=n;}).call(this);(function(){
google.y={};google.sy=[];google.x=function(a,b){if(a)var c=a.id;else{do c=Math.random();while(google.y[c])}google.y[c]=[a,b];return!1};google.sx=function(a){google.sy.push(a)};google.lm=[];google.plm=function(a){google.lm.push.apply(google.lm,a)};google.lq=[];google.load=function(a,b,c){google.lq.push([[a],b,c])};google.loadAll=function(a,b){google.lq.push([a,b])};google.bx=!1;google.lx=function(){};}).call(this);google.f={};(function(){
document.documentElement.addEventListener("submit",function(b){var a;if(a=b.target){var c=a.getAttribute("data-submitfalse");a="1"===c||"q"===c&&!a.elements.q.value?!0:!1}else a=!1;a&&(b.preventDefault(),b.stopPropagation())},!0);document.documentElement.addEventListener("click",function(b){var a;a:{for(a=b.target;a&&a!==document.documentElement;a=a.parentElement)if("A"===a.tagName){a="1"===a.getAttribute("data-nohref");break a}a=!1}a&&b.preventDefault()},!0);}).call(this);</script><style>#gbar,#guser{font-size:13px;padding-top:1px !important;}#gbar{height:22px}#guser{padding-bottom:7px !important;text-align:right}.gbh,.gbd{border-top:1px solid #c9d7f1;font-size:1px}.gbh{height:0;position:absolute;top:24px;width:100%}@media all{.gb1{height:22px;margin-right:.5em;vertical-align:top}#gbar{float:left}}a.gb1,a.gb4{text-decoration:underline !important}a.gb1,a.gb4{color:#00c !important}.gbi .gb4{color:#dd8e27 !important}.gbf .gb4{color:#900 !important}
</style><style>body,td,a,p,.h{font-family:arial,sans-serif}body{margin:0;overflow-y:scroll}#gog{padding:3px 8px 0}td{line-height:.8em}.gac_m td{line-height:17px}form{margin-bottom:20px}.h{color:#1558d6}em{font-weight:bold;font-style:normal}.lst{height:25px;width:496px}.gsfi,.lst{font:18px arial,sans-serif}.gsfs{font:17px arial,sans-serif}.ds{display:inline-box;display:inline-block;margin:3px 0 4px;margin-left:4px}input{font-family:inherit}body{background:#fff;color:#000}a{color:#4b11a8;text-decoration:none}a:hover,a:active{text-decoration:underline}.fl a{color:#1558d6}a:visited{color:#4b11a8}.sblc{padding-top:5px}.sblc a{display:block;margin:2px 0;margin-left:13px;font-size:11px}.lsbb{background:#f8f9fa;border:solid 1px;border-color:#dadce0 #70757a #70757a #dadce0;height:30px}.lsbb{display:block}#WqQANb a{display:inline-block;margin:0 12px}.lsb{background:url(/images/nav_logo229.png) 0 -261px repeat-x;border:none;color:#000;cursor:pointer;height:30px;margin:0;outline:0;font:15px arial,sans-serif;vertical-align:top}.lsb:active{background:#dadce0}.lst:focus{outline:none}</style><script nonce="TiMtLirNKKbdHjXxE7WyoA">(function(){window.google.erd={jsr:1,bv:1662,de:true};
var h=this||self;var k,l=null!=(k=h.mei)?k:1,n,p=null!=(n=h.sdo)?n:!0,q=0,r,t=google.erd,v=t.jsr;google.ml=function(a,b,d,m,e){e=void 0===e?2:e;b&&(r=a&&a.message);if(google.dl)return google.dl(a,e,d),null;if(0>v){window.console&&console.error(a,d);if(-2===v)throw a;b=!1}else b=!a||!a.message||"Error loading script"===a.message||q>=l&&!m?!1:!0;if(!b)return null;q++;d=d||{};b=encodeURIComponent;var c="/gen_204?atyp=i&ei="+b(google.kEI);google.kEXPI&&(c+="&jexpid="+b(google.kEXPI));c+="&srcpg="+b(google.sn)+"&jsr="+b(t.jsr)+"&bver="+b(t.bv);var f=a.lineNumber;void 0!==f&&(c+="&line="+f);var g=
a.fileName;g&&(0<g.indexOf("-extension:/")&&(e=3),c+="&script="+b(g),f&&g===window.location.href&&(f=document.documentElement.outerHTML.split("\n")[f],c+="&cad="+b(f?f.substring(0,300):"No script found.")));c+="&jsel="+e;for(var u in d)c+="&",c+=b(u),c+="=",c+=b(d[u]);c=c+"&emsg="+b(a.name+": "+a.message);c=c+"&jsst="+b(a.stack||"N/A");12288<=c.length&&(c=c.substr(0,12288));a=c;m||google.log(0,"",a);return a};window.onerror=function(a,b,d,m,e){r!==a&&(a=e instanceof Error?e:Error(a),void 0===d||"lineNumber"in a||(a.lineNumber=d),void 0===b||"fileName"in a||(a.fileName=b),google.ml(a,!1,void 0,!1,"SyntaxError"===a.name||"SyntaxError"===a.message.substring(0,11)||0<a.message.indexOf("Script error")?2:0));r=null;p&&q>=l&&(window.onerror=null)};})();</script></head><body bgcolor="#fff"><script nonce="TiMtLirNKKbdHjXxE7WyoA">(function(){var src='/images/nav_logo229.png';var iesg=false;document.body.onload = function(){window.n && window.n();if (document.images){new Image().src=src;}
if (!iesg){document.f&&document.f.q.focus();document.gbqf&&document.gbqf.q.focus();}
}
})();</script><div id="mngb"><div id=gbar><nobr><b class=gb1>Search</b> <a class=gb1 href="http://www.google.com/imghp?hl=en&tab=wi">Images</a> <a class=gb1 href="http://maps.google.com/maps?hl=en&tab=wl">Maps</a> <a class=gb1 href="https://play.google.com/?hl=en&tab=w8">Play</a> <a class=gb1 href="https://www.youtube.com/?tab=w1">YouTube</a> <a class=gb1 href="https://news.google.com/?tab=wn">News</a> <a class=gb1 href="https://mail.google.com/mail/?tab=wm">Gmail</a> <a class=gb1 href="https://drive.google.com/?tab=wo">Drive</a> <a class=gb1 style="text-decoration:none" href="https://www.google.com/intl/en/about/products?tab=wh"><u>More</u> &raquo;</a></nobr></div><div id=guser width=100%><nobr><span id=gbn class=gbi></span><span id=gbf class=gbf></span><span id=gbe></span><a href="http://www.google.com/history/optout?hl=en" class=gb4>Web History</a> | <a  href="/preferences?hl=en" class=gb4>Settings</a> | <a target=_top id=gb_70 href="https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=http://www.google.com/&ec=GAZAAQ" class=gb4>Sign in</a></nobr></div><div class=gbh style=left:0></div><div class=gbh style=right:0></div></div><center><br clear="all" id="lgpd"><div id="lga"><img alt="Google" height="92" src="/images/branding/googlelogo/1x/googlelogo_white_background_color_272x92dp.png" style="padding:28px 0 14px" width="272" id="hplogo"><br><br></div><form action="/search" name="f"><table cellpadding="0" cellspacing="0"><tr valign="top"><td width="25%">&nbsp;</td><td align="center" nowrap=""><input name="ie" value="ISO-8859-1" type="hidden"><input value="en" name="hl" type="hidden"><input name="source" type="hidden" value="hp"><input name="biw" type="hidden"><input name="bih" type="hidden"><div class="ds" style="height:32px;margin:4px 0"><input class="lst" style="margin:0;padding:5px 8px 0 6px;vertical-align:top;color:#000" autocomplete="off" value="" title="Google Search" maxlength="2048" name="q" size="57"></div><br style="line-height:0"><span class="ds"><span class="lsbb"><input class="lsb" value="Google Search" name="btnG" type="submit"></span></span><span class="ds"><span class="lsbb"><input class="lsb" id="tsuid_1" value="I'm Feeling Lucky" name="btnI" type="submit"><script nonce="TiMtLirNKKbdHjXxE7WyoA">(function(){var id='tsuid_1';document.getElementById(id).onclick = function(){if (this.form.q.value){this.checked = 1;if (this.form.iflsig)this.form.iflsig.disabled = false;}
else top.location='/doodles/';};})();</script><input value="AJiK0e8AAAAAYzc2FcuqbR5Dki2D5qrW2iK1DN09d7UY" name="iflsig" type="hidden"></span></span></td><td class="fl sblc" align="left" nowrap="" width="25%"><a href="/advanced_search?hl=en&amp;authuser=0">Advanced search</a></td></tr></table><input id="gbv" name="gbv" type="hidden" value="1"><script nonce="TiMtLirNKKbdHjXxE7WyoA">(function(){
var a,b="1";if(document&&document.getElementById)if("undefined"!=typeof XMLHttpRequest)b="2";else if("undefined"!=typeof ActiveXObject){var c,d,e=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];for(c=0;d=e[c++];)try{new ActiveXObject(d),b="2"}catch(h){}}a=b;if("2"==a&&-1==location.search.indexOf("&gbv=2")){var f=google.gbvu,g=document.getElementById("gbv");g&&(g.value=a);f&&window.setTimeout(function(){location.href=f},0)};}).call(this);</script></form><div id="gac_scont"></div><div style="font-size:83%;min-height:3.5em"><br><div id="prm"><style>.szppmdbYutt__middle-slot-promo{font-size:small;margin-bottom:32px}.szppmdbYutt__middle-slot-promo a.ZIeIlb{display:inline-block;text-decoration:none}.szppmdbYutt__middle-slot-promo img{border:none;margin-right:5px;vertical-align:middle}</style><div class="szppmdbYutt__middle-slot-promo" data-ved="0ahUKEwj85Ljzhb36AhXmJ0QIHe7PCwQQnIcBCAQ"><img height="32" src="https://www.google.com/images/hpp/gsa_super_g-64.gif" width="32"><a class="NKcBbd" href="https://www.google.com/url?q=https://searchon.withgoogle.com/%3Futm_source%3Dgoogle-hpp%26utm_medium%3Dembedded_marketing%26utm_campaign%3Dsearchon&amp;source=hpp&amp;id=19031309&amp;ct=3&amp;usg=AOvVaw1GlXzcThlsqsVbk7GQE3m9&amp;sa=X&amp;ved=0ahUKEwj85Ljzhb36AhXmJ0QIHe7PCwQQ8IcBCAU" rel="nofollow">Learn about the latest innovations coming to Google Search</a></div></div></div><span id="footer"><div style="font-size:10pt"><div style="margin:19px auto;text-align:center" id="WqQANb"><a href="/intl/en/ads/">Advertising�Programs</a><a href="/services/">Business Solutions</a><a href="/intl/en/about.html">About Google</a></div></div><p style="font-size:8pt;color:#70757a">&copy; 2022 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p></span></center><script nonce="TiMtLirNKKbdHjXxE7WyoA">(function(){window.google.cdo={height:757,width:1440};(function(){
var a=window.innerWidth,b=window.innerHeight;if(!a||!b){var c=window.document,d="CSS1Compat"==c.compatMode?c.documentElement:c.body;a=d.clientWidth;b=d.clientHeight}a&&b&&(a!=google.cdo.width||b!=google.cdo.height)&&google.log("","","/client_204?&atyp=i&biw="+a+"&bih="+b+"&ei="+google.kEI);}).call(this);})();</script> <script nonce="TiMtLirNKKbdHjXxE7WyoA">(function(){google.xjs={ck:'xjs.hp.CXK6HVSmUM8.L.X.O',cs:'ACT90oGJ3jTEa0u_FRw42i44cHatU_riHQ',excm:[]};})();</script>  <script nonce="TiMtLirNKKbdHjXxE7WyoA">(function(){var u='/xjs/_/js/k\x3dxjs.hp.en_US.mDriYidzYcA.O/am\x3dAACeAAAUAKg/d\x3d1/ed\x3d1/rs\x3dACT90oFg6Dxfvv4eeXaZOCvxjejFmwinQA/m\x3dsb_he,d';
var d=this||self,e=function(a){return a};
var g;var l=function(a,b){this.g=b===h?a:""};l.prototype.toString=function(){return this.g+""};var h={};function n(){var a=u;google.lx=function(){p(a);google.lx=function(){}};google.bx||google.lx()}
function p(a){google.timers&&google.timers.load&&google.tick&&google.tick("load","xjsls");var b=document;var c="SCRIPT";"application/xhtml+xml"===b.contentType&&(c=c.toLowerCase());c=b.createElement(c);if(void 0===g){b=null;var k=d.trustedTypes;if(k&&k.createPolicy){try{b=k.createPolicy("goog#html",{createHTML:e,createScript:e,createScriptURL:e})}catch(q){d.console&&d.console.error(q.message)}g=b}else g=b}a=(b=g)?b.createScriptURL(a):a;a=new l(a,h);c.src=a instanceof l&&a.constructor===l?a.g:"type_error:TrustedResourceUrl";var f,m;(f=(a=null==(m=(f=(c.ownerDocument&&c.ownerDocument.defaultView||window).document).querySelector)?void 0:m.call(f,"script[nonce]"))?a.nonce||a.getAttribute("nonce")||"":"")&&c.setAttribute("nonce",f);document.body.appendChild(c);google.psa=!0};google.xjsu=u;setTimeout(function(){n()},0);})();function _DumpException(e){throw e;}
function _F_installCss(c){}
(function(){google.jl={blt:'none',chnk:0,dw:false,dwu:true,emtn:0,end:0,ine:false,injs:'none',injt:0,injth:0,injv2:false,lls:'default',pdt:0,rep:0,snet:true,strt:0,ubm:false,uwp:true};})();(function(){var pmc='{\x22d\x22:{},\x22sb_he\x22:{\x22agen\x22:true,\x22cgen\x22:true,\x22client\x22:\x22heirloom-hp\x22,\x22dh\x22:true,\x22dhqt\x22:true,\x22ds\x22:\x22\x22,\x22ffql\x22:\x22en\x22,\x22fl\x22:true,\x22host\x22:\x22google.com\x22,\x22isbh\x22:28,\x22jsonp\x22:true,\x22msgs\x22:{\x22cibl\x22:\x22Clear Search\x22,\x22dym\x22:\x22Did you mean:\x22,\x22lcky\x22:\x22I\\u0026#39;m Feeling Lucky\x22,\x22lml\x22:\x22Learn more\x22,\x22oskt\x22:\x22Input tools\x22,\x22psrc\x22:\x22This search was removed from your \\u003Ca href\x3d\\\x22/history\\\x22\\u003EWeb History\\u003C/a\\u003E\x22,\x22psrl\x22:\x22Remove\x22,\x22sbit\x22:\x22Search by image\x22,\x22srch\x22:\x22Google Search\x22},\x22ovr\x22:{},\x22pq\x22:\x22\x22,\x22refpd\x22:true,\x22rfs\x22:[],\x22sbas\x22:\x220 3px 8px 0 rgba(0,0,0,0.2),0 0 0 1px rgba(0,0,0,0.08)\x22,\x22sbpl\x22:16,\x22sbpr\x22:16,\x22scd\x22:10,\x22stok\x22:\x22h0MtYQy1WDP2W4i0px65jT71O1Q\x22,\x22uhde\x22:false}}';google.pmc=JSON.parse(pmc);})();</script>        </body></html>
</details>
[aria2_download.log](https://github.com/LSPosed/MagiskOnWSALocal/files/9686548/aria2_download.log)

**Comment by Howard20181** [comment]
这只能证明你宿舍的网络比办公室的要差，可以检查一下代理规则

**Comment by kinver** [comment]
> 这只能证明你宿舍的网络比办公室的要差，可以检查一下代理规则

感谢解答。好奇怪，按理来说办公室的网络质量也就那样，今天再去办公室那边试试，或者到时我在宿舍用手机热点看看怎样。

**Comment by Howard20181** [comment]
看你的日志是Magisk下载失败，可以重试看看

**Comment by kinver** [comment]
> 看你的日志是Magisk下载失败，可以重试看看

排查了一下找出问题了。在办公室又构建了一次成功了，除了网速慢点没出什么问题。刚回到宿舍又检查了下发现果然是代理问题，在这里报告一下吧也好做个记录。

一开始代理用的是本机网卡的ip，虽然在ubuntu中curl google有返回结果，但是在构建wsa时下载magisk总是连接失败，并且下载ming the gapps和vclibs时网速也很慢。后面代理使用wsl的虚拟网卡的ip后就好了，网速正常。
<img width="558" alt="2022-10-01_182524" src="https://user-images.githubusercontent.com/33085738/193405072-46005fca-c79f-444d-bf6a-ad29769d7261.png">
后面代理使用wsl的虚拟网卡的ip就好了，网速正常。
<img width="491" alt="2022-10-01_182544" src="https://user-images.githubusercontent.com/33085738/193405089-0ec95cdd-0a3f-4ed2-8a5f-f9c89997b176.png">

至于wsa和xaml下载失败估计是因为我用UsbEAm Hosts Editor往host里写了些微软的规则，把host文件删了就好了。

**Comment by Howard20181** [comment]
可以用这个脚本设置代理
https://gist.github.com/Howard20181/31e61599ecb069483448c03649810c75

**Comment by kinver** [comment]
> 可以用这个脚本设置代理 https://gist.github.com/Howard20181/31e61599ecb069483448c03649810c75

感谢，我用的一个类似的脚本

**Comment by kinver** [comment]
> 可以用这个脚本设置代理 https://gist.github.com/Howard20181/31e61599ecb069483448c03649810c75

再报告一个https://github.com/LSPosed/MagiskOnWSALocal/issues/92#issuecomment-1242040448提到的问题，我办公室的电脑也是win11的insider preview，同样和这个作者一样运行run.bat时进度条闪一下就窗口就关闭了，wsa也没有安装成功，手动部署就能成功安装。宿舍的电脑是win 11 专业版 21H2运行run.bat就能安装成功。看来insider preview确实不能通过run.bat和手动运行install.ps1安装。

**Comment by Howard20181** [comment]
10.0.22621.608测试没问题

**Comment by kinver** [comment]
> 10.0.22621.608测试没问题

办公室的版本估计没这么新，等明天我再去看一下

**Comment by kinver** [comment]
> 10.0.22621.608测试没问题

忘记回复了，早上看了下办公室电脑版本是10.0.22623.730。等明天在同事的preview版本的电脑上再试试看能不能安装。

**Comment by Howard20181** [comment]
现在预览版本的Powershell管理员模式是完全使用Windows终端了吗？

**Comment by Howard20181** [comment]
非管理员权限下，Powershell 下运行 `Start-Process -PassThru -Verb RunAs powershell.exe`
弹出来的窗口是什么样式的？
![image](https://user-images.githubusercontent.com/40033067/193450308-846c8bc9-b3ad-434e-909d-bd0ed3bed442.png)
![image](https://user-images.githubusercontent.com/40033067/193450312-b87499df-c6d8-4477-826b-3dc1dac06259.png)

**Comment by kinver** [comment]
> 非管理员权限下，Powershell 下运行 `Start-Process -PassThru -Verb RunAs powershell.exe` 弹出来的窗口是什么样式的？
> 
> 控制台主机 ![image](https://user-images.githubusercontent.com/40033067/193450308-846c8bc9-b3ad-434e-909d-bd0ed3bed442.png)
> 
> Windows终端 ![image](https://user-images.githubusercontent.com/40033067/193450312-b87499df-c6d8-4477-826b-3dc1dac06259.png)
> 
> 如果是Windows终端就会安装失败 因为会被强制退出

不在办公室，我记得运行run.bat时弹出的窗口是控制台主机。

**Comment by kinver** [comment]
> 非管理员权限下，Powershell 下运行 `Start-Process -PassThru -Verb RunAs powershell.exe` 弹出来的窗口是什么样式的？
> 
> 控制台主机 ![image](https://user-images.githubusercontent.com/40033067/193450308-846c8bc9-b3ad-434e-909d-bd0ed3bed442.png)
> 
> Windows终端 ![image](https://user-images.githubusercontent.com/40033067/193450312-b87499df-c6d8-4477-826b-3dc1dac06259.png)
> 
> 如果是Windows终端就会安装失败 因为会被强制退出

不好意思记错了，刚到办公室看了下运行run.bat确实调用的是windows终端。
输入Start-Process -PassThru -Verb RunAs powershell.exe弹出的也是终端，看来确实是终端的问题，感谢解答。

**Comment by Howard20181** [comment]
最新commit已经尝试强制使用控制台主机运行powershell了，可以试试

**Comment by kinver** [comment]
> 最新commit已经尝试强制使用控制台主机运行powershell了，可以试试

抱歉这两天有点忙没去试一试，不过刚刚试了下还是不行，还是一样的窗口闪一下就没了，按照说明的用终端cd到目录运行install也是一样的情况。

用的最新的commit 2f59f6d32714f12e3aeb310b47cf0a85d1156908


![2022-10-05_170551](https://user-images.githubusercontent.com/33085738/194023728-a44267ed-eef3-4814-8598-98d0724e4c13.png)

窗口消失之前的画面，基本上要么没进度条要么进度条跑一下就没了：
![2022-10-05_165348](https://user-images.githubusercontent.com/33085738/194023784-93b210e1-04e9-4111-984e-b084971501c5.png)

**Comment by Howard20181** [comment]
所以现在是
`Start-Process -PassThru -Verb RunAs ConHost.exe -Args "powershell"`
弹出来的都是用Windows 终端了？

**Comment by kinver** [comment]
> 所以现在是 `Start-Process -PassThru -Verb RunAs ConHost.exe -Args "powershell"` 弹出来的都是用Windows 终端了？

![屏幕截图 2022-10-05 172233](https://user-images.githubusercontent.com/33085738/194027052-4074330f-26b3-4a6f-b45a-f6c1e171bc14.png)

**Comment by Howard20181** [comment]
看到了你的截图
用的是Administrator这个账户安装
这样会直接进行安装而不重新打开另一个Powershell
我看看要怎么改

**Comment by kinver** [comment]
> 看到了你的截图 用的是Administrator这个账户安装 这样会直接进行安装而不重新打开另一个Powershell 我看看要怎么改

我新建了个user用户组的账号，我试试能不能安装

**Comment by kinver** [comment]
user用户组运行run.bat卡这不懂了，也没有安装成功，我估计权限不够：
![屏幕截图 2022-10-05 173019](https://user-images.githubusercontent.com/33085738/194028810-f69d01bf-a64f-4d2b-9799-387d4c9661d1.png)

你先慢慢修改吧，要下班了:joy_cat: 等过几天上班了我再来看看

**Comment by kinver** [comment]
> 看到了你的截图 用的是Administrator这个账户安装 这样会直接进行安装而不重新打开另一个Powershell 我看看要怎么改

克隆了这个commit b092bcefe1bdd42c785cbb0a2571323e0d8b62fb 可以用终端部署了，:ox:

**Comment by Howard20181** [comment]
因为在安装依赖之前检查系统中是否已经有了，可能是直接跳过安装依赖了，不算解决问题，如果以后要求新版本的又会出问题。
________________________________
