### ISSUE TITLE
[Feature Request] Enable voice interaction service for Google Assistant for the w/GApps builds.

### ISSUE THREAD

**Issue by ccelik97** [LSPosed/MagiskOnWSALocal#159]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Yes, as most people expect Google Assistant to work when it's a build with GApps included. :D

### Describe the solution you'd like/描述你想要的解决方案

As recently shown/mentioned [here](https://www.reddit.com/r/WSA/comments/xqw2a2/how_to_access_google_assistant_on_windows_11/) on r/WSA (and I can confirm that it works),  the following command enables voice interaction service for Google Assistant:
```bash
adb shell settings put --user 0 secure voice_interaction_service com.google.android.googlequicksearchbox/com.google.android.voiceinteraction.GsaVoiceInteractionService
```

I'm guessing that creating/adding an entry to a related .xml file (under the directory _/etc/permissions_ or /etc/sysconfig, similarly to those that are found in OpenGApps' Core.tar.xz archives) may solve it.

More info here: https://developer.android.com/reference/android/service/voice/VoiceInteractionService

**Comment by s1204IT** [comment]
That's great.

**Comment by Howard20181** [comment]
I haven't found an easy way to set the default voice assistant app yet, so if you find a way you can remind me.

**Comment by ccelik97** [comment]
> I haven't found an easy way to set the default voice assistant app yet, so if you find a way you can remind me.

I didn't do anything to set it as a default app for anything though. It's WSA with GApps, so the Google app is installed and I only ran that command. As in, if I launch the Android Settings app of WSA and navigate to Apps -> Default Apps it opens Windows' Settings - > Apps -> default apps -> Google page.

It can be run without ADB, but as a privileged user from within an Android system too e.g:
```bash
su -c settings put --user 0 secure voice_interaction_service com.google.android.googlequicksearchbox/com.google.android.voiceinteraction.GsaVoiceInteractionService
```

But the thing with both commands is the fact that it doesn't persist across (WSA) system restarts, hence why I brought up the possibility of setting it via an .xml file in system, similarly to how it's done when an OpenGApps .zip is flashed/used here to repack the WSA system images.

**Comment by someone5678** [comment]
This might can be set by add overlay config to android frameworks
as that is how Pixel device or any custom rom does that

**Comment by Howard20181** [comment]
PR welcome 😉

**Comment by someone5678** [comment]
> This might can be set by add overlay config to android frameworks as that is how Pixel device or any custom rom does that

After testing, No. There's no easy way since default app config is not possible to overlaying with rro.

**Comment by ccelik97** [comment]
Hey, I made a little Magisk module that solves this as a temporary workaround:
Link to Telegram post: [[Magisk] Google Assistant Enable Voice Interaction Service.zip](https://t.me/Mi6RS/736)

Btw Telegram requires an account to download the files from there so I think I should publish such stuff I made over here on GitHub etc too eventually for easier access lol, feel free to reupload it in the meantime.

**Comment by FullyXCode** [comment]
How can we fix play store problem (can't sign in)
