### ISSUE TITLE
Apps icons disappeared after update

### ISSUE THREAD

**Issue by alex-sandro92** [LSPosed/MagiskOnWSALocal#16]
After updating WSA and Magisk with this method all my android apps icons disappeared from start menu and they are not listed in compatibility tab in WSA settings.
Anyway those apps are installed and are working (I can launch them using an utility). Also Magisk and GApps still work.

I already tried running install.ps1 multiple times and restarting my PC.

**Comment by Howard20181** [comment]
This looks like a bug in the WSA itself
It can be temporarily restored by the following steps.
1. Backup `userdata.vhdx`
2、Uninstall WSA
3、Remove the two lines in the installation script that automatically launches Magisk and Play Store after the installation is finished
4、Install WSA
5、Restore `userdata.vhdx
6、Start WSA

The key point is that you can't start WSA before restoring user data.

**Comment by Yvan-W** [comment]
![image](https://user-images.githubusercontent.com/80970174/185622084-2b81f849-4cfd-4cd8-ab80-523ceedf3ad1.png)
是要挂梯子？
