### ISSUE TITLE
希望支持Action构建

### ISSUE THREAD

**Issue by Sunrongguo2008** [LSPosed/MagiskOnWSALocal#174]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

现在的项目不支持Action构建

### Describe the solution you'd like/描述你想要的解决方案

在Action中构建WSA，就像以前一样

**Comment by Howard20181** [comment]
不会支持的，仓库会消失

**Comment by Sunrongguo2008** [comment]
当Action超过一定数量时仓库才会违规，可以新建一个MagiskOnWSAByAction仓库并在一段时间后重建仓库以清零Action数量，这样可以避免仓库违规。

**Comment by Howard20181** [comment]
那你直接干就好
别忘了断开仓库连接

**Comment by Sunrongguo2008** [comment]
我也想做，但是我没有技术能力，没法实现。
