### ISSUE TITLE
[Bug] getting drive errors after a few days installing magiskonwsa

### ISSUE THREAD

**Issue by WaitingKy** [LSPosed/MagiskOnWSALocal#175]
### Steps to reproduce/复现步骤

1. install magiskonwsa
2. wait for a few days
3. issue happens

### Expected behaviour/预期行为

no drive errors

### Actual behaviour/实际行为

getting drive erros pop up. if leave as it is, windows will act weirder and weirder
![1659433386721](https://user-images.githubusercontent.com/11504761/195269006-542a0adf-0f77-438f-b7fd-8a32dbacd244.png)
found a guy that has the same issue but this post is from the old repo and i can't see it
![Screenshot_20221006_082417](https://user-images.githubusercontent.com/11504761/195269099-3f002ce2-e6b6-452c-9a4d-0b9ccdd5b2a5.jpg)

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

2207.40000.8.0

### Linux distribution info/Linux 发行版信息

22.04.1 LTS

### Windows version/Windows 版本

Windows 11 22H2 (OS build: 22621.608)

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand OpenGapps --gapps-variant pico --root-sol magisk
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: OpenGApps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [x] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

[20221012124231.log](https://github.com/LSPosed/MagiskOnWSALocal/files/9762262/20221012124231.log)

**Comment by Howard20181** [comment]
There is no clear evidence that MagiskOnWSA is causing the problem. I am unable to reproduce it. Please let me know if you can find a step that triggers 100%.

**Comment by WaitingKy** [comment]
i always get this error since the first time installing magiskonwsa (version 2203.40000.3.0) until now. don't know how to fix this. i install only 2 apps: tachij2k and vbook

**Comment by Howard20181** [comment]
But I have used this project for so long since its existence and have not encountered this problem. It is recommended to investigate whether the same problem occurs with the Microsoft Store version.

**Comment by WaitingKy** [comment]
i will try installing magiskonwsa again without installing any apks to see if this problem occurs

**Comment by WaitingKy** [comment]
![image](https://user-images.githubusercontent.com/11504761/196422974-3b4d0a45-4efd-42d0-b4a2-5dac67b17535.png)
problem still persists :(

**Comment by Howard20181** [comment]
I don't think it's caused by this project, you can install the official version of WSA
Or check your hardware
