### ISSUE TITLE
WSA无法正常启动

### ISSUE THREAD

**Issue by Sunrongguo2008** [LSPosed/MagiskOnWSALocal#180]
### Steps to reproduce/复现步骤

打开WSA

### Expected behaviour/预期行为

正常启动

### Actual behaviour/实际行为

加载一会之后退出

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

WSA-with-magisk-stable-MindTheGapps_2208.40000.5.0_x64_Release-Nightly

### Linux distribution info/Linux 发行版信息

ubuntu 22.04

### Windows version/Windows 版本

11

### Build Parameters/构建参数

WSA-with-magisk-stable-MindTheGapps_2208.40000.5.0_x64_Release-Nightly

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>
<summary>Details</summary>

</details>

https://user-images.githubusercontent.com/91547012/195766426-b82ee58f-c798-4940-b2ff-a911d5902a9f.mp4

**Comment by Howard20181** [comment]
没有日志不知道原因
请检查WSL2在你的电脑上能否正常工作

**Comment by yuehun** [comment]
> 没有日志不知道原因 请检查WSL2在你的电脑上能否正常工作

也是同样的问题
