### ISSUE TITLE
WSA构建失败

### ISSUE THREAD

**Issue by Sunrongguo2008** [LSPosed/MagiskOnWSALocal#185]
### Steps to reproduce/复现步骤

运行脚本

### Expected behaviour/预期行为

构建WSA

### Actual behaviour/实际行为

构建失败

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

dcc6dcd

### Linux distribution info/Linux 发行版信息

ubuntu22.04

### Windows version/Windows 版本

无关

### Build Parameters/构建参数

![Screenshot_20221015_204511_com realvnc viewer android_edit_312849268555906](https://user-images.githubusercontent.com/91547012/195987144-25ac7a1a-5fd2-42c3-86e1-54524b4bf78b.jpg)

### Version requirement/版本要求

- [x] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

![Screenshot_20221015_203137_com realvnc viewer android_edit_312856570277780](https://user-images.githubusercontent.com/91547012/195987155-1184e0b0-ec43-4fc7-bd4e-200e732f397b.jpg)

**Comment by Howard20181** [comment]
你这系统怎么mount不允许？root权限是假的？
