### ISSUE TITLE
Build failure on Windows 11 22H2

### ISSUE THREAD

**Issue by tonystark79** [LSPosed/MagiskOnWSALocal#19]
I´m getting the following output:

[code]
ARCH=x64
RELEASE_TYPE=retail
MAGISK_VER=stable
GAPPS_VARIANT=pico
REMOVE_AMAZON=remove
ROOT_SOL=magisk

Download WSA
downloading link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/8a26c76e-5a63-42d5-9f7d-df053c273363?P1=1660923563&P2=404&P3=2&P4=eR5IKmKZcsKZfBckw3xiZpz68tHFIlAjXVtgX%2b96usSQ6V8Zo50kIQSTaqRX06hrCauv2zV5l8wJPHiw0O88lg%3d%3d to /root/MagiskOnWSALocal/download/vclibs.appx
downloading link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/605edfa0-3ba9-423b-abb2-aa8da0b0e8f2?P1=1660923547&P2=404&P3=2&P4=NHfYYKhIg13QkBC%2fShvryl3G9fGkNTw8n1IJI8XdUBE2y2jgg7JypyHQNnJ9nhWOtw3P3Y9m0KeJQTXXg3LwCw%3d%3d to /root/MagiskOnWSALocal/download/xaml.appx
downloading link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/dad8ebbc-9e63-4ee6-8dfb-f12fd34669bf?P1=1660951132&P2=404&P3=2&P4=lvPBPC2oQ7CON%2baRCiTODCz2M%2fJZLfi9yXD%2bdqqRbvbG2DrY1b2VyDWUyR4lXIyT9NlRHD8jmcbmHVHHRfQGVA%3d%3d to /root/MagiskOnWSALocal/download/wsa.zip
Download done

Extract WSA
unzipping to /tmp/wsa-build-Y4okGWq1jm_/wsa
unzipping from /tmp/wsa-build-Y4okGWq1jm_/wsa/WsaPackage_2206.40000.15.0_x64_Release-Nightly.msix
done
Extract done

Download Magisk
done

Download OpenGApps
downloading link: https://downloads.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip
Download done

Extract GApps
Extract done

Expand images
e2fsck 1.45.5 (07-Jan-2020)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
system_ext: 83/96 files (1.2% non-contiguous), 33727/33829 blocks
resize2fs 1.45.5 (07-Jan-2020)
resize2fs: New size smaller than minimum (33727)

An error occurs, exit
Cleanup Work Directory
Cleanup Download Directory
root@vmWin11:~/MagiskOnWSALocal/scripts#
[/code]

I don´t know where are the log files...

**Comment by tonystark79** [comment]
Complement: 

I´m running this on WSL Ubuntu 20.04 LTS!

**Comment by Howard20181** [comment]
Try again
I don't know why `du` is getting the incorrect size of `system_ext`.

**Comment by tonystark79** [comment]
Tried again, got past the first error, now I have a newer one...
------------------------------------------------------------------------------------------
ARCH=x64
RELEASE_TYPE=retail
MAGISK_VER=stable
GAPPS_VARIANT=pico
REMOVE_AMAZON=keep
ROOT_SOL=magisk

Download WSA
downloading link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/8a26c76e-5a63-42d5-9f7d-df053c273363?P1=1660942251&P2=404&P3=2&P4=m%2fcRp9kB55woIVSQhQzTIFmZ4TbrVOaCW%2bbM5Vq1hpnUAoy5LRuv29vp1HKOSCIhB3UXuCQnlTn0A7QnjWhwsA%3d%3d to /home/nascimento/MagiskOnWSALocal/download/vclibs.appx
downloading link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/605edfa0-3ba9-423b-abb2-aa8da0b0e8f2?P1=1660942254&P2=404&P3=2&P4=bXhTsT6WvrSazhF6bwIL3lnJy%2fobAE1Y6xYV%2bzg2ZQaS8TLKrA9w21qqGsAaVkmJgnpdMN7XHa7VFLMGzZliYQ%3d%3d to /home/nascimento/MagiskOnWSALocal/download/xaml.appx
downloading link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/dad8ebbc-9e63-4ee6-8dfb-f12fd34669bf?P1=1660969840&P2=404&P3=2&P4=BW5IAwECWYRfofx1VHo6fDCa46EX3EYiL08jHeGni%2fkgTTy5X5VXHtlfVhIhyJdwmWcF07Y9wUNLYlqtpX68dQ%3d%3d to /home/nascimento/MagiskOnWSALocal/download/wsa.zip
Download done

Extract WSA
unzipping to /tmp/wsa-build-8pESpuvfa4_/wsa
unzipping from /tmp/wsa-build-8pESpuvfa4_/wsa/WsaPackage_2206.40000.15.0_x64_Release-Nightly.msix
done
Extract done

Download Magisk
done

Download OpenGApps
downloading link: https://downloads.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip
Download done

Extract GApps
Extract done

Expand images
e2fsck 1.45.5 (07-Jan-2020)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
system_ext: 83/96 files (1.2% non-contiguous), 33727/33829 blocks
resize2fs 1.45.5 (07-Jan-2020)
Resizing the filesystem on /tmp/wsa-build-8pESpuvfa4_/wsa/x64/system_ext.img to 37316 (4k) blocks.
The filesystem on /tmp/wsa-build-8pESpuvfa4_/wsa/x64/system_ext.img is now 37316 (4k) blocks long.

e2fsck 1.45.5 (07-Jan-2020)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
product: 153/192 files (0.0% non-contiguous), 80266/80507 blocks
resize2fs 1.45.5 (07-Jan-2020)
Resizing the filesystem on /tmp/wsa-build-8pESpuvfa4_/wsa/x64/product.img to 84423 (4k) blocks.
The filesystem on /tmp/wsa-build-8pESpuvfa4_/wsa/x64/product.img is now 84423 (4k) blocks long.

e2fsck 1.45.5 (07-Jan-2020)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 3A: Optimizing directories
Pass 4: Checking reference counts
Pass 5: Checking group summary information

/: ***** FILE SYSTEM WAS MODIFIED *****
/: 2679/2688 files (0.4% non-contiguous), 211645/226940 blocks
resize2fs 1.45.5 (07-Jan-2020)
Resizing the filesystem on /tmp/wsa-build-8pESpuvfa4_/wsa/x64/system.img to 309860 (4k) blocks.
The filesystem on /tmp/wsa-build-8pESpuvfa4_/wsa/x64/system.img is now 309860 (4k) blocks long.

e2fsck 1.45.5 (07-Jan-2020)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 3A: Optimizing directories
Pass 4: Checking reference counts
Pass 5: Checking group summary information

vendor: ***** FILE SYSTEM WAS MODIFIED *****
vendor: 1349/1392 files (0.9% non-contiguous), 89253/89522 blocks
resize2fs 1.45.5 (07-Jan-2020)
Resizing the filesystem on /tmp/wsa-build-8pESpuvfa4_/wsa/x64/vendor.img to 93636 (4k) blocks.
The filesystem on /tmp/wsa-build-8pESpuvfa4_/wsa/x64/vendor.img is now 93636 (4k) blocks long.

Expand images done

Mount images
mount: /tmp/wsa-build-8pESpuvfa4_/system: mount failed: Operation not permitted.
An error occurs, exit
Cleanup Work Directory
umount: /tmp/wsa-build-8pESpuvfa4_/system: not mounted.
Cleanup Download Directory
root@vmWin11:/home/nascimento/MagiskOnWSALocal/scripts#
-------------------------------------------------------------------------------------------------------------------------

**Comment by Howard20181** [comment]
What version of WSL do you have?
Run `wsl -l -v` under Powershell and send the results.

**Comment by tonystark79** [comment]
PS C:\Users\Nascimento> wsl -l -v
  NAME          STATE           VERSION
* Ubuntu        Stopped         2
  kali-linux    Stopped         2
  Debian        Stopped         2
PS C:\Users\Nascimento>

All failures happened while running under Ubuntu (20.04)

**Comment by tonystark79** [comment]
Finally, worked last night!!!! 

Whatever errors I had last week, were fixed in the time being! 

Thanx and keep up the good work! :))
