### ISSUE TITLE
能否把WSA封装为.msixbundle格式？

### ISSUE THREAD

**Issue by Sunrongguo2008** [LSPosed/MagiskOnWSALocal#201]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

使用.msixbundle格式，就不用关心能否删除安装的文件夹

### Describe the solution you'd like/描述你想要的解决方案

把WSA封装为.msixbundle格式

**Comment by Howard20181** [comment]
没必要，封装成msixbundle后还要手动安装自签证书
安装时又多了一个步骤

**Comment by Howard20181** [comment]
而且更新不需要删除旧的安装文件
只要关闭WSA，直接覆盖，重新运行安装脚本
