### ISSUE TITLE
[Feature Request] Ability to use files already in download folder for build.sh

### ISSUE THREAD

**Issue by mriamnobody** [LSPosed/MagiskOnWSALocal#205]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Currently, whenever we run the build.sh command, all the files are downloaded even if they are already in the download folder. There are two issues. First: The download speed is extremely slow most of the time. People with slow internet or with low bandwidth will face issues with this. Second: even if the required files are already in the download folder downloaded moments ago through the build.sh the script will again download the files. This again raises the First issue.

### Describe the solution you'd like/描述你想要的解决方案

It would be great if some modifications could be made to the script to allow/accept the already downloaded files present in the download folder. I know this interferes if the user wants to update the already installed instance of WSA, but it would be great if the script asks the user the same while executing the build.sh that if the user wants to update installation with the files already present in the download folder

**Comment by Howard20181** [comment]
The logic now is that already downloaded files are reused and do not need to be re-downloaded, only the download link needs to be regenerated to check if the already downloaded file is up-to-date or complete.
If you want to skip the completeness or version check you can use the offline mode, check the help info of the command line tool
`build.sh --help`

Howard
________________________________
From: Roshanlal ***@***.***>
Sent: Saturday, October 22, 2022 2:27:14 PM
To: LSPosed/MagiskOnWSALocal ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LSPosed/MagiskOnWSALocal] [Feature Request] Ability (Issue #205)


Is your feature request related to a problem?/你的请求是否与某个问题相关？

Currently, whenever we run the build.sh command, all the files are downloaded even if they are already in the download folder. There are two issues. First: The download speed is extremely slow most of the time. People with slow internet or with low bandwidth will face issues with this. Second: even if the required files are already in the download folder downloaded moments ago through the build.sh the script will again download the files. This again raises the First issue.

Describe the solution you'd like/描述你想要的解决方案

It would be great if some modifications could be made to the script to allow/accept the already downloaded files present in the download folder. I know this interferes if the user wants to update the already installed instance of WSA, but it would be great if the script asks the user the same while executing the build.sh that if the user wants to update installation with the files already present in the download folder

Additional context/其他信息

No response

―

**Comment by mriamnobody** [comment]
Got it. I will add the process to extract msix bundle file and get the WSA.zip file if a user wants to run build.sh in offline mode in the readme.
