### ISSUE TITLE
[Feature Request] Ability to select WSA version while running build.sh

### ISSUE THREAD

**Issue by mriamnobody** [LSPosed/MagiskOnWSALocal#206]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

As of now build.sh by default downloads the WSA Stable. 

### Describe the solution you'd like/描述你想要的解决方案

It can be made by editing the build.sh, but it would be great if the build.sh asks which version of WSA to download.

**Comment by Howard20181** [comment]
`build.sh --release-type WIF`

**Comment by mriamnobody** [comment]
I will update this in the readme file
