### ISSUE TITLE
Wn 11 Pro 22H2 Dev channel insider - Deployment ERROR

### ISSUE THREAD

**Issue by isafadi** [LSPosed/MagiskOnWSALocal#21]
Everything went smoothly untill Installing MagiskOnWSA. Tried many ways but nothing worked
![Screenshot_2](https://user-images.githubusercontent.com/90141046/185745443-67fc0cce-2c7d-4dc2-909c-bf197ddfde30.png)

**Comment by isafadi** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/90141046/185745606-e2da5830-7030-423b-a022-b41499698749.png)
I just need to know the issue with the AppxManifest file or with the install.ps1 file !! Could not solve it , I will appreciate it if you can help me

**Comment by Howard20181** [comment]
Try changing the wsa folder to another drive
