### ISSUE TITLE
Win11 21H2 wsl Ubuntu-22.04报错

### ISSUE THREAD

**Issue by sst2020** [LSPosed/MagiskOnWSALocal#22]
ARCH=x64
RELEASE_TYPE=release preview
MAGISK_VER=stable
GAPPS_VARIANT=pico
REMOVE_AMAZON=keep
ROOT_SOL=magisk

Download WSA
downloading link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/8a26c76e-5a63-42d5-9f7d-df053c273363?P1=1660997879&P2=404&P3=2&P4=IEAHwvFY399uSsFGF%2bvovwE9AsWzhy4nJ8eQHsIkD0AQA%2fH2qt9EWRmp%2b%2bTHIKM1gMO9J%2bPt0oDUStbSr%2fKchQ%3d%3d to /MagiskOnWSALocal-main/download/vclibs.appx
downloading link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/605edfa0-3ba9-423b-abb2-aa8da0b0e8f2?P1=1660997856&P2=404&P3=2&P4=WCBUwPVw7lMHxYDkmagPULTwQOpIDEpGo8tumk8Uiw9lfcQjLvKJj07Q%2bEJf9vInkKXqzuJASqhh4uUWE7bJCw%3d%3d to /MagiskOnWSALocal-main/download/xaml.appx
downloading link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/dad8ebbc-9e63-4ee6-8dfb-f12fd34669bf?P1=1661025446&P2=404&P3=2&P4=YyThPNUGlh3xgSQm5%2fa%2bO7i6xTqgp%2fhXaXVZy1taf6IeOadpQFFwpDbxYq0VMvReKPBLHNK7GMkaxgKrbuENLg%3d%3d to /MagiskOnWSALocal-main/download/wsa.zip
Download done

Extract WSA
unzipping to /tmp/wsa-build-Xsk0FbhmkZ_/wsa
unzipping from /tmp/wsa-build-Xsk0FbhmkZ_/wsa/WsaPackage_2206.40000.15.0_x64_Release-Nightly.msix
done
Extract done

Download Magisk
done

Download OpenGApps
downloading link: https://downloads.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip
Download done

Extract GApps
Extract done

Expand images
e2fsck 1.46.5 (30-Dec-2021)
第 1 遍：检查 inode、块，和大小
第 2 遍：检查目录结构
第 3 遍：检查目录连接性
第 4 遍：检查引用计数
第 5 遍：检查组概要信息
system_ext：83/96 文件（1.2% 为非连续的），33727/33829 块
resize2fs 1.46.5 (30-Dec-2021)
将 /tmp/wsa-build-Xsk0FbhmkZ_/wsa/x64/system_ext.img 上的文件系统调整为 37316 个块（每块 4k）。
/tmp/wsa-build-Xsk0FbhmkZ_/wsa/x64/system_ext.img 上的文件系统大小已经调整为 37316 个块（每块 4k）。

e2fsck 1.46.5 (30-Dec-2021)
第 1 遍：检查 inode、块，和大小
第 2 遍：检查目录结构
第 3 遍：检查目录连接性
第 4 遍：检查引用计数
第 5 遍：检查组概要信息
product：153/192 文件（0.0% 为非连续的），80266/80507 块
resize2fs 1.46.5 (30-Dec-2021)
将 /tmp/wsa-build-Xsk0FbhmkZ_/wsa/x64/product.img 上的文件系统调整为 84423 个块（每块 4k）。
/tmp/wsa-build-Xsk0FbhmkZ_/wsa/x64/product.img 上的文件系统大小已经调整为 84423 个块（每块 4k）。

e2fsck 1.46.5 (30-Dec-2021)
第 1 遍：检查 inode、块，和大小
第 2 遍：检查目录结构
第 3 遍：检查目录连接性
第 3A 遍：优化目录
第 4 遍：检查引用计数
第 5 遍：检查组概要信息

/：***** 文件系统已被修改 *****
/：2679/2688 文件（0.4% 为非连续的），211645/226940 块
resize2fs 1.46.5 (30-Dec-2021)
将 /tmp/wsa-build-Xsk0FbhmkZ_/wsa/x64/system.img 上的文件系统调整为 309860 个块（每块 4k）。
/tmp/wsa-build-Xsk0FbhmkZ_/wsa/x64/system.img 上的文件系统大小已经调整为 309860 个块（每块 4k）。

e2fsck 1.46.5 (30-Dec-2021)
第 1 遍：检查 inode、块，和大小
第 2 遍：检查目录结构
第 3 遍：检查目录连接性
第 3A 遍：优化目录
第 4 遍：检查引用计数
第 5 遍：检查组概要信息

vendor：***** 文件系统已被修改 *****
vendor：1349/1392 文件（0.9% 为非连续的），89253/89522 块
resize2fs 1.46.5 (30-Dec-2021)
将 /tmp/wsa-build-Xsk0FbhmkZ_/wsa/x64/vendor.img 上的文件系统调整为 93636 个块（每块 4k）。
/tmp/wsa-build-Xsk0FbhmkZ_/wsa/x64/vendor.img 上的文件系统大小已经调整为 93636 个块（每块 4k）。

Expand images done

Mount images
done

Integrate Magisk
#!/system/bin/sh
mkdir -p /data/adb/magisk
cp /sbin/* /data/adb/magisk/
chmod -R 755 /data/adb/magisk
restorecon -R /data/adb/magisk
for module in $(ls /data/adb/modules); do
    if ! [ -f "/data/adb/modules/$module/disable" ] && [ -f "/data/adb/modules/$module/sepolicy.rule" ]; then
        /sbin/magiskpolicy --live --apply "/data/adb/modules/$module/sepolicy.rule"
    fi
done
/dev/FYMyZNfj(/.*)?    u:object_r:magisk_file:s0
/data/adb/magisk(/.*)?   u:object_r:magisk_file:s0
sudo: unable to execute /tmp/wsa-build-Xsk0FbhmkZ_/magisk/magiskpolicy: Permission denied
on post-fs-data
    start adbd
    mkdir /dev/FYMyZNfj
    mount tmpfs tmpfs /dev/FYMyZNfj mode=0755
    copy /sbin/magisk64 /dev/FYMyZNfj/magisk64
    chmod 0755 /dev/FYMyZNfj/magisk64
    symlink ./magisk64 /dev/FYMyZNfj/magisk
    symlink ./magisk64 /dev/FYMyZNfj/su
    symlink ./magisk64 /dev/FYMyZNfj/resetprop
    copy /sbin/magisk32 /dev/FYMyZNfj/magisk32
    chmod 0755 /dev/FYMyZNfj/magisk32
    copy /sbin/magiskinit /dev/FYMyZNfj/magiskinit
    chmod 0755 /dev/FYMyZNfj/magiskinit
    copy /sbin/magiskpolicy /dev/FYMyZNfj/magiskpolicy
    chmod 0755 /dev/FYMyZNfj/magiskpolicy
    mkdir /dev/FYMyZNfj/.magisk 700
    mkdir /dev/FYMyZNfj/.magisk/mirror 700
    mkdir /dev/FYMyZNfj/.magisk/block 700
    copy /sbin/magisk.apk /dev/FYMyZNfj/stub.apk
    rm /dev/.magisk_unblock
    start VG8tndZ6kw2L
    start 1rjRRJmVQlGH
    wait /dev/.magisk_unblock 40
    rm /dev/.magisk_unblock

service VG8tndZ6kw2L /system/bin/sh /sbin/loadpolicy.sh
    user root
    seclabel u:r:magisk:s0
    oneshot

service 1rjRRJmVQlGH /dev/FYMyZNfj/magisk --post-fs-data
    user root
    seclabel u:r:magisk:s0
    oneshot

service Q9sMIzobh4HY /dev/FYMyZNfj/magisk --service
    class late_start
    user root
    seclabel u:r:magisk:s0
    oneshot

on property:sys.boot_completed=1
    mkdir /data/adb/magisk 755
    copy /sbin/magisk.apk /data/adb/magisk/magisk.apk
    start 42oJgODUliht

service 42oJgODUliht /dev/FYMyZNfj/magisk --boot-complete
    user root
    seclabel u:r:magisk:s0
    oneshot
Integrate Magisk done

Merge Language Resources
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resources targetOsVersion="10.0.0" majorVersion="1">
<index root="\" startIndexAt="\">
    <indexer-config type="folder" foldernameAsQualifier="true" filenameAsQualifier="true" qualifierDelimiter="."/>
    <indexer-config type="PRI"/>
</index>
</resources>
0064:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0024:fixme:nls:RtlSetThreadPreferredUILanguages 256, 0000000000000000, 0000000000000000
0024:fixme:heap:RtlSetHeapInformation 0000000001400000 0 000000000021E420 4 stub
0024:fixme:heap:RtlSetHeapInformation 0000000001400000 0 000000000021E420 4 stub
Index Pass Completed.
AlternateForm Qualifiers: LIGHTUNPLATED,UNPLATED
Language Qualifiers: EN-US,EN-GB,AF-ZA,AR-SA,AZ-LATN-AZ,BG-BG,BS-LATN-BA,CA-ES,CS-CZ,CY-GB,DA-DK,DE-DE,EL-GR,ES-ES,ES-MX
,ET-EE,EU-ES,FA-IR,FI-FI,FR-CA,FR-FR,GL-ES,HE-IL,HI-IN,HR-HR,HU-HU,ID-ID,IS-IS,IT-IT,JA-JP,KA-GE,KK-KZ,KO-KR,LT-LT,LV-LV
,MS-MY,NB-NO,NL-NL,NN-NO,PL-PL,PT-BR,PT-PT,QPS-PLOC,QPS-PLOCA,QPS-PLOCM,RO-RO,RU-RU,SK-SK,SL-SI,SQ-AL,SR-CYRL-RS,SR-LATN
-RS,SV-SE,TH-TH,TR-TR,UK-UA,VI-VN,ZH-CN,ZH-TW
Scale Qualifiers: 200,400,150,125,100
TargetSize Qualifiers: 256,16,20,24,30,32,36,40,48,60,64,72,80,96

Finished building
Version: 1.0
Resource Map Name: MicrosoftCorporationII.WindowsSubsystemForAndroid
Named Resources: 235
Resource Candidates: 9787
Successfully Completed
Merge Language Resources done

Add extra packages
chcon: 改变 '/tmp/wsa-build-Xsk0FbhmkZ_/system/system/priv-app/BuiltInPrintService/lib/x86_64/libcups.so' 的上下文到 “u:object_r:system_file:s0” 失败: 没有那个文件或目录
chcon: 改变 '/tmp/wsa-build-Xsk0FbhmkZ_/system/system/priv-app/BuiltInPrintService/lib/x86_64/libwfds.so' 的上下文到 “u:object_r:system_file:s0” 失败: 没有那个文件或目录
Add extra packages done

Integrate GApps
chown: 无法取消'/tmp/wsa-build-Xsk0FbhmkZ_/system/system/app/PrintSpooler/lib/x86_64/libprintspooler_jni.so' 的引用: 没
有那个文件或目录
chown: 无法取消'/tmp/wsa-build-Xsk0FbhmkZ_/system/system/app/Bluetooth/lib/x86_64/libbluetooth_jni.so' 的引用: 没有那个 文件或目录
chown: 无法取消'/tmp/wsa-build-Xsk0FbhmkZ_/system/system/priv-app/BuiltInPrintService/lib/x86_64/libcups.so' 的引用: 没
有那个文件或目录
chown: 无法取消'/tmp/wsa-build-Xsk0FbhmkZ_/system/system/priv-app/BuiltInPrintService/lib/x86_64/libwfds.so' 的引用: 没 有那个文件或目录
chown: 无法取消'/tmp/wsa-build-Xsk0FbhmkZ_/system/product/app/Camera2/lib/x86_64/libjni_tinyplanet.so' 的引用: 没有那个
文件或目录
chown: 无法取消'/tmp/wsa-build-Xsk0FbhmkZ_/system/product/app/Camera2/lib/x86_64/libjni_jpegutil.so' 的引用: 没有那个文 件或目录
chown: 无法取消'/tmp/wsa-build-Xsk0FbhmkZ_/system/product/app/Gallery2/lib/x86_64/libjni_jpegstream.so' 的引用: 没有那个文件或目录
chown: 无法取消'/tmp/wsa-build-Xsk0FbhmkZ_/system/product/app/Gallery2/lib/x86_64/libjni_filtershow_filters.so' 的引用: 没有那个文件或目录
chown: 无法取消'/tmp/wsa-build-Xsk0FbhmkZ_/system/product/app/Gallery2/lib/x86_64/libjni_eglfence.so' 的引用: 没有那个文件或目录
find: ‘/tmp/wsa-build-Xsk0FbhmkZ_/system/product/lib’: 没有那个文件或目录
find: ‘/tmp/wsa-build-Xsk0FbhmkZ_/system/product/lib’: 没有那个文件或目录
find: ‘/tmp/wsa-build-Xsk0FbhmkZ_/system/product/lib’: 没有那个文件或目录
find: ‘/tmp/wsa-build-Xsk0FbhmkZ_/system/product/lib’: 没有那个文件或目录
find: ‘/tmp/wsa-build-Xsk0FbhmkZ_/system/product/lib’: 没有那个文件或目录
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
sudo: unable to execute /tmp/wsa-build-Xsk0FbhmkZ_/magisk/magiskpolicy: Permission denied
An error occurs, exit
Cleanup Work Directory
Cleanup Download Directory

**Comment by Howard20181** [comment]
重试过了吗？
不知道为什么你sudo都没权限运行magiskpolicy
我本地是好的

**Comment by sst2020** [comment]
重试过三次，都这样。。。

**Comment by Howard20181** [comment]
刚刚我重装了WSL2 Ubuntu 22.04
无法复现，正常编译
你再试试吧

**Comment by tjsky** [comment]
> 重试过了吗？ 不知道为什么你sudo都没权限运行magiskpolicy 我本地是好的

WSL的话，可以尝试一下先`sudo chmod -R 777 /工作目录`再执行`scripts/run.sh`

我实际没遇到过这个问题，是其他遇到Permission denied的人告知解决方法
