### ISSUE TITLE
Support to OpenGL ES 3.1 - can be it possible?

### ISSUE THREAD

**Issue by Special-Niewbie** [LSPosed/MagiskOnWSALocal#223]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Hello,

I cannot find no were (except some sporadic little mentions around)  this problem inherent WSA and OpenGL ES 3.1.

I'm not clear why, and how, can be implemented (at least ) the OpenGL ES 3.1 into WSA; as some Android app it request it as minimum specs.

On internet I found this prject: https://github.com/google/angle 

It's `ANGLE` a solution to implement in different OSes (included WIndows?!) to support the `OpenGL ES 3.1` as they listed out that can be translated the OGL ES 3.1 to `Vulkan, desktop OpenGL, OpenGL ES` (for now and to `Direct3D 11` it's on working progress)?

### Describe the solution you'd like/描述你想要的解决方案

Can be possible to implenmt OpenGL ES 3.1 into WSA?

**Comment by Howard20181** [comment]
Ask Microsoft for help
