### ISSUE TITLE
Broken execution sequence causes Busybox being copied concurrently

### ISSUE THREAD

**Issue by alexwilson1** [LSPosed/MagiskOnWSALocal#224]
### Steps to reproduce/复现步骤

- Install WSA with Magisk (WSA-with-magisk-GApps-pico_x64, WSA_VER=2206.40000.15.0, WSA_MAIN_VER=2206)
- Enable Zygisk
- Reboot
- Install lsposed
- Reboot
- Install lsposed manager using shell apk method
- Open lsposed manager, it works
- Restart WSA/terminate process
- Open lsposed manager
- 'lsposed is not found' (sometimes it works, sometimes it doesn't)
![image](https://user-images.githubusercontent.com/25535957/185045066-07dcc05b-228a-4062-bf02-34aa99fb4f84.png)
![image](https://user-images.githubusercontent.com/25535957/185045529-01f42fc8-94f4-4c39-90d2-ab8be9e4fc61.png)

### Expected behaviour/预期行为

LSPosed should be running all the time and LSPosed Manager should detect the installation

### Actual behaviour/实际行为

When rebooting WSA, LSPosed manager often does not detect LSPosed. I have tried many other versions (including riru versions) and they all exhibit the same behavior. I have also tried different installations of Windows 11.

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk - lsposed
```

### LSPosed version/LSPosed 版本

LSPosed-v1.8.3-6597-zygisk-debug

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25201

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[magisk_log_2022-08-16T22.44.20.log](https://github.com/LSPosed/LSPosed/files/9356715/magisk_log_2022-08-16T22.44.20.log)

**Comment by Howard20181** [comment]
@alexwilson1 Can you try building with the [debug-magisk](https://github.com/LSPosed/MagiskOnWSALocal/tree/debug-magisk) branch?
Just located an issue and need to confirm if it's fully fixed.

**Comment by Howard20181** [comment]
Also, you can use the debug version of Magisk from https://github.com/LSPosed/Metagisk/actions/runs/3334710111 with more logs

**Comment by alexwilson1** [comment]
Seems to be working perfectly now. I just used WSA-with-magisk-stable-MindTheGapps_2209.40000.26.0_x64_Release-Nightly.zip (didn't use the debug magisk or debig-magisk branch). Thanks for fixing this.
