### ISSUE TITLE
Save WSA in friendly name folder or in zip archive

### ISSUE THREAD

**Issue by EverchangerL** [LSPosed/MagiskOnWSALocal#23]
Hello, I have a suggestion.

On the previous repo we were getting WSA build from Github Actions in a Zip archive with friendly name like `WSA-GApps-pico_2206.40000.15.0_x64_Release-Nightly.zip`.

In this solution we are getting WSA files in output folder which is less convenient for me.

Can we please save multiple WSA builds in appropriate folder like `../MagiskOnWSALocal/output/WSA-GApps-pico_2206.40000.15.0_x64_Release-Nightly` or better yet have an option to compress WSA build into Zip archive with appropriate filename?

Thank you for all your hard work.

**Comment by Howard20181** [comment]
Folder names will try to change to something more friendly.
Not compressing now is considering that local generation of outputs will move the content directly to where it is needed, rather than distributing it. Perhaps an option could be added to ask if compression is needed.
