### ISSUE TITLE
希望增加脚本的版本号

### ISSUE THREAD

**Issue by Sunrongguo2008** [LSPosed/MagiskOnWSALocal#231]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

当前的脚本没有版本号，拥有版本号可以快速确认使用的是否为最新版本

### Describe the solution you'd like/描述你想要的解决方案

建议在README中描述脚本修改的最新日期或公布版本号

**Comment by Howard20181** [comment]
但是现在反馈都要求说一下commit SHA
如果增加版本号每次都要手动+1，也会出现忘记的情况
所以干脆反馈就一定写明commit SHA看一眼就知道是哪个了
另外commit SHA在这里可以直接点击复制
![image](https://user-images.githubusercontent.com/40033067/198835647-04e8b68c-0cd6-46cb-b93a-e7e67e4972d4.png)
