### ISSUE TITLE
MindTheGapps下载速度太慢

### ISSUE THREAD

**Issue by Sunrongguo2008** [LSPosed/MagiskOnWSALocal#234]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

MindTheGapps下载速度太慢
![Screenshot_20221031_195113](https://user-images.githubusercontent.com/91547012/199006262-e116b257-6d39-4f68-9fab-35a6673251c3.jpg)

### Describe the solution you'd like/描述你想要的解决方案

可以把MindTheGapps.zip下载好，挂在github上，让脚本直接从github下载

**Comment by Howard20181** [comment]
不需要
现实是大部分地区 Github 比较难连

**Comment by Sunrongguo2008** [comment]
有别的办法吗？DL:2kib令人无法等待

**Comment by Howard20181** [comment]
重试几遍吧，sourceforge有很多CDN的，连上近的能跑满你的带宽的
而Github在国内很多地方被墙了，换过去更加糟糕
