### ISSUE TITLE
增加脚本自动更新功能

### ISSUE THREAD

**Issue by Sunrongguo2008** [LSPosed/MagiskOnWSALocal#237]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

每次要查看脚本是否最新

### Describe the solution you'd like/描述你想要的解决方案

希望脚本自动更新

**Comment by Howard20181** [comment]
要做的话就只是自动`git reset --hard`然后`git pull`
貌似手动的也没差
而且有些人还不是用git获取的也不行

**Comment by Sunrongguo2008** [comment]
还有就是
