### ISSUE TITLE
[Bug] Incompatible apps

### ISSUE THREAD

**Issue by zero64801** [LSPosed/MagiskOnWSALocal#242]
### Steps to reproduce/复现步骤

Open specific app with minimum model requirement in gapps.

### Expected behaviour/预期行为

Should be able to download the app regardless

### Actual behaviour/实际行为

You won't be able to download the app because it says Pixel 5 isn't supported.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

0dba40de228812c6e48714a2e8d98c2260ded3fe

### Linux distribution info/Linux 发行版信息

Ubuntu

### Windows version/Windows 版本

10.0.22000.978

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico  --root-sol magisk
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>
<summary>Details</summary>

</details>

**Comment by Howard20181** [comment]
Which apps?
On which models you can download?

**Comment by zero64801** [comment]
> Which apps? On which models you can download?

I tried in this game https://play.google.com/store/apps/details?id=com.proximabeta.nikke&hl=pt_BR&gl=US I can download it in other emulators(bluestacks) or my phone (xiaomi mi 9)

**Comment by Howard20181** [comment]
Have you tried to register the device ID? https://www.google.com/android/uncertified/

**Comment by zero64801** [comment]
> Have you tried to register the device ID? https://www.google.com/android/uncertified/

Yes the app still don't show up in play store through WSA and when trying to download from google play website it says

Google Pixel 5
This item is not compatible with your device.

**Comment by Howard20181** [comment]
Maybe the game needs to pass SafetyNet detection to be downloaded, which is not possible for WSA.
