### ISSUE TITLE
build.sh: line 348: 583489 Segmentation fault 

### ISSUE THREAD

**Issue by Yofo-me** [LSPosed/MagiskOnWSALocal#243]
### Steps to reproduce/复现步骤

执行run.sh后，选择好magisk  gapps 等信息后，编译报错。

### Expected behaviour/预期行为

正常编译

### Actual behaviour/实际行为

COMMAND_LINE=--arch x64 --release-type RP --magisk-ver beta --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk --compress
INFO: Architecture: x64
INFO: Release Type: RP
INFO: Magisk Version: beta
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Release Preview
Generate Download Links
Generating WSA download link: arch=x64 release_type=Release Preview
download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/605edfa0-3ba9-423b-abb2-aa8da0b0e8f2?P1=1667709098&P2=404&P3=2&P4=AcF9sExs70EWl2XeMvVLps1qxBhiV3tSl0ISRwAwhWNgTsAaKZl61ZZhoz2ys3NkdXDA%2fU%2bUJPtSOQdBoDA7vg%3d%3d to /home/yoki/MagiskOnWSALocal/download/xaml-x64.appx
download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/389e1818-5b5f-4d75-b112-12f350f97d96?P1=1667736343&P2=404&P3=2&P4=J2ZCowLBUM84BXruUglfvbw85rmKP3QojXcJq7GGbcdbWxvKW91wFa6VCPULFJJPUldVTGaG5MPV1ymR1wMkMA%3d%3d to /home/yoki/MagiskOnWSALocal/download/wsa-x64-RP.zip
Generating Magisk download link: release type=beta
download link: https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@25.2/app-release.apk
Generating MindTheGapps download link: arch=x64 variant=pico
download link: https://downloads.sourceforge.net/project/wsa-mtg/x86_64/20220910/MindTheGapps-12.1.0-x86_64-20220910_001624.zip
Download Artifacts

11/06 12:20:03 [NOTICE] Downloading 5 item(s)
./build.sh: line 348: 586744 Segmentation fault      aria2c --no-conf --log-level=info --log="$DOWNLOAD_DIR/aria2_download.log" -x16 -s16 -j5 -c -R -m0 --async-dns=false --check-integrity=true --continue=true --allow-overwrite=true --conditional-get=true -d"$DOWNLOAD_DIR" -i"$DOWNLOAD_DIR"/"$DOWNLOAD_CONF_NAME"
We have encountered an error while downloading files.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

Main

### Linux distribution info/Linux 发行版信息

Ubuntu 20.04

### Windows version/Windows 版本

19042.2130

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type RP --magisk-ver beta --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk --compress
INFO: Architecture: x64
INFO: Release Type: RP
INFO: Magisk Version: beta
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Release Preview
Generate Download Links

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

![image](https://user-images.githubusercontent.com/55388087/200154021-9def40e4-c1f9-4d36-9eaa-ec2ca333ce75.png)

**Comment by Howard20181** [comment]
更新aria2再试

**Comment by Yofo-me** [comment]
> 更新 aria2 再试

yoki@vmi957003:~/MagiskOnWSALocal$ aria2c -v
aria2 version 1.36.0
Copyright (C) 2006, 2019 Tatsuhiro Tsujikawa

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

** Configuration **

最新版的了

**Comment by Howard20181** [comment]
那不知道了，崩溃的不是脚本是aria2

Howard
________________________________
