### ISSUE TITLE
[Bug] generateWSALinks.py

### ISSUE THREAD

**Issue by Hatsune-Mikun** [LSPosed/MagiskOnWSALocal#244]
### Steps to reproduce/复现步骤

![image](https://user-images.githubusercontent.com/47102682/200176754-ba0070db-3233-4b74-bbd5-d958deb9e97c.png)
This happens with me when i try to `run.sh`, i have been tried another presets, but same here

### Expected behaviour/预期行为

Should to keep install

### Actual behaviour/实际行为

Not installing, infinity black screen until CTRL + C

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

https://github.com/LSPosed/MagiskOnWSALocal/tree/0dba40de228812c6e48714a2e8d98c2260ded3fe

### Linux distribution info/Linux 发行版信息

Ubuntu 20.04 LTS

### Windows version/Windows 版本

Win 11, 21H2 22000.795

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand OpenGApps --gapps-variant pico --remove-amazon --root-sol magisk --compress    --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: OpenGApps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>
<summary>Details</summary>
![image](https://user-images.githubusercontent.com/47102682/200176754-ba0070db-3233-4b74-bbd5-d958deb9e97c.png)
</details>

**Comment by Hatsune-Mikun** [comment]
![image](https://user-images.githubusercontent.com/47102682/200177265-aa4a3a32-00a8-4595-9c83-1ea5716dfb5b.png)
When i tried build.sh, i got another one problem, that's `generateMagiskLink.py`

**Comment by Howard20181** [comment]
Check your Internet connection

**Comment by Hatsune-Mikun** [comment]
If i had bad internet connection, i even not be able to write here, but i'm online, playing the game, using browser and have a call in Discord, so what's problem?
If i gonna follow link i will download the package with 12mb in sec speed, so, maybe you gonna check your lines in a code?
![image](https://user-images.githubusercontent.com/47102682/200177509-1c360451-0f24-4028-97c5-006bc1d7c567.png)

**Comment by Howard20181** [comment]
I just checked and found no problems before replying to you.

**Comment by Hatsune-Mikun** [comment]
![image](https://user-images.githubusercontent.com/47102682/200177852-4417a509-040e-4974-9100-866da20e42cd.png)
Okay, now i was reupload repo, and start it again, and it's finally started, but freeze at Magisk download link, but i was follow link and see that's have 1.3 gb size, so i'll wait around 10 minutes and let you know if it's finished or not

**Comment by Hatsune-Mikun** [comment]
Just freeze and all, nothing wrong, rerun of scripts even didn'y pass generate download links, i'll try just reboot my PC, if it's gonna help i'll let you know

**Comment by Hatsune-Mikun** [comment]
![image](https://user-images.githubusercontent.com/47102682/200178799-fb054542-35f1-433b-a943-a4f030301c67.png)
Okay, reboot of PC didn't help, but i was cleared `temp` folder and it's helped, strange
