### ISSUE TITLE
[Bug] free(): invalid pointer

### ISSUE THREAD

**Issue by Othmane-ElAlami** [LSPosed/MagiskOnWSALocal#259]
### Steps to reproduce/复现步骤

1. Use Debian WSL on Windows 11
2. Install all the pre-requirements
3. Clone and run the script ./run.sh
4. Choose default options

### Expected behaviour/预期行为

Not getting any error.

### Actual behaviour/实际行为

Get ERROR 

```bash
COMMAND_LINE=--arch free(): invalid pointer
x64 --release-type  --magisk-ver free(): invalid pointer
stable --gapps-brand free(): invalid pointer
MindTheGapps --gapps-variant pico  --root-sol free(): invalid pointer
magisk --compress    --compress-format free(): invalid pointer
7z
ERROR: Invalid Architecture: free(): invalid pointer
x64
```

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

2d90b1cc58ad69b8ecb0f9ed43a76958aafdda74

### Linux distribution info/Linux 发行版信息

PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION="2022.4"
VERSION_ID="2022.4"
VERSION_CODENAME="kali-rolling"
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"

### Windows version/Windows 版本

11 22H2 (64-bit) 22621.819

### Build Parameters/构建参数

I used default value, didn't change anything. Just pressed OK on every step, I also tried other parameters same error.

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>
<summary>Details</summary>

</details>

**Comment by s1204IT** [comment]
It's the `libpopt0` issue.
Translate the next page into your country language to check the version of `libpopt0`.
https://github.com/openyellowos/help-hw/issues/1

**Comment by Howard20181** [comment]
@Othmane-ElAlami What the output of `echo $BASH_VERSION` ?

**Comment by Othmane-ElAlami** [comment]
> It's the `libpopt0` issue.
Yes, thanks! Downgrading to 1.18 fixed the issue.

> What the output of `echo $BASH_VERSION` ?
5.2.2(1)-release
