### ISSUE TITLE
:warning: Since OpenGapps doesn't officially support Android 12.1 yet, lock the variant to pico!

### ISSUE THREAD

**Issue by janat08** [LSPosed/MagiskOnWSALocal#26]
:warning: Since OpenGapps doesn't officially support Android 12.1 yet, lock the variant to pico!

**Comment by janat08** [comment]
It then doesn't work. This shows up during output build.

**Comment by Howard20181** [comment]
As the warning message says, this is by design.

**Comment by janat08** [comment]
Meaning instead of full, the pico variant is installed without play store? I installing this for local banking app and I wouldn't find it outside play store.

**Comment by janat08** [comment]
I'd rather use an older android.

**Comment by Howard20181** [comment]
pico includes Play Store

**Comment by janat08** [comment]
https://github.com/opengapps/opengapps/wiki/Pico-Package
But indeed after updates play store seems to have been installed.
