### ISSUE TITLE
[Feature Request] MicroG apps

### ISSUE THREAD

**Issue by fillwithjoy1** [LSPosed/MagiskOnWSALocal#261]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Problem is, I prefer microG over mind-the-gapps

### Describe the solution you'd like/描述你想要的解决方案

Offer MicroG as a gapps solution available

### Additional context/其他信息

https://microg.org/

**Comment by fillwithjoy1** [comment]
I will note that it is possible to install microG manually, but it would be nice for it to be already setup

**Comment by Howard20181** [comment]
#33 

MicroG does not have complete GApps components
It means that you need to patch after installing OpenGapps or MindTheGapps
