### ISSUE TITLE
[Bug] Sampling Rate for microphone is stuck at 8000Hz

### ISSUE THREAD

**Issue by aleksstevcic** [LSPosed/MagiskOnWSALocal#265]
### Steps to reproduce/复现步骤

No steps to reproduce. This seems to be the default behaviour for WSA.

Editing sampling rates under
-vendor/etc/audio_policy_configuration.xml
-vendor/etc/primary_audio_policy_configuration.xml
both seem to adjust the sampling rates for audio output, but all microphone input still is very low quality (as if it is at 8000Hz).

See files.zip for the two edited files, taken directly from my live WSA instance.

### Expected behaviour/预期行为

Input sample rate should be at whatever I decide to set it to under those files.

### Actual behaviour/实际行为

Audio input sample rate stays at 8000Hz.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

78a408de0ce9d576323cd9c8e9c8e8d72b59cc2d

### Linux distribution info/Linux 发行版信息

Ubuntu 20.04.5 LTS

### Windows version/Windows 版本

Windows 11 22H2 / 22623.891

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk     --compress-format
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [x] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>
<summary>Details</summary>

[files.zip](https://github.com/LSPosed/MagiskOnWSALocal/files/10095802/files.zip)

</details>

**Comment by Howard20181** [comment]
Report to Microsoft https://github.com/microsoft/WSA/issues
