### ISSUE TITLE
[Bug] The build isn't the latest version.

### ISSUE THREAD

**Issue by xvzhenduo** [LSPosed/MagiskOnWSALocal#267]
### Steps to reproduce/复现步骤

1. run `./build.sh --release-type WIF`

### Expected behaviour/预期行为

It will download and build the latest version of insider fast.

### Actual behaviour/实际行为

It download the version `2210.40000.7.0` but not the latest version `2209.40000.28.0`
The actrual download link`http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/15af34f3-b0f6-42bb-9e95-19888b0c545c?P1=1669834971&P2=404&P3=2&P4=XGrnCrnHk7UkcnOd12PKoYEfDW3XyNezNJ6G7dpUFaAMbaDzirqYiTTGbqRwBsCEdCsTReaeZSgH3bEMxNcxDA%3d%3d`
![image](https://user-images.githubusercontent.com/74353173/204784221-cb86dd0f-880e-49bc-b8a9-7a0c1b5c1942.png)
![image](https://user-images.githubusercontent.com/74353173/204784369-724e42d3-e8a0-4f86-936e-acbf56bc2113.png)

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

78a408d

### Linux distribution info/Linux 发行版信息

WSL ubuntu
5.15.74.2-microsoft-standard-WSL2 #1 SMP Wed Nov 2 19:50:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Windows version/Windows 版本

25236.1010

### Build Parameters/构建参数

INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: stable
INFO: GApps Brand: OpenGApps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Insider Fast

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/74353173/204781771-d943cffe-4666-4f41-a8a4-4772b95dd416.png)

</details>

**Comment by xvzhenduo** [comment]
为什么吧issue关了？

**Comment by Howard20181** [comment]
你自己指定通道为WIF然后网页通道选RP然后问为什么不一样

**Comment by xvzhenduo** [comment]
抱歉啊😂
