### ISSUE TITLE
[Bug] wsa-retail and wsa related files fail to download

### ISSUE THREAD

**Issue by mriamnobody** [LSPosed/MagiskOnWSALocal#273]
### Steps to reproduce/复现步骤

1. Run ./build.sh command with no arguments.

### Expected behaviour/预期行为

File download shall complete without any issues.

### Actual behaviour/实际行为

Getting error "[SocketCore.cc:507] errorCode=1 Failed to connect to the host 2402:6800:764:a000::1, cause: Network is unreachable" for Wsa-retail.zip and wsa related files. I have attached the screenshot of error with this issue. And most annoying this is slow download speed for wsa-retail.zip. I have 300 Mbps download speed and when I download it from "https://store.rg-adguard.net/" it only takes me a few minutes to completely download all wsa files (including wsa.msixbundle file)

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

78a408d

### Linux distribution info/Linux 发行版信息

Ubuntu-22.04

### Windows version/Windows 版本

Windows 11 22622.590, Windows feature Experience pack: 1000.22634.1000.0

### Build Parameters/构建参数

./build.sh command with no arguments.

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

[aria2_download.log](https://github.com/LSPosed/MagiskOnWSALocal/files/10148204/aria2_download.log)
![Screenshot (1982)](https://user-images.githubusercontent.com/14347205/205484050-2141b819-296f-4a9e-8990-c01fdbd1f9e9.png)

**Comment by Howard20181** [comment]
Does your network support IPv6? Try disabling it. This issue comes from Microsoft's servers and there is nothing we can do about it.

**Comment by mriamnobody** [comment]
Can we use "https://store.rg-adguard.net/" to download ```wsa``` related files? There is no download speed issue when I use "https://store.rg-adguard.net/" to download ```wsa``` related files plus the downloads on "https://store.rg-adguard.net/" are hosted by Microsoft servers.

**Comment by Howard20181** [comment]
No, a long time ago we got the download link from that site, which was much more unstable, so we implemented our own link generation.

**Comment by mriamnobody** [comment]
More unstable in what sense? I mean, was the download speed unstable or the files from "https://store.rg-adguard.net/" resulted in crashes after building?

**Comment by mriamnobody** [comment]
I'm writing a script to get the files from "https://store.rg-adguard.net/" and will only finalize it after your input.

**Comment by mriamnobody** [comment]
I just checked my network adapter settings and my modem settings. IPv6 is disabled in both of them.

**Comment by Howard20181** [comment]
That site uses cloudflare protection, sometimes can not bypass
Our own implementation of link generation and site generation is no different

**Comment by mriamnobody** [comment]
> That site uses cloudflare protection, sometimes can not bypass
> Our own implementation of link generation and site generation is no different

Is this the reason behind the instability?

**Comment by Howard20181** [comment]
Why are you still receiving IPv6 DNS results and trying to connect to it after disabling IPv6? Please check the WSL configuration or report the problem to Microsoft.

**Comment by mriamnobody** [comment]
Alright, let me check ```wsl``` network settings.

**Comment by mriamnobody** [comment]
The IPv6 was enabled in WSL, and I have now disabled it. Now the downloading of wsl related files are not failing, but there is also no improvement in the download speed. I'm getting around 10-15 Kb download speed.
