### ISSUE TITLE
[Feature Request] WSA即将升级至Android13

### ISSUE THREAD

**Issue by Sunrongguo2008** [LSPosed/MagiskOnWSALocal#282]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

无

### Describe the solution you'd like/描述你想要的解决方案

我只是想说：
WSA在一周内将升级至Android13，请做好准备。如果现在的项目与Android13有兼容性问题，希望提前修改，防患于未然。
注：Android13的WSA版本是2211.40000.7.0或更高，希望对你有帮助。
最后，祝愿MagiskOnWSALocal项目越来越好！

**Comment by Howard20181** [comment]
已经提前适配

**Comment by sundakai** [comment]
> 已经提前适配

麻烦问下是还不支持下载 13 的版本吗，我拉了最新 master 的代码，清空了 download ，选择dev版本的wsa，下载的 wsa 版本是 2210.40000.7.0

**Comment by Howard20181** [comment]
目前通过API直接获取的最新版是2210
微软可能限制了只有内测用户的账号才能获取2211

**Comment by sundakai** [comment]
> 

好的感谢解答

**Comment by sundakai** [comment]
> 目前通过API直接获取的最新版是2210 微软可能限制了只有内测用户的账号才能获取2211

好的感谢解答

**Comment by Sunrongguo2008** [comment]
> 目前通过API直接获取的最新版是2210 微软可能限制了只有内测用户的账号才能获取2211

确实是这样
