### ISSUE TITLE
Docker内的Ubuntu运行脚本需要权限（privileged mode无效）

### ISSUE THREAD

**Issue by Zaphkito** [LSPosed/MagiskOnWSALocal#29]
![7Z(T77S})8 C~I`NV`P~52V](https://user-images.githubusercontent.com/64299266/185909425-82d2418b-6228-4167-aa78-1dcbf60af45f.png)
不懂就问，是不是这部分操作你们的脚本前面忘了加sudo

**Comment by Howard20181** [comment]
已经加了
你是什么环境？会不会不允许sudo或者mount

**Comment by Zaphkito** [comment]
> 

docker内的Ubuntu，直接sudo运行脚本也不能编译，我还是正儿八经弄个Ubuntu得了

**Comment by Howard20181** [comment]
你可以搜索一下docker privileged mode

**Comment by Zaphkito** [comment]
![image](https://user-images.githubusercontent.com/64299266/185914157-e40db2ff-c588-4bd6-bb04-b7bf704adc6d.png)
privileged mode也试过了有个不太一样的报错
另外这玩意多少有点危险还是别让一般人用这个了，似乎能直接危害宿主机

**Comment by Howard20181** [comment]
不用privileged mode不能mount, sudo也是假的，没办法

**Comment by Zaphkito** [comment]
直接用正儿八经的Ubuntu或者wsl2得了，docker方案直接放弃比较好
