### ISSUE TITLE
[Feature Request] Fall back to tsinghua mirror on magisk download failure.

### ISSUE THREAD

**Issue by sqhills** [LSPosed/MagiskOnWSALocal#305]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Sometimes script fails to retrieve magisk release from github.

### Describe the solution you'd like/描述你想要的解决方案

Add fallback to tsinghua mirror when using stable magisk.

### Additional context/其他信息

Tsinghua magisk mirror: https://mirrors.tuna.tsinghua.edu.cn/github-release/topjohnwu/Magisk/LatestRelease/
thx for the great job btw👍

**Comment by Howard20181** [comment]
Seems like there is no a easy way to get the link.
And the mirror only has the stable version, not a great choices to add it to the fallback.

**Comment by sqhills** [comment]
I see. I will use offline mode for now.
