### ISSUE TITLE
[Feature Request] 支持无wine运行

### ISSUE THREAD

**Issue by qwerty472123** [LSPosed/MagiskOnWSALocal#306]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

无

### Describe the solution you'd like/描述你想要的解决方案

WSL下shell脚本可直接运行exe程序而无需安装wine。

鉴于目前推荐使用本地wsl而非github actions，希望支持build.sh在没有安装wine的环境下运行。

```shell
if [ ! -f /proc/sys/fs/binfmt_misc/WSLInterop ] || which wine64 > /dev/null; then
	# run makepri by wine
else
	# run makepri on windows
fi
```

### Additional context/其他信息

无

**Comment by Howard20181** [comment]
如果不需要WSA设置界面多语言支持（仅英文）可以注释掉合并语言资源部分就可以不用wine了

**Comment by qwerty472123** [comment]
> 如果不需要WSA设置界面多语言支持（仅英文）可以注释掉合并语言资源部分就可以不用wine了

我知道，事实上建议用makepri的issue是我提的...

而WSL上直接运行 makepri.exe 也不需要wine，希望能够支持这种方式。

**Comment by Howard20181** [comment]
你可以PR，我要到下个工作日才有空

**Comment by zanhecht** [comment]
I commented on the pull request, but the checks for wine and winetricks would also need to be removed from `run.sh`.
