### ISSUE TITLE
关于临时数据即“/tmp”的一个建议

### ISSUE THREAD

**Issue by Zaphkito** [LSPosed/MagiskOnWSALocal#31]
首先说明该问题在Ubuntu中并不存在，仅仅是我尝试其他Linux编译时遇到的问题
经过替换软件包的方式我成功在Arch Linux编译了MagiskOnWSA且经过测试在Windows中运行正常
https://github.com/Zaphkito/MagiskOnWSAArchLocal

但是在编译过程中，我发现由于系统默认分配的"/tmp"空间太小(我是archinstall官方脚本安装非手敲)，所以会导致出现空间不足的报错，临时解决方案是重定向或直接更改这些临时数据的存放位置，编译完成后删除临时目录，或者直接扩容tmp也是一种选择，但是较为过程复杂

既然你们能直接删除临时使用的download文件夹，那为什么不也在源码根目录临时借用一些地方存放临时数据？
只是建议，毕竟项目主要给Ubuntu用而不是给Arch使用，如果实际使用中有不合理的地方希望指出
![image](https://user-images.githubusercontent.com/64299266/186029095-e833e8f8-5679-481c-9589-3d76e4ccfbe3.png)
![LG9~ZZAG5TQ~R4JKTP}Y~2G](https://user-images.githubusercontent.com/64299266/186029447-05cee23e-bc8d-4f4e-910d-e2c221d92a98.jpg)
![UI`PFFC`(T%(6A F875W_1](https://user-images.githubusercontent.com/64299266/186029122-af95bcbc-8019-4357-b576-d146d4cd6627.png)

**Comment by Howard20181** [comment]
因为/tmp在WSL上是在内存里，不用存到硬盘上就会比较快，解压什么的都飞速
之前临时目录也是和Download目录同级的
Download文件夹留下是为了不用重复下载（当然要更新还是要删掉重下）

**Comment by Zaphkito** [comment]
> 因为/tmp在WSL上是在内存里，不用存到硬盘上就会比较快，解压什么的都飞速 之前临时目录也是和Download目录同级的 Download文件夹留下是为了不用重复下载（当然要更新还是要删掉重下）

那有考虑优化这方面的问题吗，还是保持现状

**Comment by Howard20181** [comment]
/tmp在内存上不知道是WSL还是Ubuntu的魔法，如果没有通用性还是改回去比较好
没办法在下载完所有东西再保证/tmp有足够的空间
或者加个开关？

**Comment by Zaphkito** [comment]
> /tmp在内存上不知道是WSL还是Ubuntu的魔法，如果没有通用性还是改回去比较好 没办法在下载完所有东西再保证/tmp有足够的空间 或者加个开关？

我都行，你做主（

**Comment by Howard20181** [comment]
加了一条注释，去掉注释就变成用源码根目录，方便切换
默认还是用的 `/tmp`
