### ISSUE TITLE
$MAGISK_VER for the downloadGapps.py function

### ISSUE THREAD

**Issue by Renda80** [LSPosed/MagiskOnWSALocal#32]
https://github.com/LSPosed/MagiskOnWSALocal/blob/f2b05674dc499b9d20b7d7c8edea970edc0e91f7/scripts/run.sh#L175
Is it really okay? $MAGISK_VER Shouldn't it be more like $GAPPS_VARIANT?

**Comment by Howard20181** [comment]
WTF? 
It was a stupid mistake.
