### ISSUE TITLE
[Feature Request] Windows server support 有办法支持Windows server 吗

### ISSUE THREAD

**Issue by gyhmz** [LSPosed/MagiskOnWSALocal#324]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

![image](https://user-images.githubusercontent.com/95202722/210218941-3cd0b826-d321-45b0-bba3-6354c4c18a7e.png)

### Describe the solution you'd like/描述你想要的解决方案

Doesn't work in Windows server. Windows server 不能用

**Comment by Howard20181** [comment]
去[这里](https://github.com/cinit/WSAPatch)问
