### ISSUE TITLE
[Bug] No android 13 when selecting insider preview version

### ISSUE THREAD

**Issue by TRINCETT** [LSPosed/MagiskOnWSALocal#325]
### Steps to reproduce/复现步骤

1.  Open the windows subsystem for linux
2. run the script
3. Select insider preview version

### Expected behaviour/预期行为

I expected that selecting the insider preview version in the script would download the latest version

### Actual behaviour/实际行为

When I run the script and select the insider preview version, it doesn't download the latest version (2211.40000.7.0)

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

--

### Linux distribution info/Linux 发行版信息

WSL Ubuntu 22.04.1

### Windows version/Windows 版本

22621.963

### Build Parameters/构建参数

x64 
insider preview
Magisk stable
No keep amazon store

### Version requirement/版本要求

- [x] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>
<summary>Details</summary>

</details>

**Comment by someone5678** [comment]
This is not a bug. Microsoft grant A13 preview build per User Account, not Release Ring...
I recommend you to read this thread
https://github.com/LSPosed/MagiskOnWSALocal/discussions/298
