### ISSUE TITLE
Option to Install Microg instead of google play services in Gapps.

### ISSUE THREAD

**Issue by foco76** [LSPosed/MagiskOnWSALocal#33]
Can you please add an option to install Microg instead of google play services in Gapps,Thank you!

**Comment by Howard20181** [comment]
Now the installation of OpenGapps and MindtheGapps is implemented, but it was found that MindtheGapps does not work properly, which wastes a lot of time, if someone wants to support MicroG then feel free to submit a Pull Request.

**Comment by fillwithjoy1** [comment]
What about now? Or is there an option to try and build for microG?
(PS. Using magisk for MicroG installer revived doesn't work either 👎)
