### ISSUE TITLE
[Bug] Magisk and Google play

### ISSUE THREAD

**Issue by vojtanethio** [LSPosed/MagiskOnWSALocal#331]
### Steps to reproduce/复现步骤

Previously I had installed WSA without problems everything was running Magisk and Google play without issues.

1. I was trying to do an update and I deleted all files from the folder where I have installed WSA (C:\WSA).
2. I pasted newly created files to the folder and tried every method from point 10 in Text Guide
3. It shows me just two windows of Windows Subsystem for Android. It runs for a while and then it closes itself
4. Magisk and Google play in not installed just Windows Subsystem for Android

 

### Expected behaviour/预期行为

Install Magisk and Google play/Gapps
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/99132302/211164676-e2b9328a-b35c-4d48-8540-08346392a3c2.png">

### Actual behaviour/实际行为

two windows of Windows Subsystem for Android opens
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/99132302/211164618-1618278b-a93a-4f03-94f0-14ee0b25dd32.png">

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

--

### Linux distribution info/Linux 发行版信息

Ubuntu

### Windows version/Windows 版本

10.0.22621 Build 22621

### Build Parameters/构建参数

WSA-with-magisk-stable-MindTheGapps_2210.40000.7.0_x64_Release-Nightly

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

[debug.txt](https://github.com/LSPosed/MagiskOnWSALocal/files/10367020/debug.txt)

**Comment by Howard20181** [comment]
Please update scripts.
