### ISSUE TITLE
[Feature Request] Support Magisk Delta

### ISSUE THREAD

**Issue by akhil-rana** [LSPosed/MagiskOnWSALocal#332]
### Is your feature request related to a problem? 
Yes

Currently magisk fails to pass safety net on x86 and emulators.

### Describe the solution you'd like

An additional option to choose for "[Magisk Delta](https://github.com/HuskyDG/magisk-files/tree/main)" as root installation, as it seems to have passed the safety net on most emulators.

**Comment by s1204IT** [comment]
https://github.com/s1204IT/MagiskOnWSALocal/tree/magisk-delta
I've adding it but I don't know how to passing SafetyNet.

https://forum.xda-developers.com/t/4460555/
Is this XDA forum helpful?

**Comment by akhil-rana** [comment]
> https://github.com/s1204IT/MagiskOnWSALocal/tree/magisk-delta I've adding it but I don't know how to passing SafetyNet.
> 
> https://forum.xda-developers.com/t/4460555/ Is this XDA forum helpful?

Magisk hide is built in in delta in the settings. Just like old magisk.

**Comment by Howard20181** [comment]
https://github.com/LSPosed/MagiskOnWSALocal/discussions/216#discussioncomment-3947684
