### ISSUE TITLE
[Bug] VPN Dialog not working on Android 13

### ISSUE THREAD

**Issue by AndersonCV** [LSPosed/MagiskOnWSALocal#339]
### Steps to reproduce/复现步骤

1. Open any VPN app
2. Try to connect using VPN Dialog
3. App crashes

### Expected behaviour/预期行为

VPN Dialog doesn't work

### Actual behaviour/实际行为

VPN Apps crashes on latest WSA Android 13 Update (2211.40000.11.0)

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

f9a8b78ed59abfa7c1055576552c25b75d8cb3ed

### Linux distribution info/Linux 发行版信息

WSL with Ubuntu

### Windows version/Windows 版本

25272.1000

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIF --magisk-ver canary --gapps-brand MindTheGapps --gapps-variant pico  --root-sol magisk     --compress-format
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: canary
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Insider Fast

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

Here the logs of "Speedtest by Ookla" app. Other VPN apps just crash when you try to open them, like VPNHub.
[VPN_SpeedTest.txt]
(https://github.com/LSPosed/MagiskOnWSALocal/files/10386578/VPN_log.txt)

**Comment by s1204IT** [comment]
Are you possible to verify with the WSA original APK?

**Comment by Howard20181** [comment]
Install this update
https://github.com/LSPosed/VpnDialogs/actions/runs/3893849959

**Comment by mstouk57g** [comment]
> Install this update https://github.com/LSPosed/VpnDialogs/actions/runs/3893849959 This is just a workaround The root cause is not yet determined

![image](https://user-images.githubusercontent.com/65524880/215305439-ef3bbfb8-1fd6-4d6e-9ac5-378d3cd4a7db.png)


Existing package com.android.vpndialogs signatures do not match newer version

**Comment by s1204IT** [comment]
Please replace directly from the system image file.

**Comment by luis-arch** [comment]
请问您可以讲清楚怎么替换系统的vpndiags吗。本人尝试过adb root 以及在内部shell获取root都无法卸载Vpndiags。没法实现替换。

------------------------------------------------------------------------------------------

**Comment by luis-arch** [comment]
——————————————————————————-

**Comment by luis-arch** [comment]
请问您可以讲清楚怎么替换系统的vpndiags吗。本人尝试过adb root 以及在内部shell获取root都无法卸载Vpndiags。没法实现替换。

-----------------------------------------------------------------------------------------------

Can you tell me how to replace vpndiags in the system? I tried adb root and getting root in the internal shell, but I couldn't uninstall Vpndiags. Unable to achieve replacement.

**Comment by s1204IT** [comment]
> 请问您可以讲清楚怎么替换系统的vpndiags吗。本人尝试过adb root 以及在内部shell获取root都无法卸载Vpndiags。没法实现替换。
> 
> Can you tell me how to replace vpndiags in the system? I tried adb root and getting root in the internal shell, but I couldn't uninstall Vpndiags. Unable to achieve replacement.

https://github.com/s1204IT/MagiskOnWSALocal/tree/3997b2a
Try it.

APK signature is `testkey`.

**Comment by mstouk57g** [comment]
> > 请问您可以讲清楚怎么替换系统的vpndiags吗。本人尝试过adb root 以及在内部shell获取root都无法卸载Vpndiags。没法实现替换。
> > Can you tell me how to replace vpndiags in the system? I tried adb root and getting root in the internal shell, but I couldn't uninstall Vpndiags. Unable to achieve replacement.
> 
> https://github.com/s1204IT/MagiskOnWSALocal/tree/3997b2a Try it.
> 
> APK signature is `testkey`.

Build a new one?
构建一个新的？

**Comment by mstouk57g** [comment]
> Please replace directly from the system image file.

怎么弄啊，能不能教教

**Comment by s1204IT** [comment]
> > > 请问您可以讲清楚怎么替换系统的vpndiags吗。本人尝试过adb root 以及在内部shell获取root都无法卸载Vpndiags。没法实现替换。
> > > Can you tell me how to replace vpndiags in the system? I tried adb root and getting root in the internal shell, but I couldn't uninstall Vpndiags. Unable to achieve replacement.
> > 
> > 
> > https://github.com/s1204IT/MagiskOnWSALocal/tree/3997b2a Try it.
> > APK signature is `testkey`.
> 
> Build a new one? 构建一个新的？

Rebuild from [my repository](https://github.com/s1204IT/MagiskOnWSALocal).

**Comment by mstouk57g** [comment]
> > > > 请问您可以讲清楚怎么替换系统的vpndiags吗。本人尝试过adb root 以及在内部shell获取root都无法卸载Vpndiags。没法实现替换。
> > > > Can you tell me how to replace vpndiags in the system? I tried adb root and getting root in the internal shell, but I couldn't uninstall Vpndiags. Unable to achieve replacement.
> > > 
> > > 
> > > https://github.com/s1204IT/MagiskOnWSALocal/tree/3997b2a Try it.
> > > APK signature is `testkey`.
> > 
> > 
> > Build a new one? 构建一个新的？
> 
> Rebuild from [my repository](https://github.com/s1204IT/MagiskOnWSALocal).

![image](https://user-images.githubusercontent.com/65524880/216480187-2d6f9df8-01e9-44a5-b8fe-830db134db51.png)
感谢，在重新构建后成功连接Google
Thanks.I have solved my porblem.

**Comment by LLP2333** [comment]
### 也可以通过adb设置代理
#### 前提
一、把WSA这个网络关了
![image](https://user-images.githubusercontent.com/61670545/216752584-f254348c-dd00-4cb2-87ef-cd307c05bdf3.png)
二、clash代理打开，端口为7890，并且Allow Lan
![image](https://user-images.githubusercontent.com/61670545/216752630-f525eb20-2efd-4d07-89b3-91a1fc16102b.png)


#### 第一步使用ipconfig查看windows的网络信息
![image](https://user-images.githubusercontent.com/61670545/216752115-fa904fec-344c-41d3-a26c-a5169f40901e.png)
我这里的ip为172.22.96.1
#### 然后执行
```bash
adb connect 127.0.0.1:58526
```
![image](https://user-images.githubusercontent.com/61670545/216752227-fb6d4099-a470-47bb-bab9-b8daaa76573f.png)
#### 根据前面查看的windows的ip，(我的电脑的clash端口为7890)
执行
```bash
adb shell settings put global http_proxy  ip:端口
```
![image](https://user-images.githubusercontent.com/61670545/216752361-b7f6212e-c8c4-4d61-8d23-50c61fa9e5bb.png)
然后就能代理WSA
![image](https://user-images.githubusercontent.com/61670545/216752436-af2a0be3-6f88-410c-b5e1-7f0179fe50ec.png)
#### 如果想取消clash代理
执行
```bash
adb shell settings put global http_proxy  :0
```

**Comment by sforman2861597** [comment]
还有一个方法，就是在子系统里安装诸如 AppOps 这样的权限管理应用，然后将相关软件的“激活 vpn”权限改为允许。
![屏幕截图_20230207_113147](https://user-images.githubusercontent.com/121373973/217141527-691664db-b8ec-4d5b-a322-9056b703a8d5.png)


实测可以直接开启vpn

**Comment by Howard20181** [comment]
Status: Wontfix

Microsoft set https://developer.android.com/reference/android/os/UserManager#DISALLOW_CONFIG_VPN to restrict configure of VPN

**Comment by Howard20181** [comment]
Found a way to bypass restriction
Testing

**Comment by s1204IT** [comment]
> Found a way to bypass restriction
> Testing

It may present a solution for Japan's restricted devices.
Thanks!

**Comment by Howard20181** [comment]
I'm not sure if this is a vulnerability and why the policy is not checked further but continues to allow VPN setup.
https://github.com/LSPosed/VpnDialogs/commit/db3740428524a5ba001daf76d28e10796ecce35c
