### ISSUE TITLE
WSA Release Type and Magisk Release Version always set to retail and stable

### ISSUE THREAD

**Issue by someone5678** [LSPosed/MagiskOnWSALocal#34]
![image](https://user-images.githubusercontent.com/59456192/186216122-3f787242-2013-4adf-b536-71ea413cf75b.png)

![image](https://user-images.githubusercontent.com/59456192/186216942-ce615956-2272-420e-b77e-a3a7355128b6.png)

I tried several times of build and all the build have Retail WSA variant with Stable Magisk release

Build env: On WSL Ubuntu 20.10
Selected WSA Variant: Insider Fast
Selected Magisk Relase: Debug

Result: Retail WSA with Stable Magisk

**Comment by m-jishnu** [comment]
> ![image](https://user-images.githubusercontent.com/59456192/186216122-3f787242-2013-4adf-b536-71ea413cf75b.png)
> 
> ![image](https://user-images.githubusercontent.com/59456192/186216942-ce615956-2272-420e-b77e-a3a7355128b6.png)
> 
> I tried several times of build and all the build have Retail WSA variant with Stable Magisk release
> 
> Build env: On WSL Ubuntu 20.10 Selected WSA Variant: Insider Fast Selected Magisk Relase: Debug
> 
> Result: Retail WSA with Stable Magisk

use space key to select the version type during the running of run.sh

**Comment by Howard20181** [comment]
In order to build without duplicate downloads, the download folder will not be cleared automatically, delete the download folder manually and try again.
