### ISSUE TITLE
[Bug] The WSA settings and splash screen are in English only.

### ISSUE THREAD

**Issue by meiruitesi** [LSPosed/MagiskOnWSALocal#342]
### Steps to reproduce/复现步骤

正常运行install.ps1安装

### Expected behaviour/预期行为

显示为Windows的语言，例如简体中文

### Actual behaviour/实际行为

只会显示为英文，但是安卓应用会显示为Windows的语言

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

f9a8b78ed59abfa7c1055576552c25b75d8cb3ed

### Linux distribution info/Linux 发行版信息

WSL with Ubuntu 22.04.1 LTS

### Windows version/Windows 版本

10.0.22621.963

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIF --magisk-ver canary --gapps-brand MindTheGapps --gapps-variant pico  --root-sol magisk --compress    --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: canary
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Insider Fast

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

![image](https://user-images.githubusercontent.com/84609642/211742378-9206df25-b4e6-4240-9198-c1fa5f7401a5.png)
![image](https://user-images.githubusercontent.com/84609642/211742574-829ddd7e-61b2-47c5-8144-c337b36bf35e.png)
![image](https://user-images.githubusercontent.com/84609642/211742798-24bdfcec-c2cc-4f97-b21a-523612da7e7f.png)

**Comment by Howard20181** [comment]
无法复现
是不是和#335 一样

试试在WSL内执行`wslpath -w ~`
显示什么？

**Comment by meiruitesi** [comment]
> 无法复现 是不是和#335 一样
> 
> 试试在WSL内执行`wslpath -w ~` 显示什么？

![image](https://user-images.githubusercontent.com/84609642/211746122-48051959-2056-453b-836a-3437ef569a9d.png)

**Comment by Howard20181** [comment]
这个路径直接粘贴在Windows的资源管理器里面能访问吗？

**Comment by meiruitesi** [comment]
> 这个路径直接粘贴在Windows的资源管理器里面能访问吗？

能
![image](https://user-images.githubusercontent.com/84609642/211746764-ccea5685-6e89-4339-85a2-52b0d0a52d00.png)

**Comment by Howard20181** [comment]
合并过程中有报错吗？
正常的是这样的
![image](https://user-images.githubusercontent.com/40033067/211747129-028cd61f-9ec9-4f24-9e4d-6385ae52c521.png)

**Comment by meiruitesi** [comment]
Merge Language Resources
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resources targetOsVersion="10.0.0" majorVersion="1">
<index root="\" startIndexAt="\">
    <indexer-config type="folder" foldernameAsQualifier="true" filenameAsQualifier="true" qualifierDelimiter="."/>
    <indexer-config type="PRI"/>
</index>
</resources>
Microsoft (R) MakePRI Tool
Copyright (C) 2013 Microsoft. All rights reserved.

ERROR: PRI180: 0x80070057 - Target \\wsl.localhost\Ubuntu-22.04\tmp\wsa-build-onA6Svkj8n_\wsa\pri does not exist
ERROR: PRI193: 0x80070057 - Please provide a valid Project Root

Usage:
------
    MakePri.exe new /pr <project root> /cf <config file> [options]

Example:
--------
    MakePri.exe new /pr C:\MyApp\src\ /cf C:\MyApp\priconfig.xml /mn
    C:\MyApp\AppXManifest.xml /of C:\MyApp\src\resources.pri /o

Description:
------------
    Creates a PRI file at [outputfile] by indexing all files in the
    [projectroot]and its subdirectories as directed by the [configxml]. The
    index will be assigned [indexname] to reference resources in the application

Required Parameters:
--------------------
    /ProjectRoot(pr)  : <FOLDERPATH> Root location of project files
    /ConfigXml(cf)    : <FILEPATH> Configuration file location. Use
                        'Makepri.exe createconfig' command to generate one

Options:
--------
    /OutputFile(of)   : <FILEPATH> Output location of PRI file, default is
                        [current directory]\resources.pri
    /Manifest(mn)     : <FILEPATH> Location of the application or component's
                        manifest. This parameter is ignored if [indexname]
                        is given. Default is [projectroot]\AppXManifest.xml
    /IndexName(in)    : <STRING> Name for the generated index of resources.
                        Typically matches the AppX package name, class library
                        simple name, etc. May be supplied via the
                        [manifest] parameter.
                        If IndexName is not specified and an AppX manifest
                        file is not present, the default name 'Application'
                        will be used.
    /VersionMajor(vma): <INTEGER> [Deprecated] Major version number for
                        index, default is 1
    /IndexLog(il)     : <FILEPATH> XML Log of indexed resources, no file
                        generated by default
    /AutoMerge(am)    : This flag is not recommended for normal use with AppX
                        packages. It causes Makepri.exe to set the auto
                        merge flag within the PRI file. Default is not set.
    /ReverseMap(rm)   : Generate a reverse mapping section in the PRI file
                        which can be used for debugging purposes.
    /MappingFile(mf)  : <MAPPINGFILETYPE> Generate a mapping file in the given
                        file format.
    /SchemaFile(sf)   : <FILEPATH> Output location of XML resource schema
                        description.
    /IndexOptions(io) : <OPTIONS> Options to provide detailed control over
                        behavior of resource indexers.
    /Overwrite(o)     : Overwrite an existing output file of the same name
                        without prompting
    /Verbose(v)       : Causes verbose messages to be output to the console
    /Help(h, ?)       : Display the usage help text
    /ExtensionDll(ex) : <FILEPATH> Location of the MRT environment extension
                        DLL. This DLL must be signed by a Microsoft-issued
                        certificate. Default is an empty path (no DLL
                        will be used).


    FOLDERPATH       - is a valid path to a folder
    FILEPATH         - is a path to a file, either relative to the current
                       directory or absolute
    MAPPINGFILETYPE  - Supported File type(s): 'AppX'

Merge Language Resources done

**Comment by meiruitesi** [comment]
![image](https://user-images.githubusercontent.com/84609642/211753793-9a555ae6-55da-4f58-bebe-d13885e0243a.png)

**Comment by qwerty472123** [comment]
> > 无法复现 是不是和#335 一样
> > 试试在WSL内执行`wslpath -w ~` 显示什么？
> 
> ![image](https://user-images.githubusercontent.com/84609642/211746122-48051959-2056-453b-836a-3437ef569a9d.png)

截图提示你可能是zsh用户。

而目前build.sh依赖这样的行为：执行命令 `echo "$(echo \\\\)"` 得到的输出为 `\\` 而非 `\`。

我在Ubuntu20.04与22.04上测试均发现只有bash存在这样的行为，zsh或dash均输出 `\`。

建议确认build.sh是否由符合上述行为的shell执行。

我也期待有sh大佬能提供各种shell下均ok的代码QAQ。

**Comment by Howard20181** [comment]
已经强制只能bash运行了
不知道会不会被绕过

**Comment by qwerty472123** [comment]
> 已经强制只能bash运行了 不知道会不会被绕过

或许他们的bash版本与Ubuntu20.04与22.04上默认提供的行为不同，谁知道呢QAQ

**Comment by Howard20181** [comment]
其实上面的
```
ERROR: PRI180: 0x80070057 - Target \wsl.localhost\Ubuntu-22.04\tmp\wsa-build-onA6Svkj8n_\wsa\pri does not exist
```
是两个`\\`的，由于上面直接粘贴过来没有加` ``` ``` `标记为代码块导致Markdown解析结果只有一个`\`，我点编辑看原始内容是两个

**Comment by Howard20181** [comment]
> 其实上面的
> 
> ```
> ERROR: PRI180: 0x80070057 - Target \wsl.localhost\Ubuntu-22.04\tmp\wsa-build-onA6Svkj8n_\wsa\pri does not exist
> ```
> 
> 是两个`\\`的，由于上面直接粘贴过来没有加`` ``` ``` ``标记为代码块导致Markdown解析结果只有一个`\`，我点编辑看原始内容是两个

#335 那边的也是两个，所以建议发日志就括起来，Markdown解析过之后很容易看错

**Comment by qwerty472123** [comment]
> > 其实上面的
> > ```
> > ERROR: PRI180: 0x80070057 - Target \wsl.localhost\Ubuntu-22.04\tmp\wsa-build-onA6Svkj8n_\wsa\pri does not exist
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 是两个`\\`的，由于上面直接粘贴过来没有加`` ``` ``` ``标记为代码块导致Markdown解析结果只有一个`\`，我点编辑看原始内容是两个
> 
> #335 那边的也是两个，所以建议发日志就括起来，Markdown解析过之后很容易看错

这样啊，那我就不知道原因了QAQ

**Comment by faerfa** [comment]
一样的问题
Merge Language Resources
Microsoft (R) MakePRI Tool
Copyright (C) 2013 Microsoft. All rights reserved.

ERROR: PRI180: 0x80070057 - Target \\wsl.localhost\Ubuntu\tmp\wsa-build-gdhDT4JnJ1_\wsa\pri does not exist
ERROR: PRI193: 0x80070057 - Please provide a valid Project Root

**Comment by MustardChef** [comment]
I was also having the same problem on the Ubuntu WSL distro, but after switching to Debian WSL distro it seems to work without any problems.
This is one fix if you cannot get rid of the "MakePRI" error
