### ISSUE TITLE
[Bug] Mount images failed.

### ISSUE THREAD

**Issue by sakurasep** [LSPosed/MagiskOnWSALocal#346]
### Steps to reproduce/复现步骤

1. 运行Windows10的WSL Ubuntu22.04
2. 在Ubuntu中执行./run.sh，在最后Mount images这一步出现问题

### Expected behaviour/预期行为

这是我在VMware16中的Ubuntu22.04以同样方法执行所得到的结果
![image](https://user-images.githubusercontent.com/70024132/212013214-00f8825d-762c-4573-b446-0ca9fd9a7887.png)

### Actual behaviour/实际行为

![image](https://user-images.githubusercontent.com/70024132/212013364-05821e9c-61f2-4363-a719-9fc26df5baa5.png)

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

dc7083c

### Linux distribution info/Linux 发行版信息

WSL with Ubuntu 22.04 LTS

### Windows version/Windows 版本

10.0.19045.2486

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand none --gapps-variant pico --remove-amazon --root-sol magisk --compress    --compress-format zip
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: none
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: zip
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/70024132/212014480-1631520d-b503-4f29-80f0-5002b59cbf4c.png)

</details>

**Comment by Howard20181** [comment]
WSL2还是1?
WSL1不行

**Comment by sakurasep** [comment]
WSL1，ok我去试试WSL2
