### ISSUE TITLE
[Bug] Cannot start WSAClient.exe

### ISSUE THREAD

**Issue by Ztumpie905509** [LSPosed/MagiskOnWSALocal#349]
### Steps to reproduce/复现步骤

Follows the installation steps, and waits for it to complete.

### Expected behaviour/预期行为

After installation, Google Play Store and Magisk should be launched.

### Actual behaviour/实际行为

![image](https://user-images.githubusercontent.com/48085506/212144006-f3b659a5-71d1-4078-aaab-87fe2783a43b.png)
Gives out an error, and the "Starting Windows Subsystem for Android" screen is stuck forever.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

dc7083ccface4eac389bbeff4b3aad049116c888

### Linux distribution info/Linux 发行版信息

![image](https://user-images.githubusercontent.com/48085506/212144504-b3ae5c5d-249e-4fa5-a8c2-264452cdfd36.png)

### Windows version/Windows 版本

10.0.22621.1105

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand OpenGApps --gapps-variant pico  --root-sol none     --compress-format
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: OpenGApps
INFO: GApps Variant: pico
INFO: Root Solution: none

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

![image](https://user-images.githubusercontent.com/48085506/212144006-f3b659a5-71d1-4078-aaab-87fe2783a43b.png)
It gives out an error, and the "Starting Windows Subsystem for Android" screen is stuck forever.

I have already tried reinstalling WSA, Regedit, sfc and DISM method, and none of the above fixed the issue

**Comment by Yexilei** [comment]
Me too
