### ISSUE TITLE
[Bug] After running Run.bat, all app shortcuts are gone, but app still installed.

### ISSUE THREAD

**Issue by superluig164** [LSPosed/MagiskOnWSALocal#353]
### Steps to reproduce/复现步骤

Ran Run.bat in application folder.
Look in Start for application icons, they are gone.  However, if you go into dev options, and the RAM viewer, you can see apps are installed and even launch them, but shortcuts don't show up in WSA settings or Start.

### Expected behaviour/预期行为

Shortcuts should reappear after Run.bat reinstalls WSA.

### Actual behaviour/实际行为

Shortcuts are gone.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

I'm not sure how to check this.

### Linux distribution info/Linux 发行版信息

WSL2, Ubuntu.

### Windows version/Windows 版本

Win 11 22H2 (22621.1105)

### Build Parameters/构建参数

Not sure how to check this.

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

No logs to submit?  WSA launches.

**Comment by superluig164** [comment]
Update, any apps updated through the Play Store reappeared in WSA and Start Menu.  It seems that reinitializes them somehow.

**Comment by Howard20181** [comment]
Where did you put the WSA system files (the folder with system.img)? It needs to stay the same as it was before the update.

**Comment by superluig164** [comment]
I didn't move anything, although, when first installing I didn't keep it inside the folder with the scripts.  As far as I understand you can use Run.bat to reinstall if there were issues?  I'm not sure if it even performed an update or just reinstalled the same version, but either way it didn't work right.
