### ISSUE TITLE
[Bug] Installation fails with Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF6, Package could not be registered

### ISSUE THREAD

**Issue by dreamflasher** [LSPosed/MagiskOnWSALocal#361]
### Steps to reproduce/复现步骤

1. Successfully build MagiskOnWSALocal
2. Start powershell with admin rights
3. Navigate to output folder
4. PowerShell.exe -ExecutionPolicy Bypass -File .\Install.ps1

### Expected behaviour/预期行为

Succesful installation of WSA with Magisk

### Actual behaviour/实际行为

```Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF6, Package could not be registered

In E:\Software\MagiskOnWSALocal\output\WSA_2210.40000.7.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-OpenGApps-
11.0-pico\Install.ps1:102 Character:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion
```

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

9854c62

### Linux distribution info/Linux 发行版信息

WSL 2

### Windows version/Windows 版本

11

### Build Parameters/构建参数

WSA_2210.40000.7.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-OpenGApps-11.0-pico

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

```Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF6, Package could not be registered

In E:\Software\MagiskOnWSALocal\output\WSA_2210.40000.7.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-OpenGApps-
11.0-pico\Install.ps1:102 Character:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion
```
</details>

**Comment by Howard20181** [comment]
Please move to a shorter path.
