### ISSUE TITLE
[Feature Request] The possibility of a new feature to select and merge language packs manually or semi-automatically.

### ISSUE THREAD

**Issue by ZL-ZedeL** [LSPosed/MagiskOnWSALocal#364]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

#342 #335 
这两个问题均出现在合并语言包失败上,且本人的错误与操作环境等与#342保持一致(即WSA界面显示为英文)

### Describe the solution you'd like/描述你想要的解决方案

我这边目前只能定位问题范围在\\\wsl.localhost\Ubuntu\home\USERNAME\MagiskOnWSALocal-main\wine\x86_64的makepri.exe与目录的问题上(这里的路径为了防止markdown渲染多加了一个反斜杠),而不清楚该如何解决.所以我在想,是否可以支持单独的选择语言包进行合并的步骤,或者干脆不合并,逐次使用语言包的功能/选项.这样,也许这个问题就能被绕过.
希望您能考虑我的请求或提议,如果能提供回复会更好,谢谢了.

**Comment by Howard20181** [comment]
不能选
要解决很容易，就是一律使用wine，传路径给Windows这边执行始终还是不稳定
