### ISSUE TITLE
无法下载magisk.zip，一直在尝试

### ISSUE THREAD

**Issue by callng** [LSPosed/MagiskOnWSALocal#38]
ARCH=x64
RELEASE_TYPE=retail
MAGISK_VER=stable
GAPPS_VARIANT=
REMOVE_AMAZON=remove
ROOT_SOL=magisk
COMPRESS_OUTPUT=yes
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail
Generating Magisk download link: release type=stable
download link: https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@25.2/app-release.apk
./scripts/run.sh: 第 180 行： [: !=：需要一元表达式
Download Artifacts

08/25 16:36:03 [NOTICE] Downloading 2 item(s)

08/25 16:36:04 [NOTICE] CUID#7 - Redirecting to https://download.microsoft.com/download/4/7/c/47c6134b-d61f-4024-83bd-b9c9ea951c25/appx/Microsoft.VCLibs.x64.14.00.Desktop.appx

08/25 16:36:04 [NOTICE] GID#dc5bb57834d062cb - 下载已完成：/www/wwwroot/wsa/download/vclibs.appx

08/25 16:36:04 [NOTICE] 下载已完成：/www/wwwroot/wsa/download/vclibs.appx

08/25 16:36:04 [NOTICE] CUID#8 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk
 *** Download Progress Summary as of Thu Aug 25 16:37:03 2022 ***                                                                       
========================================================================================================================================
[#19ae89 0B/0B CN:1 DL:0B]
FILE: /www/wwwroot/wsa/download/magisk.zip
----------------------------------------------------------------------------------------------------------------------------------------

[#19ae89 0B/0B CN:1 DL:0B]                                                                                                              
08/25 16:37:05 [NOTICE] CUID#8 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk
 *** Download Progress Summary as of Thu Aug 25 16:38:04 2022 ***                                                                       
========================================================================================================================================
[#19ae89 0B/0B CN:1 DL:0B]
FILE: /www/wwwroot/wsa/download/magisk.zip
----------------------------------------------------------------------------------------------------------------------------------------

[#19ae89 0B/0B CN:1 DL:0B]                                                                                                              
08/25 16:38:06 [NOTICE] CUID#8 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk
 *** Download Progress Summary as of Thu Aug 25 16:39:04 2022 ***                                                                       
========================================================================================================================================
[#19ae89 0B/0B CN:1 DL:0B]
FILE: /www/wwwroot/wsa/download/magisk.zip
----------------------------------------------------------------------------------------------------------------------------------------

[#19ae89 0B/0B CN:1 DL:0B]                                                                                                              
08/25 16:39:08 [NOTICE] CUID#8 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk
 *** Download Progress Summary as of Thu Aug 25 16:40:05 2022 ***                                                                       
========================================================================================================================================
[#19ae89 0B/0B CN:1 DL:0B]
FILE: /www/wwwroot/wsa/download/magisk.zip
----------------------------------------------------------------------------------------------------------------------------------------

[#19ae89 0B/0B CN:1 DL:0B]                                                                                                              
08/25 16:40:09 [NOTICE] CUID#8 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk
 *** Download Progress Summary as of Thu Aug 25 16:41:05 2022 ***                                                                       
========================================================================================================================================
[#19ae89 0B/0B CN:1 DL:0B]
FILE: /www/wwwroot/wsa/download/magisk.zip
----------------------------------------------------------------------------------------------------------------------------------------

[#19ae89 0B/0B CN:1 DL:0B]                                                                                                              
08/25 16:41:11 [NOTICE] CUID#8 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk
 *** Download Progress Summary as of Thu Aug 25 16:42:05 2022 ***                                                                       
========================================================================================================================================
[#19ae89 0B/0B CN:1 DL:0B]
FILE: /www/wwwroot/wsa/download/magisk.zip
----------------------------------------------------------------------------------------------------------------------------------------

[#19ae89 0B/0B CN:1 DL:0B]                                                                                                              
08/25 16:42:16 [NOTICE] CUID#8 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk
[#19ae89 0B/0B CN:1 DL:0B]                                                                                                              
08/25 16:42:24 [NOTICE] 正在关闭程序…再次按 Ctrl-C 可强制关闭程序。

08/25 16:42:24 [NOTICE] GID 为 19ae89aa331741c3 的下载项未完成：/www/wwwroot/wsa/download/magisk.zip

下载结果：
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
dc5bb5|OK  |       0B/s|/www/wwwroot/wsa/download/vclibs.appx
19ae89|INPR|       0B/s|/www/wwwroot/wsa/download/magisk.zip

状态标识：
(OK): 下载完成。(INPR): 正在下载。

传输重启后 aria2 可继续该下载。
如见任何错误，详查日志文件。详细信息见帮助或手册页面中的“-l”选项。
An error has occurred, exit
Cleanup Work Directory
Cleanup Download Directory
[root@ubuntu-virtual-machine:/www/wwwroot/wsa#

**Comment by lava114514** [comment]
请问问题解决了吗？我也遇到相同问题

**Comment by Howard20181** [comment]
不是bug
请检查网络
