### ISSUE TITLE
[Feature Request] WSA 2301 has been released, but the build is still an old version

### ISSUE THREAD

**Issue by EricFengFuuuu** [LSPosed/MagiskOnWSALocal#385]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

WSA 2301 has been released, but the build is still an old version

### Describe the solution you'd like/描述你想要的解决方案

Hope to build the latest version of WSA

**Comment by 7gxycn08** [comment]
You need to `git clone https://github.com/LSPosed/MagiskOnWSALocal` a fresh copy it worked for me.

**Comment by EricFengFuuuu** [comment]
Yes, I cloned the code and built it locally, but I still got the old version.

**Comment by 7gxycn08** [comment]
> Yes, I cloned the code and built it locally, but I still got the old version.

I got 2301.40000.4.0

When you build select Release Preview Channel don't choose Stable.
