### ISSUE TITLE
[Bug]  A Prerequisite for an install could not be satisfied.

### ISSUE THREAD

**Issue by axcairns** [LSPosed/MagiskOnWSALocal#386]
### Steps to reproduce/复现步骤

1. Build installer with all defaults
2. Execute Run.bat

### Expected behaviour/预期行为

Should install WSA

### Actual behaviour/实际行为

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

b0e94d2ea36921a0a0d58f7199a619b212fe6f89

### Linux distribution info/Linux 发行版信息

Under WSL2 - 

allan@study:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 22.04 LTS
Release: 22.04
Codename: jammy

### Windows version/Windows 版本

Windows 10 22H2 build 19045.2546

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --root-sol magisk --compress --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail
WSA Version=2211.40000.11.0

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

```
Installing MagiskOnWSA...
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.
Windows cannot install package MicrosoftCorporationII.WindowsSubsystemForAndroid_2211.40000.11.0_x64__8wekyb3d8bbwe     because this package is not compatible with the device. The package requires OS version 10.0.22000.120 or higher on     the Windows.Desktop device family. The device is currently running OS version 10.0.19045.2546.                          NOTE: For additional information, look for [ActivityId] e17f3dd3-3dda-0002-6164-80e1da3dd901 in the Event Log or use    the command line Get-AppPackageLog -ActivityID e17f3dd3-3dda-0002-6164-80e1da3dd901
At \\wsl.localhost\Ubuntu-22.04\home\allan\MagiskOnWSALocal\output\WSA_2211.40000.11.0_x64_Release-Nightly-with-magisk-
25.2(25200)-stable-MindTheGapps-13.0\Install.ps1:102 char:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (\\wsl.localhost...ppxManifest.xml:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

All Done!
Press any key to exit```
</details>

**Comment by Howard20181** [comment]
Not a bug
WSA only can install in Windows 11
