### ISSUE TITLE
[Feature Request] Support building on windows.

### ISSUE THREAD

**Issue by androidacy-user** [LSPosed/MagiskOnWSALocal#387]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Current, we must use Linux or WSL to build WSA, then transfer that to the Windows install. This can be rather cumbersome. 

### Describe the solution you'd like/描述你想要的解决方案

The ability to build natively on windows, using the appropriate tools. 

### Additional context/其他信息

The simple requirement of installation of Linux through one method or another is a deterrent to many users. Allowing to build on windows would be a huge boon.

**Comment by vvb2060** [comment]
> There are several third party tools to do it.

PR welcome

**Comment by yujincheng08** [comment]
@androidacy-user notice that we still not found any tools to do so since existing tools simpily ignore xattr.
