### ISSUE TITLE
[Feature Request] Support Windows 10

### ISSUE THREAD

**Issue by YT-Advanced** [LSPosed/MagiskOnWSALocal#389]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

In github, we have a patch to enable WSA run on Windows 10. Here is the reporistory: https://github.com/cinit/WSAPatch

### Describe the solution you'd like/描述你想要的解决方案

On install file, add some code to check the Windows version, then if the Windows version is 10, the file will auto copy and paste modifided file to WSA and run it

**Comment by MustardChef** [comment]
> @MustardChef I have create the ones have support both Windows 10 x64 and Windows 11 x64. Can you check for me before I send a pull request ? Download link: [CLICK HERE](https://github.com/YT-Advanced/WSA-Magisk/suites/11042178954/artifacts/560959741)

Seems to be working

**Comment by MustardChef** [comment]
Also I would recommend having the script download the latest WSAPatch dlls

**Comment by MustardChef** [comment]
> @MustardChef I think you can add to your WSABuild repos a Custom Build option that can be help user to build they own  :D

Yes, that seems like a great idea. I will experiment with the Github Actions Workflow and add it to the repo

**Comment by Howard20181** [comment]
> yes, so I think let user to use compiled package in release is better

https://github.com/LSPosed/MagiskOnWSALocal/issues/4#issuecomment-1376508507

**Comment by CarlGao4** [comment]
> In my opinion, don't provide Actions-based builds if you don't want the repository to be disabled. Even if you export to Releases it will still be disabled.

@Howard20181 Please read your email (How***@outlook.com). I have something related to this to discuss with you.

**Comment by MichaelPei2003** [comment]
I managed to run wsa on windows10 but it somehow can't use GPU and has extremely poor 3D performance xD
