### ISSUE TITLE
Recommendation: add "offline mode" for download directory.

### ISSUE THREAD

**Issue by Renda80** [LSPosed/MagiskOnWSALocal#39]
hi, if I understand correctly, the files downloaded to the "download" directory will be deleted after the "output" directory is created. For WSA builds, they download again, even if the version of the downloaded files has not changed.

You can add "offline mode" where downloads are kept in the "downloads" directory and WSA is repeatedly created from them.

It might come in handy if a user needs to build different WSA variants (with/without GApps) like me. I solved the commenting of the code in "run.sh" according to my needs.

**Comment by Howard20181** [comment]
The logic now is that a normal build will not delete the contents of the Downloads folder.

**Comment by Renda80** [comment]
Apologies in advance for reopening this thread.
I understand that the already downloaded files in the "download" directory are now being used for building WSA. Unfortunately, the script in question still requires internet connectivity, otherwise it will end up with an error. I understand why this is so and for what reasons. It would be good to be able to build WSA even without an Internet connection, when all the necessary files are already available in the "download" directory and all system tools are up-to-date, resepktively there is no need to verify them again.

**Comment by Howard20181** [comment]
Offline mode is implemented.
