### ISSUE TITLE
[Bug] WSA doesn't open

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [LSPosed/MagiskOnWSALocal#394]
### Steps to reproduce/复现步骤

1. Open any app
2. The loading screen goes on forever

### Expected behaviour/预期行为

WSA should start and apps should load.

### Actual behaviour/实际行为

WSA doesn't finish loading and is listed at a ridiculously low size (~100 KB) at the installed apps list.

This happens even after reinstalling and it seems it happens to me too even with the official release. No Windows update nor change in configuration since last successful loading. It just doesn't want to work.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

b0e94d2ea36921a0a0d58f7199a619b212fe6f89

### Linux distribution info/Linux 发行版信息

WSL2 Ubuntu

### Windows version/Windows 版本

Windows 11 Pro 22H2 22621.1265 Windows Feature Experience Pack 1000.22638.1000.0

### Build Parameters/构建参数

COMMAND-LINE=--arch x64 --release-type=retail --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --root-sol magisk
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

![image](https://user-images.githubusercontent.com/36646277/221406403-ff89a300-a808-4930-a321-501c09b97fa5.png)

</details>

**Comment by Howard20181** [comment]
Try wipe data (delete userdata.vhdx) and renistall.

**Comment by l-l-l-l-l-l** [comment]
I deleted userdata.vhdx, ran the script again and reinstalled the new build and still the ame issue.

I checked the event viewer and the only weird thing I found are a whole lot of warnings telling me that each individual R/W operation WSL did took over 10 seconds.

**Comment by MustardChef** [comment]
Weirdly enough, I have been having the same issue and no matter what I do, it seems to persist.

**Comment by MARIELLAMARIELLA28** [comment]
IL BUILD WSA NON SI APRE

**Comment by YT-Advanced** [comment]
hmm, I think we should test patch via [WSAPackagingTool](https://github.com/WSA-Community/WSAPackagingTool)

**Comment by Howard20181** [comment]
This doesn't look like a problem we can fix
It should be reported to Microsoft
