### ISSUE TITLE
[Bug] Nbc Sports and NBC Apps Can't be Installed

### ISSUE THREAD

**Issue by Timbo303** [LSPosed/MagiskOnWSALocal#398]
### Steps to reproduce/复现步骤

1. Try Downloading Nbc Sports or NBC App from Play Store or even manually

### Expected behaviour/预期行为

Should be installed.

### Actual behaviour/实际行为

Gives an Error when trying to install. 
INSTALL_FAILED_MISSING_SHARED_LIBRARY: Reconciliation failed...: Reconcile failed: Package air.com.nbcuni.com.nbcsports.liveextra requires unavailable shared library com.amazon.device.messaging; failing!

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

https://github.com/creative-builds/WSA-Magisk

### Linux distribution info/Linux 发行版信息

Linux Mint 22.04 (wasn't really used since I already found prebuilt version)

### Windows version/Windows 版本

11

### Build Parameters/构建参数

I used this github repo but it was likely built with this repo because for some reason it wouldn't install when I tried to build it with linux mint since I dual boot. Pretty sure it has to be ubuntu itself. Your more of an expert when it comes to magiskonwsa: https://github.com/creative-builds/WSA-Magisk

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

![Screenshot (2)](https://user-images.githubusercontent.com/28489517/222777405-4b06b50e-7333-41d3-9b2a-7017db1d4bd5.png)

**Comment by Howard20181** [comment]
Try install a build did not remove amazon.
