### ISSUE TITLE
[Feature Request] Symlink BusyBox

### ISSUE THREAD

**Issue by YT-Advanced** [LSPosed/MagiskOnWSALocal#402]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No

### Describe the solution you'd like/描述你想要的解决方案

As you can see, we have busybox at /system/sbin/ but I want to call it via ADB as a symlink Can you add it to shell script. Thanks
![image](https://user-images.githubusercontent.com/70064328/223675679-d0055576-5636-42aa-81e9-e60ef6492aba.png)

**Comment by yujincheng08** [comment]
`ASH_STANDALONE=1 /path/to/busybox/sh`
