### ISSUE TITLE
[Bug] no google play store in apps.

### ISSUE THREAD

**Issue by AminAhmadyDeveloper** [LSPosed/MagiskOnWSALocal#407]
### Steps to reproduce/复现步骤

1. cloned the repo
2. build the WSA with X64-86 | magisk | mind the gapps | no amazon store delete.
3. installed the WSA

### Expected behaviour/预期行为

as in description I should see play store in my apps.

### Actual behaviour/实际行为

it seems like I only have Google app, means there is no play store or any other google apps.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

8d795a6bc31bc300233ed24604a1a008c384cc26

### Linux distribution info/Linux 发行版信息

"Ubuntu" named distribution installed from WSL2. on windows 11.

### Windows version/Windows 版本

Windows 11 Pro - 22H2 - 22623.1325

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --root-sol magisk
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

```
there is no logs or images i can provide
```
</details>

**Comment by Howard20181** [comment]
Unable to reproduce
