### ISSUE TITLE
Change properties ro.secure to 0 and ro.debuggable to 1

### ISSUE THREAD

**Issue by l-l-l-l-l-l** [LSPosed/MagiskOnWSALocal#409]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

I need to use adb in root mode, but the way things are configured through this script only allow adb to access the supersuser account in shell mode. Given that the command I need to use is not a shell command, I need to change ro.secure to 0 and ro.debuggable to 1, but even as superuser in shell, those two as fñagged as "read only", so I need  to change the properties directly in the default.prop file.

### Describe the solution you'd like/描述你想要的解决方案

For now, I'd like a tutorial on how to manually change that, but in the future it would be interesting if a new option was added in the run and build scripts to change it from the start.

**Comment by Howard20181** [comment]
[adb_root.zip](https://github.com/LSPosed/MagiskOnWSALocal/files/10955493/adb_root.zip)
