### ISSUE TITLE
[Feature Request] Support .msixbundle output file

### ISSUE THREAD

**Issue by YT-Advanced** [LSPosed/MagiskOnWSALocal#410]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

As you can see in the Additional context below, @WSA-Community have provided a tool to pack, unpack WSA msixbundle, so how about if you add it to the script. Thanks!

### Describe the solution you'd like/描述你想要的解决方案

First, mannual download and patch Magisk MindTheGapps etc. Then the script use the tool below to repack instead of use 7zip or zip.

### Additional context/其他信息

https://github.com/WSA-Community/WSAPackagingTool

**Comment by Howard20181** [comment]
Didn't see any advantages. If we want to share now we can compress to 7z for a smaller size. If you don't need to share just for your own use, the unpacked files installed in developer mode are easier to modify.

**Comment by YT-Advanced** [comment]
> Didn't see any advantages. If we want to share now we can compress to 7z for a smaller size. If you don't need to share just for your own use, the unpacked files installed in developer mode are easier to modify.

Yes, I known but if we pack .msix, we don't need to turn on developer mode (that can maybe risk for our device) and of course we just need a click to the file then click install. More easier than ever

**Comment by Howard20181** [comment]
But installing a packaged msix package that uses the repository you pointed out still requires enabling developer mode.
And you also need to use the installation script it provides for automatically enabling developer mode.

**Comment by Howard20181** [comment]
In summary, there is no advantage over what we have.
The packaged one is more inconvenient to modify.

**Comment by YT-Advanced** [comment]
Oh thanks for your advice, I will close this issues
