### ISSUE TITLE
[Bug] VHDX version

### ISSUE THREAD

**Issue by Titi66200** [LSPosed/MagiskOnWSALocal#417]
### Steps to reproduce/复现步骤

Expand images done

Mount images
mount: /tmp/wsa-build-TDUahpe3dX_/system: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
Build: an error has occurred, exit

### Expected behaviour/预期行为

Expand images done

Mount images
mount: /tmp/wsa-build-TDUahpe3dX_/system: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
Build: an error has occurred, exit

### Actual behaviour/实际行为

Expand images done

Mount images
mount: /tmp/wsa-build-TDUahpe3dX_/system: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
Build: an error has occurred, exit

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

latest

### Linux distribution info/Linux 发行版信息

20

### Windows version/Windows 版本

11

### Build Parameters/构建参数

none

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

```
Expand images done

Mount images
mount: /tmp/wsa-build-TDUahpe3dX_/system: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
Build: an error has occurred, exit
```
</details>

**Comment by Howard20181** [comment]
#414
