### ISSUE TITLE
[Bug] Resize error

### ISSUE THREAD

**Issue by Titi66200** [LSPosed/MagiskOnWSALocal#419]
### Steps to reproduce/复现步骤

 none

### Expected behaviour/预期行为

resize system.img to 1992991
resize2fs 1.45.5 (07-Jan-2020)
resize2fs: New size smaller than minimum (252205)

### Actual behaviour/实际行为

resize system.img to 1992991
resize2fs 1.45.5 (07-Jan-2020)
resize2fs: New size smaller than minimum (252205)

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

latest

### Linux distribution info/Linux 发行版信息

20.04

### Windows version/Windows 版本

11

### Build Parameters/构建参数

None

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

```
resize system.img to 1992991
resize2fs 1.45.5 (07-Jan-2020)
resize2fs: New size smaller than minimum (252205)
```
</details>

**Comment by Howard20181** [comment]
Not enough information
