### ISSUE TITLE
Error while building latest insider beta version

### ISSUE THREAD

**Issue by nisarg-ujjainkar** [LSPosed/MagiskOnWSALocal#420]
### Steps to reproduce/复现步骤

1. ./build.sh --release-type WIS --remove-amazon
2. 
3. 

### Expected behaviour/预期行为

Expect it to build the WSA package

### Actual behaviour/实际行为

Build bails with the following error:

Expand images
e2fsck: No such file or directory while trying to open /tmp/wsa-build-mkOWb31HLe_/wsa/x64/system_ext.img
Possibly non-existent device?
Build: an error has occurred, exit

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

58d25e995901c3c0d0daf40635953c2df0b6e087

### Linux distribution info/Linux 发行版信息

Ubuntu 22.04

### Windows version/Windows 版本

11

### Build Parameters/构建参数

COMMAND_LINE: --release-type WIS --remove-amazon
INFO: Architecture: x64
INFO: Release Type: WIS
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Insider Slow
Generate Download Links
Generating WSA download link: arch=x64 release_type=Insider Slow
WSA Version=2302.40000.6.0

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

Expand images
e2fsck: No such file or directory while trying to open /tmp/wsa-build-mkOWb31HLe_/wsa/x64/system_ext.img
Possibly non-existent device?
Build: an error has occurred, exit

**Comment by nisarg-ujjainkar** [comment]
Please note that retail and RP builds run just fine.

**Comment by Howard20181** [comment]
#414
