### ISSUE TITLE
[Bug] Merge pri not working

### ISSUE THREAD

**Issue by Titi66200** [LSPosed/MagiskOnWSALocal#424]
### Steps to reproduce/复现步骤

1. 
2. 
3. 

### Expected behaviour/预期行为

Merge pri not working

### Actual behaviour/实际行为

Merge pri not working

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

latest

### Linux distribution info/Linux 发行版信息

20.04

### Windows version/Windows 版本

11

### Build Parameters/构建参数

None

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

```
# Replace this line with the log / 将此行用日志替换
```
</details>

**Comment by homo11451419** [comment]
连hash都没有，咋过的
啥问题
说清楚

**Comment by homo11451419** [comment]
看看这个？#421

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/MagiskOnWSALocal/commit/ec58edfd47c96f4de68e30a82d4cc9f8e3e62a12
