### ISSUE TITLE
Unable to install a Magisk module interactively 

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [LSPosed/MagiskOnWSALocal#43]
I don't know how to install a Magisk module that requires volume buttons keys.

**Comment by Howard20181** [comment]
key_volume_up: `adb shell input keyevent 24`
key_volume_down: `adb shell input keyevent 25`

**Comment by MohammedMehdiTBER** [comment]
> key_volume_up: `adb shell input keyevent 24` key_volume_down: `adb shell input keyevent 25`

didn't work
