### ISSUE TITLE
[Bug] Start Process parameter is incorrect

### ISSUE THREAD

**Issue by KyleStilkey** [LSPosed/MagiskOnWSALocal#433]
### Steps to reproduce/复现步骤

1. Create a Build
2. Try to install
3. Get the error.

### Expected behaviour/预期行为

Should install without issues.

### Actual behaviour/实际行为

Errors out and fails to install.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

8e3eef3

### Linux distribution info/Linux 发行版信息

Ubuntu (Windows Store)

### Windows version/Windows 版本

10.0.22621 Build 22621

### Build Parameters/构建参数

--release-type RP --magisk-ver stable --gapps-brand MindTheGapps --root-sol magisk --compress-format 7z

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

![image](https://user-images.githubusercontent.com/6766223/226506119-9f822466-bb98-425a-a243-1df83fc37c4c.png)

Start-Process : This command cannot be run due to the error: The parameter is incorrect.
At C:\WSA\Install.ps1:52 char:5
Start-Process : This command cannot be run due to the error: The parameter is incorrect.
At C:\WSA\Install.ps1:53 char:5
+     Start-Process "wsa://com.android.vending"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

**Comment by KyleStilkey** [comment]
> that error wont appear if you build with gapps on it and that error doesnt affect functionality wsa can still launch

Not sure what you mean because it doesn't install WSA at all and before the changes were made to how this builds and installs I've not had issues and now I can't install it now.

**Comment by Howard20181** [comment]
Reboot Windows and run the installer again.
