### ISSUE TITLE
[BUG] ./build.sh: line 125: e2fsck: command not found

### ISSUE THREAD

**Issue by pranjal32** [LSPosed/MagiskOnWSALocal#440]
In continuation to: https://github.com/LSPosed/MagiskOnWSALocal/issues/437#issue-1637450460 (Reopened)

The user @Howard20181 suggested to run install_deps.sh and closed the issue.
I have already tried that and it this is the output of `./install_deps.sh`:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
e2fsprogs is already the newest version (1.46.2-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20210119).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
No new packages are updated or installed and it says e2fsprogs is already the newest version (1.46.2-2).

Still, the script has the same error as referenced on top.

**Comment by Howard20181** [comment]
It is not clear which distribution you are using, usually `e2fsck`b is included in `e2fsprogs`, please install the dependencies yourself.
