### ISSUE TITLE
[Bug] doesn't complete WSA install stops after an error occurs (''requests''module not found)

### ISSUE THREAD

**Issue by MHMae001** [LSPosed/MagiskOnWSALocal#446]
### Steps to reproduce/复现步骤

1. Clone repo according to (2) in Text Guide
2. run.sh --arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --root-sol magisk --compress-format

### Expected behaviour/预期行为

WSA folder should be available in output folder

### Actual behaviour/实际行为

do not see an output folder
here's the list of folders i see

~/MagiskOnWSALocal$ ls -R
.:
LICENSE arm64 bin docs installer linker scripts x64 xml

./arm64:
gapps system

./arm64/gapps:
product

./arm64/gapps/product:
overlay

./arm64/gapps/product/overlay:
GoogleWebViewOverlay.apk

./arm64/system:
priv-app

./arm64/system/priv-app:
VpnDialogs

./arm64/system/priv-app/VpnDialogs:
VpnDialogs.apk

./bin:
arm64 x64

./bin/arm64:
makepri.exe

./bin/x64:
makepri.exe

./docs:
Custom-GApps.md KernelSU.md README.md

./installer:
Install.ps1 MakePri.ps1 Run.bat

./linker:
aarch64 x86_64

./linker/aarch64:
libc.so libdl.so libm.so linker64

./linker/x86_64:
libc.so libdl.so libm.so linker64

./scripts:
build.sh fixGappsProp.py generateMagiskLink.py install_deps.sh
extractMagisk.py generateGappsLink.py generateWSALinks.py requirements.txt
extractWSA.py generateKernelSULink.py getWSAMainVersion.py run.sh

./x64:
gapps system

./x64/gapps:
product

./x64/gapps/product:
overlay

./x64/gapps/product/overlay:
GoogleWebViewOverlay.apk

./x64/system:
priv-app

./x64/system/priv-app:
VpnDialogs

./x64/system/priv-app/VpnDialogs:
VpnDialogs.apk

./xml:
FE3FileUrl.xml GetCookie.xml WUIDRequest.xml priconfig.xml

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

58e17da60af06fc948c21593d6ca210a6465649c

### Linux distribution info/Linux 发行版信息

Ubuntu 22.04.2 LTS

### Windows version/Windows 版本

22h2 Build 22621.1413 Windows Feature Experience Pack 1000.22639.1000.0

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --root-sol magisk --compress-format
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Generate Download Links
Traceback (most recent call last):
  File "/home/USER/MagiskOnWSALocal/scripts/generateWSALinks.py", line 31, in <module>
    from requests import Session
ModuleNotFoundError: No module named 'requests'
Build: an error has occurred, exit

Cleanup Work Directory
```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
Run `scripts/install_deps.sh`
