### ISSUE TITLE
stuck on PowerShell.exe -ExecutionPolicy Bypass -File .\Install.ps1

### ISSUE THREAD

**Issue by berkovich98** [LSPosed/MagiskOnWSALocal#45]
![image](https://user-images.githubusercontent.com/54507029/186911988-bc777636-c391-4503-875e-b721a20f49dc.png)
i did uninstall the previous verion of wsa did everything according to the this video https://www.youtube.com/watch?v=Hap1csblx50 and it stuck on the image. Any work arounds for this? (popup windows disappear without asking administrative permission when i run install.ps1 with power shell)

**Comment by Howard20181** [comment]
Which account are you using?
Don't use the account named `Administrator`.
Create a new administrator account and try again.

**Comment by s1204IT** [comment]
> Don't use the account named Administrator.

There is no problem even if the user name is `Administrator`.
That's me now.
However, it's good to create a new admin account.
