### ISSUE TITLE
[Bug] 下载APK阶段没有走环境变量配置的代理

### ISSUE THREAD

**Issue by miyouzi** [LSPosed/MagiskOnWSALocal#455]
### Steps to reproduce/复现步骤

1. 在WSL中配置 $HTTPS_PROXY $HTTP_PROXY 环境变量代理
2. 执行 ./scripts/run.sh
3. 在APK 下载阶段卡住

![image](https://user-images.githubusercontent.com/24269465/227751815-ffcf21ae-cc53-45d1-a3ba-3d73f652605c.png)

### Expected behaviour/预期行为

顺利下载 Github 上的资源

### Actual behaviour/实际行为

在Github资源下载阶段卡住

```bash
03/26 10:21:25 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk
[#564471 0B/0B CN:1 DL:0B]
```

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

2e02381b9addf70044e5464fab3c58dd308d584b

### Linux distribution info/Linux 发行版信息

Ubuntu-20.04 （WSL2）

### Windows version/Windows 版本

10.0.19045.2788

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIF --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk --compress    --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Insider Fast

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

![image](https://user-images.githubusercontent.com/24269465/227751962-ef84858c-01c2-4da4-a9e3-d1bc068cc679.png)
```
03/26 10:10:29 [NOTICE] CUID#11 - Redirecting to https://nchc.dl.sourceforge.net/project/wsa-mtg/x86_64/20230323/MindTheGapps-13.0.0-x86_64-20230323.zip
[DL:0B][#8ab2ba 0B/0B][#564471 0B/0B][#1a0e87 0B/0B]
03/26 10:10:29 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:29 [NOTICE] GID#8ab2ba477eb3f21c - Download has already completed: /mnt/d/InstallerPackages/wsa/MagiskOnWSALocal/download/Microsoft.VCLibs.x64.14.00.Desktop.appx

03/26 10:10:29 [NOTICE] Download complete: /mnt/d/InstallerPackages/wsa/MagiskOnWSALocal/download/Microsoft.VCLibs.x64.14.00.Desktop.appx

03/26 10:10:29 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:29 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:29 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:30 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk
[DL:0B][#564471 0B/0B][#1a0e87 0B/0B]
03/26 10:10:30 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:30 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:30 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:30 [NOTICE] GID#1a0e87dc4be05a22 - Download has already completed: /mnt/d/InstallerPackages/wsa/MagiskOnWSALocal/download/MindTheGapps-x64-13.0.zip

03/26 10:10:30 [NOTICE] Download complete: /mnt/d/InstallerPackages/wsa/MagiskOnWSALocal/download/MindTheGapps-x64-13.0.zip

03/26 10:10:30 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:31 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk
[#564471 0B/0B CN:1 DL:0B]
03/26 10:10:31 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:31 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:31 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:31 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:31 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:32 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk
[#564471 0B/0B CN:1 DL:0B]
03/26 10:10:32 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk

03/26 10:10:32 [NOTICE] CUID#10 - Redirecting to https://raw.githubusercontent.com/topjohnwu/magisk-files/25.2/app-release.apk
```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
我测试是会使用代理的
用这个脚本设置吧https://gist.github.com/Howard20181/31e61599ecb069483448c03649810c75
windows.local 无法解析
![image](https://user-images.githubusercontent.com/40033067/227752323-daa16042-5774-4452-a0ca-29f184d424da.png)

**Comment by miyouzi** [comment]
> 我测试是会使用代理的 用这个脚本设置吧https://gist.github.com/Howard20181/31e61599ecb069483448c03649810c75 windows.local 无法解析 ![image](https://user-images.githubusercontent.com/40033067/227752323-daa16042-5774-4452-a0ca-29f184d424da.png)

因为 `windows.local` 是我自己配置的，WSL 的 Hosts 文件会和 Win 主机的同步，所以我是配置当 WSL 启动时刷新 `windows.local` 的重定向。
![image](https://user-images.githubusercontent.com/24269465/227752676-579eba10-7cb0-457d-a33f-972ff657059c.png)

也可能是不支持域名形式的代理配置？我试试看你的方法

**Comment by miyouzi** [comment]
> 我测试是会使用代理的 用这个脚本设置吧https://gist.github.com/Howard20181/31e61599ecb069483448c03649810c75 windows.local 无法解析 ![image](https://user-images.githubusercontent.com/40033067/227752323-daa16042-5774-4452-a0ca-29f184d424da.png)

因为 `windows.local` 是我自己配置的，WSL 的 Hosts 文件会和 Win 主机的同步，所以我是配置当 WSL 启动时刷新 `windows.local` 的重定向。
![image](https://user-images.githubusercontent.com/24269465/227752737-299cbee0-cd8d-4c5e-b19f-5d0652556527.png)

也可能是不支持域名形式的代理配置？我试试看你的方法

**Comment by miyouzi** [comment]
> 我测试是会使用代理的 用这个脚本设置吧https://gist.github.com/Howard20181/31e61599ecb069483448c03649810c75 windows.local 无法解析 ![image](https://user-images.githubusercontent.com/40033067/227752323-daa16042-5774-4452-a0ca-29f184d424da.png)

使用这个脚本了，感谢。估计是 Hosts 域名兼容性不太好

**Comment by Howard20181** [comment]
反馈给aria2，它应该会直接使用环境变量
是不是不支持socks5h https://github.com/aria2/aria2/issues/1830
