### ISSUE TITLE
[Feature Request] Output folder name should create a folder with different name if it already exists

### ISSUE THREAD

**Issue by Almighty188** [LSPosed/MagiskOnWSALocal#459]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No

### Describe the solution you'd like/描述你想要的解决方案

If there is already an existing output folder with the same name such as WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-13.0, it should create another folder.  
Maybe the best way is the output folder has a date/time stamp as part of the folder name such as WSA_2302.40000.8.0_x64_Release-Nightly-with-magisk-25.2(25200)-stable-MindTheGapps-13.0-YYYYMMDDHHMMSS

The reason for this is let's say you have a working WSA and later, you decide to build WSA again except WSA is the same version resulting in the same output folder name and for some reason, the build either fails to build or install like in the case of https://github.com/LSPosed/MagiskOnWSALocal/issues/450, you would no longer have a working WSA until it is fixed.

**Comment by Howard20181** [comment]
Please move the generated artifacts to another location instead of installing them directly in place.
