### ISSUE TITLE
Ubuntu failure missing ARIA2 / patchelf

### ISSUE THREAD

**Issue by filzek** [LSPosed/MagiskOnWSALocal#462]
### Steps to reproduce/复现步骤

ubuntu is missing ARIA2 / patchelf

### Expected behaviour/预期行为

ubuntu is missing ARIA2 / patchelf

installer should check and install ARIA2 / patchelf

### Actual behaviour/实际行为

ubuntu is missing ARIA2 failure using aria2c and patchelf

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

latest

### Linux distribution info/Linux 发行版信息

wsa ubuntu

### Windows version/Windows 版本

22621.1413

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand none --gapps-variant pico  --root-sol magisk --compress    --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: none
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail
WSA Version=2301.40000.7.0

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

only missing this two packs from the default installer script!!!

**Comment by Howard20181** [comment]
https://github.com/LSPosed/MagiskOnWSALocal/blob/d01fdc3951f74c137a51822152f14bdb07a21237/scripts/install_deps.sh#L43
https://github.com/LSPosed/MagiskOnWSALocal/blob/d01fdc3951f74c137a51822152f14bdb07a21237/scripts/install_deps.sh#L46
