### ISSUE TITLE
[Feature Request] Add Magisk Module by default

### ISSUE THREAD

**Issue by YT-Advanced** [LSPosed/MagiskOnWSALocal#483]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No

### Describe the solution you'd like/描述你想要的解决方案

If user want to add their Magisk module, they create a folder named "Modules" and add .zip module file to this folder. Then run and MagiskOnWSALocal will auto add all module in Modules folder to WSA

**Comment by Howard20181** [comment]
we don't modify `userdata.vhdx` so this is impossible.
