### ISSUE TITLE
[Bug] 选择不压缩时，不应该显示--compress-format

### ISSUE THREAD

**Issue by Doddddd** [LSPosed/MagiskOnWSALocal#484]
### Steps to reproduce/复现步骤

<img width="690" alt="{E198F0C8-FF63-49B8-AF9C-BC0F8DECE8CE}" src="https://user-images.githubusercontent.com/88972478/230914211-f43026e1-9838-4cd2-9bd6-68aa81a7eccb.png">
<img width="693" alt="{BB322184-5E9E-4AC6-AF93-333627AFD3FA}" src="https://user-images.githubusercontent.com/88972478/230914220-468031ed-4f0d-402c-be6b-65364c26eb6f.png">

### Expected behaviour/预期行为

1

### Actual behaviour/实际行为

1

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

1ebd85b

### Linux distribution info/Linux 发行版信息

ubuntu 20.04

### Windows version/Windows 版本

10.0.22621.1413

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIF --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk     --compress-format 
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Insider Fast
Generate Download Links
Generating WSA download link: arch=x64 release_type=Insider Fast

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
# Replace this line with the log / 将此行用日志替换
```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
没有影响
实际上`run.sh`给的参数是`--compress-format ""`，附加的是一个空值而不是什么都没有

**Comment by Doddddd** [comment]
> 没有影响 实际上`run.sh`给的参数是`--compress-format ""`，附加的是一个空值而不是什么都没有

但是直接复制下来用build.sh会出错，可以像gapps和root一样，附加一个none

**Comment by Howard20181** [comment]
但是build.sh那边有些地方靠参数的长度是否为0来决定另一些提示，要改的地方有点多

**Comment by Doddddd** [comment]
> 但是build.sh那边有些地方靠参数的长度是否为0来决定另一些提示，要改的地方有点多

好吧，其实也无伤大雅
