### ISSUE TITLE
无法选择GApps版本

### ISSUE THREAD

**Issue by TheWhiteDog9487** [LSPosed/MagiskOnWSALocal#49]
准确来说是没有地方可以选择  
我看到README里面是这么说的：  
> Support all OpenGApps variants except for aroma (aroma does not support x86_64, please use super instead)
Select the version of Magisk and select the [OpenGApps variant](https://github.com/opengapps/opengapps/wiki#variants) you like, select the root solution (none means no root), select the WSA version and its architecture (mostly x64)

但是我实际操作的时候却是这样的：  
> 构建架构
WSA的更新通道
Magisk版本
是否安装GApps（我选择的是“是”）
是否保留亚马逊应用商店
Root方案
是否压缩输出文件

没了
我最后得到的输出是这个文件名：WSA-with-magisk-stable-OpenGApps-pico_2206.40000.15.0_x64_Release-Nightly.7z  
看这个名字应该的OpenGApps的Pico版本吧，但是文档里说可以自己选择的嘞  
是我哪里做错了嘛？还是怎么回事  
还有一个问题是我从以前的Action构建升级过来，按照说明把文件全部替换进去之后运行了install.ps1，但是完事之后我数据都没了，那几个VHDX虚拟盘是不是不能替换啊？

**Comment by Howard20181** [comment]
因为OpenGApps官方没支持Android 12，现在还在用Android 11的，除了pico之外全部都会bootloops，开不了机，就锁定在pico了，你可以将脚本里的DEBUG=1的注释去掉就可以选了，前几天测过还是bootloops的。等https://github.com/opengapps/opengapps/pull/959 合并

我也是直接从Actions构建的升级上来的，数据没丢，不知道你是什么情况。也试过了手动替换`userdata.vhdx`, 是可以一路从低版本升级上来的，我从Android 11的底层的WSA升级上来也没事。
