### ISSUE TITLE
Use Bromite Browser and Bromite Webview by default

### ISSUE THREAD

**Issue by YT-Advanced** [LSPosed/MagiskOnWSALocal#492]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No

### Describe the solution you'd like/描述你想要的解决方案

The original web browser don't have any ad-blocker or privacy protection. So I think we should replace original browser with Bromite ones

**Comment by Howard20181** [comment]
We should change this for all users.
You can replace Webview overlay by yourself.
