### ISSUE TITLE
[Bug] Magisk Manager (v26.0+) does not get installed automatically as it did for previous versions

### ISSUE THREAD

**Issue by MustardChef** [LSPosed/MagiskOnWSALocal#493]
### Steps to reproduce/复现步骤

1. Build WSA with Magisk (I used the Magisk Canary variant)
2. Install WSA using the "Run.bat" Script
3. Google Play is installed, but Magisk Manager is missing and has to be manually installed

### Expected behaviour/预期行为

Magisk Manager should be installed and start when "Run.bat" is initially run. 

### Actual behaviour/实际行为

However only Play Store starts and Magisk Manager is missing
This can also be seen here https://github.com/LSPosed/MagiskOnWSALocal/discussions/486

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

commit: 8337c73

### Linux distribution info/Linux 发行版信息

OS: Ubuntu Lunar Lobster (development branch) on Windows 10 x86_64
Kernel: 5.15.90.1-microsoft-standard-WSL2
Uptime: 57 secs
Packages: 650 (dpkg), 4 (snap)
Shell: bash 5.2.15
Theme: Adwaita [GTK3]
Icons: Adwaita [GTK3]
Terminal: Relay(266)
CPU: AMD Ryzen 9 3900X (24) @ 3.800GHz
GPU: f01c:00:00.0 Microsoft Corporation Basic Render Driver
Memory: 576MiB / 11921MiB
 

### Windows version/Windows 版本

10.0.22621.1413

### Build Parameters/构建参数

 ./build.sh --arch x64 --release-type WIF --magisk-ver canary --gapps-brand MindTheGapps --gapps-variant pico --root-sol magisk --compress-format zip --remove-amazon

Execute MagiskOnWSALocal Script to build for arm64
INFO: Architecture: arm64
INFO: Release Type: WIF
INFO: Magisk Version: canary
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: zip
Build: RELEASE_TYPE=Insider Fast

### Version requirement/版本要求

- [x] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
# Replace this line with the log / 将此行用日志替换
```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
Can not reproduce

**Comment by Howard20181** [comment]
Maybe it just installed success but didn't create a shortcut in Windows Start menu.

**Comment by YT-Advanced** [comment]
> Maybe it just installed success but didn't create a shortcut in Windows Start menu.

I think nope because we can't run it via wsa://com.topjohnwu.magisk
If we want to use Magisk, we must install it manually via apk file

**Comment by MustardChef** [comment]
> Unable to reproduce

Weird, since multiple other people have reported the same issue.

**Comment by Lukasz88PL** [comment]
I checked it. Only Magisk Manager is not installing, but Magisk still is there. Just have to installed Manager.

**Comment by Howard20181** [comment]
Magisk Manager auto-installation is implemented by Magisk itself, we will not fix this, if you can find the root cause please feedback to upstream.

**Comment by Howard20181** [comment]
Please check if this issue still occurs after https://github.com/LSPosed/MagiskOnWSALocal/commit/07f580587d5c76bfd71855065bc5e0b025ee148e
