### ISSUE TITLE
[Bug] Fails with "Build: an error has occurred, exit"

### ISSUE THREAD

**Issue by michael-zock** [LSPosed/MagiskOnWSALocal#494]
### Steps to reproduce/复现步骤

1. Ran the run.sh script as requested
2. Once the graphical part is done, the  avalanche of output messages seems to tun fine until the below "Build: an error has occurred, exit" problem occurs.

### Expected behaviour/预期行为

Would expect it to succeed as expected by the manual on this project's Readme page instead of failing as in the end of the output in the Logs section.

### Actual behaviour/实际行为

Produce an output with the "mount: /tmp/wsa-build-37bYaWKwbJ_/system_root: mount failed: Operation not permitted." error where trying the Windows script later produces two errors that vanish before I could copy the output and a final one with the following:
```
Get-Content : Cannot find path 'D:\WSL\rootfs\root\Debian\MagiskOnWSALocal\installer\filelist.txt' because it does not
exist.
At D:\WSL\rootfs\root\Debian\MagiskOnWSALocal\installer\Install.ps1:72 char:13
+ $FileList = Get-Content -Path .\filelist.txt
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\WSL\rootfs\r...er\filelist.txt:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At D:\WSL\rootfs\root\Debian\MagiskOnWSALocal\installer\Install.ps1:73 char:23
+ If (((Test-Path -Path $FileList) -Eq $false).Count) {
+                       ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom
   mand

The operation completed successfully.

```

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

8337c73

### Linux distribution info/Linux 发行版信息

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

### Windows version/Windows 版本

22H2 22621.1555

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --magisk-ver stable
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Expand images done

Mount images
mount: /tmp/wsa-build-37bYaWKwbJ_/system_root: mount failed: Operation not permitted.
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Mount Directory
umount: /tmp/wsa-build-37bYaWKwbJ_/system_root: not mounted.
Cleanup Download Directory
```
[//]: <> (Don't modify below)
</details>

**Comment by michael-zock** [comment]
Side note: I tried it as the normal user and with "sudo" to rule out a permissions problem, both failed.

**Comment by Howard20181** [comment]
1. Use WSL2
2. Don't run `*.ps1` in WSL
