### ISSUE TITLE
[Bug] Given solution still produces broken output, now just breaks network connectivity as well

### ISSUE THREAD

**Issue by michael-zock** [LSPosed/MagiskOnWSALocal#496]
### Steps to reproduce/复现步骤

Recommendation to switch to WSL2 breaks network connectivity, script still produces no working output, now the network connectivity is just broken as well.

```
1. Use WSL2
2. Don't run `*.ps1` in WSL
```

_Originally posted by @Howard20181 in https://github.com/LSPosed/MagiskOnWSALocal/issues/494#issuecomment-1510029874_
            
It's a known problem that WSL 2 in Debian and derivatives breaks network connectivity, hence the problems till persists. I'm now left with a WSL install that's just even more broken. Would've updated the original thread, but locking it after the non-solution prevents that.ails to produce working output

### Expected behaviour/预期行为

See previous thread you locked without a working solution.

### Actual behaviour/实际行为

See previous thread you locked without a working solution.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

See previous thread you locked without a working solution.

### Linux distribution info/Linux 发行版信息

See previous thread you locked without a working solution.

### Windows version/Windows 版本

See previous thread you locked without a working solution.

### Build Parameters/构建参数

See previous thread you locked without a working solution.

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

See previous thread you locked without a working solution.

**Comment by Howard20181** [comment]
There are no issues.
It is clearly stated that WSL 1 is not supported, only WSL 2 is supported.
![image](https://user-images.githubusercontent.com/40033067/232312509-a9aaec86-179e-4efd-8f35-d719dba73c9c.png)
