### ISSUE TITLE
Outputing ISO as single file

### ISSUE THREAD

**Issue by CarlGao4** [LSPosed/MagiskOnWSALocal#500]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No

### Describe the solution you'd like/描述你想要的解决方案

On Windows 10 or higher, ISO can be directly mounted without extracting it. Outputing ISO can save the disk space of extracting the files. 

### Additional context/其他信息

I've sent some relative information to @Howard20181 by email

**Comment by Howard20181** [comment]
Appx cannot be registered in a virtual image and must be extracted to the local hard drive.
