### ISSUE TITLE
[Bug] stuck on Generating Magisk download link: release type=stable

### ISSUE THREAD

**Issue by w5b** [LSPosed/MagiskOnWSALocal#503]
### Steps to reproduce/复现步骤

follow the steps

### Expected behaviour/预期行为

magisk download generated

### Actual behaviour/实际行为

it succesfully generates wsa download link but then im stuck on magisk download link

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

ad396d6

### Linux distribution info/Linux 发行版信息

ubuntu

### Windows version/Windows 版本

10.0.22621 build 22621

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --compress --magisk-ver stable --compress-format zip
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: zip

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
# Replace this line with the log / 将此行用日志替换
```
[//]: <> (Don't modify below)
</details>

**Comment by CarlGao4** [comment]
You can use https://vid.rosa.ink/WSA_2302.40000.9.0_x64_Release-Nightly-with-magisk-26.1(26100)-stable-MindTheGapps-13.0.zip
But it doesn't remove the Amazon store. 

Besides, @Howard20181 please check the email.
