### ISSUE TITLE
[Bug] vhdx_to_img throwing a lot of errors with WSA_2303.40000.5.0_x64

### ISSUE THREAD

**Issue by OlyAndy** [LSPosed/MagiskOnWSALocal#512]
### Steps to reproduce/复现步骤

- Run run.sh
- Use Beta or Nightly version of WSA
- Observe errors in script build.sh vhdx_to_img

### Expected behaviour/预期行为

Should be no  Multiply-claimed block(s) type errors in the e2fsck command

### Actual behaviour/实际行为

 Multiply-claimed block type filesystem errors in build.  Newly built WSA environment runs then fails to start on second or third try

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

ad396d6810d8cb87ed8354c89442953e4ab4818a

### Linux distribution info/Linux 发行版信息

WSL Ubuntu 23.04

### Windows version/Windows 版本

11.0.25346

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIS --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --magisk-ver canary
INFO: Architecture: x64
INFO: Release Type: WIS
INFO: Magisk Version: canary
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Insider Slow
Generate Download Links
Generating WSA download link: arch=x64 release_type=Insider Slow (same issue with insider fast)

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Expand images
Convert vhdx to img and remove read-only flag
system_ext: 104/128 files (5.8% non-contiguous), 47850/47994 blocks
resize2fs 1.47.0 (5-Feb-2023)
Resizing the filesystem on /tmp/wsa-build-tZXTKZAGUz_/wsa/x64/system_ext.img to 97568 (4k) blocks.
The filesystem on /tmp/wsa-build-tZXTKZAGUz_/wsa/x64/system_ext.img is now 97568 (4k) blocks long.

system_ext: Duplicate or bad block in use!
system_ext: Multiply-claimed block(s) in inode 62: 115
system_ext: Multiply-claimed block(s) in inode 65: 115
system_ext: Multiply-claimed block(s) in inode 78: 1708 2500 2500 2500 1708 12729 12729 12729 12729 12729 12729 12729 12938--12942 12729 12729 12729 12729 12729 12969--12973 12999 12729 12729 12729 12729 13001--13005 13031 12729 12729 12729 12729 13033--13038 13063 12729 12729 12729 12729 13065--13070 13095 12729 12729 12729 12729 13097-
(truncated)

```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
This is normal as we try to remove unshare_blocks.
