### ISSUE TITLE
[Feature Request] 无网络构建

### ISSUE THREAD

**Issue by ghost** [LSPosed/MagiskOnWSALocal#519]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

在某些情况下（如无代理环境的中国大陆）无法即时下载构建所需资源。

### Describe the solution you'd like/描述你想要的解决方案

提供**多平台**的脚本可在有网络环境配置构建参数和下载所需文件，同时另一个脚本使用已下载的文件完成构建任务。

~~实际上就是将配置/下载过程和构建过程的脚本分开~~

### Additional context/其他信息

我自己的环境：
- 相当于无网络的 WSL2 (巨硬禁止访问host网络于是无法设置代理)
- 有网络的 Windows 10 宿主机 (全局代理)

**Comment by Howard20181** [comment]
所以为什么不直接在那台能联网的电脑上构建

**Comment by zen0null** [comment]
@Howard20181 我也想啊，但能联网的是 Windows 没法跑这个脚本

**Comment by Howard20181** [comment]
WSL2可以设置代理的
https://gist.github.com/Howard20181/31e61599ecb069483448c03649810c75

**Comment by zen0null** [comment]
WSL2 的代理很玄学的，而且多数时候要扯到 Windows 防火墙这种贼麻烦的东西...
~~其实我自己的问题已经解决了~~，但是想到还会有人遇到这个问题就来开了一个 issue

**Comment by skycat2216** [comment]
直接把下載好的檔案丟到download不就好了?
