### ISSUE TITLE
[Feature Request] Add support for preview builds.

### ISSUE THREAD

**Issue by rp1231** [LSPosed/MagiskOnWSALocal#525]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

There is no option for preview builds.

### Describe the solution you'd like/描述你想要的解决方案

An option to choose preview builds

### Additional context/其他信息

Right now a new build was released on the preview channel.
https://github.com/microsoft/WSA/discussions/293

But you have to wait for some time before it become available on the channels currently available on MagiskOnWSALocal.

**Comment by Howard20181** [comment]
https://github.com/LSPosed/MagiskOnWSALocal/commit/615c125030e3f448e4ac5d34f812cd4c0027cc06
