### ISSUE TITLE
Weird errors after 2nd run of install.ps

### ISSUE THREAD

**Issue by Cr4z33** [LSPosed/MagiskOnWSALocal#53]
After having succesfully installed everything on my Windows 11 Pro computer I copied all the WSA directory to my daughter's computer, enabled everything needed for VMs, but after the second install.ps (after the 1st reboot) I got these weird errors while running it.

What is going on please?

![Immagine 2022-08-30 094708](https://user-images.githubusercontent.com/19343851/187381802-0758e9b7-3cce-4e83-92b9-ed488680349c.png)

**Comment by Cr4z33** [comment]
Translation of the top red error sentence:
`Start-Process : Cannot execute the command because of the following error: A specified access session does not exist. It could have been already killed.`

**Comment by Howard20181** [comment]
AppxManifast.xml deployment failed, try to manually execute `Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion -Register . \AppxManifest.xml` to see what the error is reported.

**Comment by Cr4z33** [comment]
Thanks, but I got a new error then (both in my administrator Windows session and in my daughter's standard session).

The Italian red sentence say something like
`Add-AppxPackage : Cannot solve the parameters set using the entered parameters`


![Immagine 2022-08-30 143921](https://user-images.githubusercontent.com/19343851/187439732-0c274262-e31c-47e1-9392-d2bebaf043f3.png)

**Comment by Howard20181** [comment]
You have to type the name of the file to be deployed at the end similar to `.\AppxManifest.xml`

**Comment by Howard20181** [comment]
`Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion -Register .\AppxManifest.xml`

**Comment by Cr4z33** [comment]
> You have to type the name of the file to be deployed at the end similar to `.\AppxManifest.xml`

Yeah my bad sorry.

I realised the mistake only once posting here doh!

Will post back once I try that again.

**Comment by Cr4z33** [comment]
Me again.
This is the new error and thi is the translation of th first two lines
`A positional parameter cannot be found that accepts argument '\AppxManifest.xml'.`
`In line:1 char:1`

Maybe I should stop using a copy of my WSA folder and do all the steps from scratch?

![screenshot](https://user-images.githubusercontent.com/19343851/187621241-2c9f548c-829f-4cb3-9d13-9bf834297691.jpg)

**Comment by Howard20181** [comment]
Do not leave spaces in front of the file path
`.\AppxManifest.xml` means that file in the current directory.

**Comment by Howard20181** [comment]
https://en.wikipedia.org/wiki/Path_(computing)#Absolute_and_relative_paths

**Comment by Cr4z33** [comment]
OK did it again, no error outputs.

Ended up by finding out that WSA can be used in Windows administrators sessions only so no go for standard / guest sessions.

Thanks for you help anyway. 🙂
