### ISSUE TITLE
[Bug] Install Failed WSA using Install.ps1 script

### ISSUE THREAD

**Issue by sahoonalinikanta** [LSPosed/MagiskOnWSALocal#541]
### Steps to reproduce/复现步骤

1. Executing Install.ps1 script in Powershell
2. 
3. 

### Expected behaviour/预期行为

Should install the WSA

### Actual behaviour/实际行为

It is failing with error message
![Screenshot 2023-05-17 112141](https://github.com/LSPosed/MagiskOnWSALocal/assets/41999958/49a74c64-93c0-41bf-99f6-9d215025d3c3)

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

7a33f97d192a4363ddfbc886c08d0f5710e9e2ac

### Linux distribution info/Linux 发行版信息

Distributor ID: Ubuntu
Description: Ubuntu 22.04.2 LTS
Release: 22.04
Codename: jammy

### Windows version/Windows 版本

Windows 11  Pro version 22H2 OS Build 23451.100

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIF --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --magisk-ver beta
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: beta
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Insider Fast

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Start-Process: F:\WSA\InstallDir\Install.ps1:54
Line |
  54 |      Start-Process "wsa://com.topjohnwu.magisk"
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: An error occurred trying to start process 'wsa://com.topjohnwu.magisk' with working directory 'F:\WSA\InstallDir'. The parameter is incorrect.
Start-Process: F:\WSA\InstallDir\Install.ps1:55
Line |
  55 |      Start-Process "wsa://com.android.vending"
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: An error occurred trying to start process 'wsa://com.android.vending' with working directory 'F:\WSA\InstallDir'. The parameter is incorrect.
All Done!
Press any key to exit
PS F:\WSA\InstallDir>
![Screenshot 2023-05-17 112141](https://github.com/LSPosed/MagiskOnWSALocal/assets/41999958/58144b3e-07a0-4785-b820-a7937eec6122)

```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
Please retry with the latest commit
Please provide more logs

**Comment by Howard20181** [comment]
Please double-click Run.bat instead of run ps1 scritp int PlwerShell.

**Comment by sahoonalinikanta** [comment]
Same issue even after double clicking the Run.bat 


Start-Process: F:\WSA\InstallDir\Install.ps1:57
Line |
  57 |      Start-Process "wsa://com.topjohnwu.magisk"
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: An error occurred trying to start process
     | 'wsa://com.topjohnwu.magisk' with working directory 'F:\WSA\InstallDir'. The parameter is incorrect.
Start-Process: F:\WSA\InstallDir\Install.ps1:58
Line |
  58 |      Start-Process "wsa://com.android.vending"
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: An error occurred trying to start process
     | 'wsa://com.android.vending' with working directory 'F:\WSA\InstallDir'. The parameter is incorrect.
All Done!
Press any key to exit
Deployment operation progress: F:\WSA\InstallDir\AppxManifes… [Processing                                            ]



![Screenshot 2023-05-17 164232](https://github.com/LSPosed/MagiskOnWSALocal/assets/41999958/e1d1bd56-584f-4f48-8015-a79c60872a65)

**Comment by sahoonalinikanta** [comment]
title -- Installing MagiskOnWSA

The operation completed successfully.
Installing MicrosoftCorporationII.WindowsSubsystemForAndroid version: 2304.40000.5.0
Dependency package Microsoft.UI.Xaml.2.8 x64 current version: 8.2305.5001.0. Nothing to do.
Dependency package Microsoft.VCLibs.140.00.UWPDesktop x64 current version: 14.0.32530.0. Nothing to do.
Dependency package Microsoft.VCLibs.140.00 x64 current version: 14.0.32530.0. Nothing to do.
Installing MagiskOnWSA....
Start-Process: F:\WSA\InstallDir\Install.ps1:57
Line |
  57 |      Start-Process "wsa://com.topjohnwu.magisk"
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: An error occurred trying to start process 'wsa://com.topjohnwu.magisk' with working directory 'F:\WSA\InstallDir'. The parameter is incorrect.
Start-Process: F:\WSA\InstallDir\Install.ps1:58
Line |
  58 |      Start-Process "wsa://com.android.vending"
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: An error occurred trying to start process 'wsa://com.android.vending' with working directory 'F:\WSA\InstallDir'. The parameter is incorrect.
All Done!
Press any key to exit
Deployment operation progress: F:\WSA\InstallDir\AppxManifes… [Processing                                            ]







![Screenshot 2023-05-17 170251](https://github.com/LSPosed/MagiskOnWSALocal/assets/41999958/b13a526f-fee3-45a4-b580-a7f72f5f5955)

**Comment by Howard20181** [comment]
Start PowerShell as Admin
cd into WSA dir
Run `Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion -Register .\AppxManifest.xml`
What's the output?

**Comment by Howard20181** [comment]
Can you try it in system PowerShell instead of PowerShell 7?

**Comment by sahoonalinikanta** [comment]
same result as previous 
![Screenshot 2023-05-17 183816](https://github.com/LSPosed/MagiskOnWSALocal/assets/41999958/fc25ded1-ecf2-43bf-b98a-a221a61e756d)

**Comment by Howard20181** [comment]
Have you turned on developer mode yet?

**Comment by sahoonalinikanta** [comment]
yes Developer mode turned on in the previous version , after update the WSA is not at all opening .

**Comment by Howard20181** [comment]
Tested on Windows version 23475 and install smoothly. No idea how this issue happen.

**Comment by YT-Advanced** [comment]
@sahoonalinikanta WSA didn't support for using from other drive/partition. You can follow this guide to fix it:
https://github.com/YT-Advanced/WSA-Script/blob/main/Guides/MoveToExtDrive.md

**Comment by Howard20181** [comment]
I'm install in D driver.

**Comment by sahoonalinikanta** [comment]
Hi ,
I am trying to install in F drive. It is not external drive. It is an
partition of internal hard drive only. It was working previously in that
drive .

**Comment by YT-Advanced** [comment]
> Hi , I am trying to install in F drive. It is not external drive. It is an partition of internal hard drive only. It was working previously in that drive .

Yes, I know, but sometime WSA didn't work when install at other drive. So I think you should test it

**Comment by sahoonalinikanta** [comment]
So which partition should I use ?? C drive ,??

**Comment by YT-Advanced** [comment]
> So which partition should I use ?? C drive ,??

Yes, I think. Or follow the guide above if you want to use in another drive (like F:\ )

**Comment by sahoonalinikanta** [comment]
thanks a lot for the support  it worked. I did not use C drive , just installed from another location . Did not use the existing location
