### ISSUE TITLE
[Bug] Build fails and completely crash WSL2

### ISSUE THREAD

**Issue by IzaacJ** [LSPosed/MagiskOnWSALocal#544]
### Steps to reproduce/复现步骤

1. Clone the repository
2. Run ./scripts/run.sh in fresh install of Ubuntu-22.04 or Ubuntu-20.04 in WSL2

### Expected behaviour/预期行为

A successful build

### Actual behaviour/实际行为

Everything goes smooth until it's converting images to vhdx, which is the last line printed before wsl crashes completely, throwing me back to a Powershell prompt.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

ca48cf372cfa383fc6d4245d47083f9e55563e8e

### Linux distribution info/Linux 发行版信息

Tested with fresh Ubuntu 22.04 and 20.04 under WSL2

### Windows version/Windows 版本

10.0.22621

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --magisk-ver stable
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Umount images
umount: /tmp/wsa-build-FYWKdyLtwy_/system_root_merged/vendor unmounted
umount: /tmp/wsa-build-FYWKdyLtwy_/system_root_merged/product unmounted
umount: /tmp/wsa-build-FYWKdyLtwy_/system_root_merged/system_ext unmounted
umount: /tmp/wsa-build-FYWKdyLtwy_/system_root_merged unmounted
done

Shrink images
/: 2812/5632 files (11.8% non-contiguous), 249762/492200 blocks
resize2fs 1.46.5 (30-Dec-2021)
Resizing the filesystem on /tmp/wsa-build-FYWKdyLtwy_/wsa/x64/system.img to 250053 (4k) blocks.
The filesystem on /tmp/wsa-build-FYWKdyLtwy_/wsa/x64/system.img is now 250053 (4k) blocks long.

vendor: 1098/1120 files (4.1% non-contiguous), 61018/63638 blocks
resize2fs 1.46.5 (30-Dec-2021)
Resizing the filesystem on /tmp/wsa-build-FYWKdyLtwy_/wsa/x64/vendor.img to 61023 (4k) blocks.
The filesystem on /tmp/wsa-build-FYWKdyLtwy_/wsa/x64/vendor.img is now 61023 (4k) blocks long.

product: 169/480 files (7.7% non-contiguous), 188777/304371 blocks
resize2fs 1.46.5 (30-Dec-2021)
Resizing the filesystem on /tmp/wsa-build-FYWKdyLtwy_/wsa/x64/product.img to 188984 (4k) blocks.
The filesystem on /tmp/wsa-build-FYWKdyLtwy_/wsa/x64/product.img is now 188984 (4k) blocks long.

system_ext: Inode 78 extent tree (at level 2) could be narrower.  IGNORED.
system_ext: Inode 90 extent tree (at level 1) could be narrower.  IGNORED.
system_ext: 98/128 files (5.1% non-contiguous), 44129/56013 blocks
resize2fs 1.46.5 (30-Dec-2021)
Resizing the filesystem on /tmp/wsa-build-FYWKdyLtwy_/wsa/x64/system_ext.img to 44152 (4k) blocks.
The filesystem on /tmp/wsa-build-FYWKdyLtwy_/wsa/x64/system_ext.img is now 44152 (4k) blocks long.

Shrink images done

Convert images to vhdx
PS C:\Users\Izaac>
```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
It looks like an OOM kill caused by lack of memory, please restart your computer.
