### ISSUE TITLE
[Suggestion] Remove OpenGApps from the GApps brand

### ISSUE THREAD

**Issue by s1204IT** [LSPosed/MagiskOnWSALocal#546]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Not compatible with A12.1, A13

### Describe the solution you'd like/描述你想要的解决方案

If you don't plan to add other brands of GApps, change the only question to a straightforward "Do you want to install GApps?".

### Additional context/其他信息

I can't find any other GApps brand candidates, so I think we can choose MindTheGapps for now.

**Comment by YT-Advanced** [comment]
Yes, remove OpenGApps and maybe add NikGapps or BiTGApps instead

**Comment by s1204IT** [comment]
> Yes, remove OpenGApps and maybe add LiteGapps or NikGapps or BiTGApps instead

![Screenshot_20230524_183406_Chrome](https://github.com/LSPosed/MagiskOnWSALocal/assets/52069677/3ce5a91d-773e-479e-bc65-cf403a605474)
![Screenshot_20230524_183435_Chrome](https://github.com/LSPosed/MagiskOnWSALocal/assets/52069677/4c7b1f96-7a1d-45bf-9112-40fddd466b36)
![Screenshot_20230524_183514_Chrome](https://github.com/LSPosed/MagiskOnWSALocal/assets/52069677/80d6e848-7930-4f0e-8233-967f2ad665e2)

"**x86_64**" is nothing.

**Comment by Howard20181** [comment]
Haven't seen OpenGapps updated in a while, plan to remove OpenGapps.
Supporting a new flavor of GApps takes a lot of time and isn't something I really want to do.
