### ISSUE TITLE
[Bug] Play Store crashes when you try to install any app

### ISSUE THREAD

**Issue by MustardChef** [LSPosed/MagiskOnWSALocal#550]
### Steps to reproduce/复现步骤

1.  Build WSA using MagiskOnWSALocal
2. Open and sign in to your Google Account in the Google Play Store
3. Try to install an app
4. Play Store will crash

### Expected behaviour/预期行为

Application from the Play Store should install withou any issue

### Actual behaviour/实际行为

Play Store crashes

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

969d2b2fa69e132b7ad8d220ffa984cf0f4d7c75

### Linux distribution info/Linux 发行版信息

OS: Ubuntu 22.04.2 LTS on Windows 10 x86_64
Kernel: 5.15.90.1-microsoft-standard-WSL2

### Windows version/Windows 版本

10.0.22621.1702

### Build Parameters/构建参数

sudo ./build.sh --arch x64 --release-type WIF --magisk-ver canary --gapps-brand MindTheGapps --gapps-variant pico --root-sol none --compress-format zip --remove-amazon

INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: canary
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: none
INFO: Compress Format: zip
Build: RELEASE_TYPE=Insider Fast

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
# Replace this line with the log / 将此行用日志替换
```
[//]: <> (Don't modify below)
</details>

**Comment by MustardChef** [comment]
https://github.com/LSPosed/MagiskOnWSALocal/assets/68516357/ddd10410-479d-466d-9458-05a9ceea5ed3

**Comment by Howard20181** [comment]
Check microsoft/WSA#309

**Comment by MustardChef** [comment]
> Check [microsoft/WSA#309](https://github.com/microsoft/WSA/issues/309)

Ah, so that is the reason for this.

**Comment by Howard20181** [comment]
Not thing we can do.

**Comment by YT-Advanced** [comment]
> Not thing we can do.

Turn off this setting will work ?
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/70064328/9bf5ff94-81db-432c-928a-36e6f78023ff)

**Comment by Howard20181** [comment]
> > Not thing we can do.
> 
> Turn off the setting "Block installation of malcious apps" will work ?
> ![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/70064328/9bf5ff94-81db-432c-928a-36e6f78023ff)
> 
> 
> 

No.
Only work if you disable antivirus.

**Comment by YT-Advanced** [comment]
> Only work if you disable antivirus.

Hmm, so sad :(

**Comment by MustardChef** [comment]
I would like to add that some users are also having their Play Store app crash without installing anything.

**Comment by Howard20181** [comment]
> I would like to add that some users are also having their Play Store app crash without installing anything. Is this also to do with the WSA stated earlier

Did only the Play Store crash (single app) or the entire WSA crash (entire WSA reload)?
Logs are needed to know what happened.

**Comment by Howard20181** [comment]
Try turning off all manually installed antivirus software, leaving only Microsoft Defender.

**Comment by Howard20181** [comment]
From the logs, the line `I FileSystemRedirectionHandler: Package verification request` always appears a few seconds before the system crashes.
When installing the application, WSA will call "FileSystemRedirectionHandler" to forward the file to the antivirus software on Windows for real-time scanning, regardless of whether the "Prevent malware installation " is disabled (this feature will prevent the installation of malware when it is turned on, and pop-up notifications when it is turned off, so it needs to be scanned whether it is turned on or off), but some third-party antivirus providers are not specified when setting the engine name, which can cause `WsaClient` to crash.
There are several situations that may trigger a "Package verification request"
1. when trying to install Magisk App during a new WSA installation
2. The Play Store will update itself automatically when needed
3. The Play Store will update the Play service when needed (this can happen at login)
4. Installing the app by any method (including installing on the Play Store)

**Comment by MustardChef** [comment]
So this is still due to the Package Verification/ Malicious app detection feature on WSA?

**Comment by marchingon12** [comment]
Seems to have been fixed with the release of WSA_2304.40000.7.0_x64

**Comment by MustardChef** [comment]
Will close the issue as it is no longer an issue now.
