### ISSUE TITLE
[Bug] Getting this error when I try to use the run.sh script

### ISSUE THREAD

**Issue by rp1231** [LSPosed/MagiskOnWSALocal#559]
### Steps to reproduce/复现步骤

Use the run.sh script.

### Expected behaviour/预期行为

See the build in the output folder

### Actual behaviour/实际行为

I'm getting an error at the end of the script and it exits

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

644d1dc06e3d79d42a2abbb26c0b06dd3b739b8d

### Linux distribution info/Linux 发行版信息

Ubuntu

### Windows version/Windows 版本

Build 22621.1778

### Build Parameters/构建参数

Options selected in the run.sh script are:
x64_Release-Nightly-with-magisk-26.1(26100)-stable-MindTheGapps-13.0-RemovedAmazon

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Convert vhdx to RAW image
Convert vhdx to RAW image done

Mount images
fuse.erofs 1.6-g689372cd
disk: /tmp/wsa-build-yweBsrDlGM_/wsa/x64/system.img
offset: 0
mountpoint: /tmp/wsa-build-yweBsrDlGM_/erofs
dbglevel: 0
fuse.erofs 1.6-g689372cd
disk: /tmp/wsa-build-yweBsrDlGM_/wsa/x64/vendor.img
offset: 0
mountpoint: /tmp/wsa-build-yweBsrDlGM_/erofs/vendor
dbglevel: 0
fuse.erofs 1.6-g689372cd
disk: /tmp/wsa-build-yweBsrDlGM_/wsa/x64/product.img
offset: 0
mountpoint: /tmp/wsa-build-yweBsrDlGM_/erofs/product
dbglevel: 0
fuse.erofs 1.6-g689372cd
disk: /tmp/wsa-build-yweBsrDlGM_/wsa/x64/system_ext.img
offset: 0
mountpoint: /tmp/wsa-build-yweBsrDlGM_/erofs/system_ext
dbglevel: 0
done

Create overlayfs for EROFS
mk_overlayfs: label system
        lowerdir=/tmp/wsa-build-yweBsrDlGM_/erofs
        upperdir=/tmp/wsa-build-yweBsrDlGM_/upper/system
        workdir=/tmp/wsa-build-yweBsrDlGM_/worker/system
        merged=/tmp/wsa-build-yweBsrDlGM_/system_root_merged
mount: /tmp/wsa-build-yweBsrDlGM_/system_root_merged: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Mount Directory
umount: /tmp/wsa-build-yweBsrDlGM_/erofs/vendor unmounted
umount: /tmp/wsa-build-yweBsrDlGM_/erofs/system_ext unmounted
umount: /tmp/wsa-build-yweBsrDlGM_/erofs/product unmounted
umount: /tmp/wsa-build-yweBsrDlGM_/erofs unmounted
umount: /tmp/wsa-build-yweBsrDlGM_/system_root_merged/vendor: no mount point specified.
umount: /tmp/wsa-build-yweBsrDlGM_/system_root_merged/system_ext: no mount point specified.
umount: /tmp/wsa-build-yweBsrDlGM_/system_root_merged/product: no mount point specified.
umount: /tmp/wsa-build-yweBsrDlGM_/system_root_merged: not mounted.
Cleanup Download Directory
```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
It looks like your system does not support Overlayfs, please update your system
What is your specific system version number? Don't just type Ubuntu

**Comment by Howard20181** [comment]
Upload `dmesg`
It is recommended to update the system before any operation

**Comment by Howard20181** [comment]
The log is incomplete, please rebuild it again and redirect `dmesg` to a file.

**Comment by Howard20181** [comment]
> How do I do this? The redirect dmesg to a file part

https://www.google.com/search?q=linux+output+redirect+to+file

**Comment by Howard20181** [comment]
dmesg will be cleared after one read.
So you have to rebuild it once to trigger the problem to see the logs.
