### ISSUE TITLE
如果我选择不加入GAPPS ，则会报错无法构建

### ISSUE THREAD

**Issue by Yvan-W** [LSPosed/MagiskOnWSALocal#56]
![image](https://user-images.githubusercontent.com/80970174/187811095-73bd2de8-fffb-4d4e-96ae-ef2035f7b3b4.png)

**Comment by Yvan-W** [comment]
![image](https://user-images.githubusercontent.com/80970174/187818990-07c52d1f-60d1-4bca-82d4-177002dc608b.png)
download wsa error

**Comment by Howard20181** [comment]
选择无GApps报错会修复
下载错误重试几遍或者改DNS（你图中的就是DNS解析失败）或者挂代理
