### ISSUE TITLE
[Bug] a new error

### ISSUE THREAD

**Issue by q12p1** [LSPosed/MagiskOnWSALocal#564]
### Steps to reproduce/复现步骤

1. after build,open"run.bat“
2. 
3. 

### Expected behaviour/预期行为

install WSA

### Actual behaviour/实际行为

have a error

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

how sees SHA?

### Linux distribution info/Linux 发行版信息

Windows's install error

### Windows version/Windows 版本

10.0.22621.1702

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --compress --magisk-ver canary --compress-format zip
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: canary
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: zip
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073CFB, 提供的程序包已安装，且禁止重新安装该程序包。请检查 AppXDeployme
nt-Server 事件日志了解详细信息。
另一个用户已安装此应用的打包版本。未打包版本无法替换该版本。冲突程序包为 MicrosoftCorporationII.WindowsSubsystemForAndr
oid，由 CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US 发布。
注意: 有关其他信息，请在事件日志中查找 [ActivityId] efca6a96-8fd1-0007-84c3-d1efd18fd901，或使用命令行 Get-AppPackageLo
g -ActivityID efca6a96-8fd1-0007-84c3-d1efd18fd901
所在位置 D:\Magisk\MagiskOnWSALocal\output\WSA_2303.40000.5.0_x64_Release-Nightly-with-magisk-47d2d4e3(26102)-canary-Mi
ndTheGapps-13.0\Install.ps1:167 字符: 1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (D:\Magisk\Magis...ppxManifest.xml:String) [Add-AppxPackage], PSInvalidO
   perationException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
Please uninstall manually using the command `Remove-AppxPackage -Package MicrosoftCorporationII.WindowsSubsystemForAndroid` in Powershell.
Note: the data in the prevent installation will be lost, please backup by yourself.

**Comment by q12p1** [comment]
> 

下一个错误 ： `PS C:\Users\14909.DESKTOP-8F8QQ42> Remove-AppxPackage -Package MicrosoftCorporationII.WindowsSubsystemForAndroid        Remove-AppxPackage : 部署失败，原因是 HRESULT: 0x80073CFA, 无法卸载。请联系你的软件供应商。 (异常来自 HRESULT:0x80073CF
A)
程序包管理器中止了 Remove 操作，因为传递的参数无效: MicrosoftCorporationII.WindowsSubsystemForAndroid。
注意: 有关其他信息，请在事件日志中查找 [ActivityId] bd4eff35-902d-0006-093a-51bd2d90d901，或使用命令行 Get-AppPackageLo
g -ActivityID bd4eff35-902d-0006-093a-51bd2d90d901
所在位置 行:1 字符: 1
+ Remove-AppxPackage -Package MicrosoftCorporationII.WindowsSubsystemFo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (MicrosoftCorpor...ystemForAndroid:String) [Remove-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.RemoveAppxPackageCommand`

**Comment by q12p1** [comment]
> Please uninstall manually using the command `Remove-AppxPackage -Package MicrosoftCorporationII.WindowsSubsystemForAndroid` in Powershell. Note: the data in the prevent installation will be lost, please backup by yourself.

Reply me,Quick!!!!

**Comment by q12p1** [comment]
looks no anyone answer me,I need open a new issue
