### ISSUE TITLE
[Bug] Can't access the camera in apps

### ISSUE THREAD

**Issue by Tsynskyy** [LSPosed/MagiskOnWSALocal#565]
### Steps to reproduce/复现步骤

1. Install WSA (arch: x64, WSA release type: retail, Root: Yes, Root solution: magisk, Magisk version: stable, install GApps: Yes, keep Amazon Appstore: No, compress the output: No)
2. Run any app and try to take a photo

### Expected behaviour/预期行为

Should output an image from the camera

### Actual behaviour/实际行为

Just black screen with no image
For example: Google Lens and Google Chrome
![Screenshot 2023-05-26 180000](https://github.com/LSPosed/MagiskOnWSALocal/assets/82811759/c10a9c38-9aef-4c55-add4-a409c06406f9)
![Screenshot 2023-05-26 180336](https://github.com/LSPosed/MagiskOnWSALocal/assets/82811759/a3796d4c-5c90-4186-9f14-3941a015cb85)

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

fddfd79

### Linux distribution info/Linux 发行版信息

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
UBUNTU_CODENAME=jammy

### Windows version/Windows 版本

12.0.22621.1778

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --magisk-ver stable
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [x] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
![Screenshot 2023-05-26 180000](https://github.com/LSPosed/MagiskOnWSALocal/assets/82811759/4547843d-3406-4555-933c-49064c6be4d2)
![Screenshot 2023-05-26 180336](https://github.com/LSPosed/MagiskOnWSALocal/assets/82811759/7b3a3248-8fcc-456a-aab4-2ab8f2d25335)
```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
Report to Microsoft.
