### ISSUE TITLE
[Feature Request] Gyroscope/Accelerometer support

### ISSUE THREAD

**Issue by sorgelig** [LSPosed/MagiskOnWSALocal#568]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Somehow

### Describe the solution you'd like/描述你想要的解决方案

Many modern portable PCs like GPD Win4 have accelerometer/gyroscope sensor, and it would be good if it would be passed to android environment, so games such as racing games would be able to utilize it.

**Comment by Howard20181** [comment]
Report to Microsoft.
