### ISSUE TITLE
[Bug] Unable to open any apps

### ISSUE THREAD

**Issue by BlueOutside** [LSPosed/MagiskOnWSALocal#570]
### Steps to reproduce/复现步骤

1. Install WSA on an unsupported machine
2. Open Files
3. Wait for any notifications and see if no window opens

### Expected behaviour/预期行为

Normally The Files app must start in order to see any apps

### Actual behaviour/实际行为

2 Notifications pops up
The first one about finishing system update
The second one about Configure physical keyboard
And the files app doesn't open

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

fddfd79

### Linux distribution info/Linux 发行版信息

WSL Ubuntu 22.04

### Windows version/Windows 版本

22621.1778

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --magisk-ver stable
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

WSA Version=2303.40000.5.0

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/70482525/d62b2066-8cc8-4e16-bbc6-a42b2c236e68)
```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
Report to Microsoft.
