### ISSUE TITLE
[Bug] Build failed

### ISSUE THREAD

**Issue by subby2006** [LSPosed/MagiskOnWSALocal#574]
### Steps to reproduce/复现步骤

1. open run.sh
2. use default settings to build
3. build fails and exits

### Expected behaviour/预期行为

build should complete and start the zipping process

### Actual behaviour/实际行为

build fails with error message
`<E> erofs:      Could not format the device : [Error 28] No space left on device

ERROR: Failed to make erofs image from /tmp/wsa-build-YjCE5zjLec_/system_root_merged/product
Build: an error has occurred, exit`

my device has around 256gb of storage left so storage shouldn't be an issue

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

c622109

### Linux distribution info/Linux 发行版信息

WSL2:Arch

### Windows version/Windows 版本

22621.1702

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --compress --magisk-ver stable --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Create EROFS images
mkfs.erofs 1.6-g689372cd
Build completed.
umount: /tmp/wsa-build-YjCE5zjLec_/system_root_merged/vendor (overlay) unmounted
mkfs.erofs 1.6-g689372cd
Processing app/webview/webview.apk ...
<E> erofs:      Could not format the device : [Error 28] No space left on device

ERROR: Failed to make erofs image from /tmp/wsa-build-YjCE5zjLec_/system_root_merged/product
Build: an error has occurred, exit
```
[//]: <> (Don't modify below)
</details>

**Comment by Almighty188** [comment]
Can you post the output of the "df" command in Linux without the quotes which will show exactly what the free space is.

**Comment by subby2006** [comment]
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/65925208/16cf0723-4098-4e98-83f5-3a8443a43f6b)

**Comment by Howard20181** [comment]
Check the free space of `/tmp`. If it is too tiny, remove the `#` in this line.
https://github.com/LSPosed/MagiskOnWSALocal/blob/aefda92b20022ee509a2ba3fa12ccf46ac3f2d33/scripts/build.sh#L31

**Comment by rupbabu** [comment]
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/137851466/d7415486-a318-4810-a02c-3aa4f2a589ab)
                                                      it is showing noe what to do to fix the problem and dowmload it?

**Comment by rupbabu** [comment]
plz somebody help me, what to do?

**Comment by rupbabu** [comment]
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/137851466/f407031e-f81e-4793-9035-072ecaf30e66)
 now what to do  for downloading the ga apps or fix the problem?

**Comment by stunlocked1** [comment]
> plz somebody help me, what to do?

https://github.com/LSPosed/MagiskOnWSALocal/issues/615#issuecomment-1647270403 try this one👍
