### ISSUE TITLE
[Bug] An error occurred while installing: the manifest is not in the package root

### ISSUE THREAD

**Issue by fuweichin** [LSPosed/MagiskOnWSALocal#580]
### Steps to reproduce/复现步骤

1. clone and build MagiskOnWSALocal with WSL Debian
2. extract the output zip
3. run Install.ps1 or Run.bat

### Expected behaviour/预期行为

WSA gets installed and can be launched successfully.

### Actual behaviour/实际行为

An error occurred.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

c62210927796c7152eebe217bfc22ed6473eb46b

### Linux distribution info/Linux 发行版信息

Linux wsl-debian 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 GNU/Linux

Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

### Windows version/Windows 版本

10.0.22621 N/A Build 22621

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --compress --magisk-ver stable --compress-format zip
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: zip
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9, Install failed. Please contact your software vendor.
(Exception from HRESULT: 0x80073CF9)
Rejecting a request to register from AppxBundleManifest.xml because the manifest is not in the package root.
NOTE: For additional information, look for [ActivityId] a0ed85cf-97b5-0005-fa28-f0a0b597d901 in the Event Log or use
the command line Get-AppPackageLog -ActivityID a0ed85cf-97b5-0005-fa28-f0a0b597d901
At C:\WSADistros\WSA_2304.40000.7.0_x64_Release-Nightly\Install.ps1:167 char:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\WSADistros\W...ppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```
![error-screenshot](https://github.com/LSPosed/MagiskOnWSALocal/assets/1687235/54c98ac4-e657-41d8-a41f-ee0d594d6505)

[//]: <> (Don't modify below)
</details>

**Comment by UranusITS** [comment]
Same issue. I move the folder to `C:\WSA` but both `Run.bat` and `Install.ps1` fail.

My OS is Windows 11 Build 25381 (insider canary channel)

![Run.bat](https://github.com/LSPosed/MagiskOnWSALocal/assets/38391284/a0232274-29d2-4dee-a94b-4a735b772d16)

**Comment by UranusITS** [comment]
I have installed WSA through [this blog](https://sysin.org/blog/wsa/). I uninstalled it in the start menu before I tried this repo, but now I can't install the original version of WSA or WSA built from this repo.

Maybe an incomplete uninstall issue but can't find any app related to WSA in start menu or in the setting.

**Comment by rmdlv** [comment]
Same issue.

**Comment by YT-Advanced** [comment]
@UranusITS I think you should go to `%LOCALAPPDATA%/Packages/` and delete the folder named `MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe`

**Comment by UranusITS** [comment]
@YT-Advanced I tried this method but it's not working :(

Actually I deleted any folder containing `WindowsSubsystemForAndroid` or related to 'WSA' by searching in `everything`, but sadly not working.

Anyway, I finally solved this issue after a Windows Update (canary channel) and found the error log was different with error code `HRESULT: 0x80073CFB`. After I reinstalled WSA (original version) and uninstalled it with any method I can find, I managed to install the WSA built from this repo successfully.

However, I'm sorry that I cannot reproduce the exact operations to solve this issue. I still think an incomplete uninstall caused it.

<details><summary>the different log mentioned above, in Chinese</summary>

```txt
Installing MagiskOnWSA....
Add-AppxPackage: 部署失败，原因是 HRESULT: 0x80073CFB, 提供的程序包已安装，且禁止重新安装该程序包。
请检查 AppXDeployment-Server 事件日志了解详细信息。

另一个用户已安装此应用的打包版本。未打包版本无法替换该版本。
冲突程序包为 MicrosoftCorporationII.WindowsSubsystemForAndroid，
由 CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US 发布。

注意: 有关其他信息，请在事件日志中查找 [ActivityId] b1775193-a400-000f-de7f-cbb100a4d901，
或使用命令行 Get-AppPackageLog -ActivityID b1775193-a400-000f-de7f-cbb100a4d901
```

</details>

**Comment by Pete-Whiting** [comment]
I had the same issue, Turns out it was because I had installed WSA in a different profile previously. Had to go uninstall it from there and delete the profile to get it to install. Hope that helps you.

**Comment by thyman3** [comment]
I’m getting the same issue and can’t find a solution. I uninstalled the previous WSA and any related files/folders. No other profiles on the device where traces might have remained. Still getting the error:
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9
Rejecting a request to register from AppxBundleManifest.xml because the manifest is not in the package root.

**Comment by ha1vorsen** [comment]
I'm also getting this issue. There aren't any other WSA profiles on this PC other than a WSL installation on this same user account.

**Comment by BoYanZh** [comment]
https://github.com/WSA-Community/WSAGAScript/issues/28#issuecomment-992113337 It solves my problem.
