### ISSUE TITLE
[Bug] Unable to build package, Could not download magisk : link error

### ISSUE THREAD

**Issue by m0usaa** [LSPosed/MagiskOnWSALocal#596]
### Steps to reproduce/复现步骤

_**1. I updated the ubuntu by sudo apt update and apt upgrade
2. secondly i opened the script by ls and cd magiskowsalocal 
3. i typed scripts/run.sh to open the builder 
4. i choosed retail and stable channel with non root
5. it started building 
6. magisk download link error so it stopped build**_
7. 
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/69627848/9db83f9c-d318-40aa-b5d5-c2062170cd25)

### Expected behaviour/预期行为

**_1. The wsa script shouldn't download magisk because i choosed non root version
2. the wsa script should continue to build with working links 
3. was script should work and build the program_** 

### Actual behaviour/实际行为

**_1. wsa script stopped working 
2. magisk link error_** 

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

bbc86e1

### Linux distribution info/Linux 发行版信息

OS: Ubuntu 22.04.2 LTS on Windows 11 x86_64
Kernel: 5.15.90.1-microsoft-standard-WSL2

### Windows version/Windows 版本

10.0.22621.1848

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol none --gapps-brand MindTheGapps --remove-amazon
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: none
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
# WSA Build Version=2304.40000.10.0

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/3b0a2424-33b7-4f1b-8434-9dc37ddfff81?P1=1687288384&P2=404&P3=2&P4=Bb%2fMY1vJwwA2rLMq8%2fy7mj98Rx4js6t5CmVnMGwrxbAdL0iEiG6EN8erzfxg2FwILlj9fQScBcbLycEDpstKEQ%3d%3d
path: ../download/Microsoft.UI.Xaml.2.8_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/28edaebf-8019-4844-ba32-8ab019bc9391?P1=1687288337&P2=404&P3=2&P4=aRosUyzvUm4ExNkCtJHFP2rf6fG4YtLN%2f5He7Eyk7R%2fkFMgeHJ1lewcE149yhtQlcmfSNrYwnS8wMDy7zIyxBQ%3d%3d
path: ../download/Microsoft.VCLibs.140.00_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/986a8270-404c-4470-871d-5c4090dcaa79?P1=1687288420&P2=404&P3=2&P4=WpaK%2fka0%2b1z6MPeXDPXHZevyjIssoSwrH5swJdn9grAwjXcvVpBx867gCNc3exh%2fUBX3eb9Z7MWyO7eSfGO7YQ%3d%3d
path: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/4c5002df-7e1c-4bc9-9eb8-977498fa49f9?P1=1687315922&P2=404&P3=2&P4=Ua6V0q1mFfwVZ48Vdlrnx42TCojoGGvf15DcsquuqRrljnHGMnb3ABKMjQtN4SupU4wOVvv9BhRURPZIze5B8w%3d%3d
path: ../download/wsa-retail.zip

Generating Magisk download link: release type=stable
download link: https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@26.1/app-release.apk
Generating MindTheGapps download link: arch=x64 variant=pico
download link: https://downloads.sourceforge.net/project/wsa-mtg/x86_64/20230323/MindTheGapps-13.0.0-x86_64-20230323.zip
Download Artifacts

06/20 22:02:30 [NOTICE] Downloading 6 item(s)

06/20 22:02:30 [NOTICE] GID#c04fb18aeeef58d9 - Download has already completed: ../download/Microsoft.VCLibs.140.00_x64.appx

06/20 22:02:30 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00_x64.appx

06/20 22:02:31 [NOTICE] GID#0871efb30c8ecc6a - Download has already completed: ../download/Microsoft.UI.Xaml.2.8_x64.appx

06/20 22:02:31 [NOTICE] GID#772797d7f121ac57 - Download has already completed: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

06/20 22:02:31 [NOTICE] GID#99509de296656d15 - Download has already completed: ../download/wsa-retail.zip

06/20 22:02:31 [ERROR] CUID#11 - Download aborted. URI=https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@26.1/app-release.apk
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@26.1/app-release.apk
  -> [SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure: Error in the pull function.

06/20 22:02:31 [NOTICE] Download complete: ../download/Microsoft.UI.Xaml.2.8_x64.appx

06/20 22:02:31 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

06/20 22:02:31 [NOTICE] Download complete: ../download/wsa-retail.zip

06/20 22:02:31 [NOTICE] Download GID#61dcdf56f3a2bf5a not complete: ../download/magisk-stable.zip
[#69aae0 0B/0B CN:1 DL:0B]
06/20 22:02:32 [NOTICE] CUID#12 - Redirecting to https://netix.dl.sourceforge.net/project/wsa-mtg/x86_64/20230323/MindTheGapps-13.0.0-x86_64-20230323.zip
[#69aae0 0B/0B CN:1 DL:0B]
06/20 22:02:33 [NOTICE] GID#69aae081cd3f0fd0 - Download has already completed: ../download/MindTheGapps-x64-13.0.zip

06/20 22:02:33 [NOTICE] Download complete: ../download/MindTheGapps-x64-13.0.zip

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
c04fb1|OK  |       0B/s|../download/Microsoft.VCLibs.140.00_x64.appx
0871ef|OK  |       0B/s|../download/Microsoft.UI.Xaml.2.8_x64.appx
772797|OK  |       0B/s|../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
99509d|OK  |       0B/s|../download/wsa-retail.zip
61dcdf|ERR |       0B/s|../download/magisk-stable.zip
69aae0|OK  |       0B/s|../download/MindTheGapps-x64-13.0.zip

Status Legend:
(OK):download completed.(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
We have encountered an error while downloading files.


```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
Try again. There may be some error on jsdelivr.

**Comment by m0usaa** [comment]
> Try again. There may be some error on jsdelivr.

this error with me since 11 days that i think ...... i did everything and full remove the script and reclone again but same error in the magisk link

**Comment by m0usaa** [comment]
and i have reset the firewall settings in my laptop but same error with me .... idk why ....may you please update the magisk download link or help me ..... icant use the script or build wsa 😣

**Comment by Howard20181** [comment]
Can you download Magisk using that link in the browser?

**Comment by m0usaa** [comment]
may you update the magisk link howard

**Comment by Howard20181** [comment]
That link is same as Magisk's build-in update. If it's can't download why no one report in Magisk repo?
It's was update by John wu.


Best regards,

Howard
________________________________

**Comment by m0usaa** [comment]
may you update the script to not download magisk as i choosed non root ?

**Comment by m0usaa** [comment]
and idk how to fi or report ..... may you help me howard please

**Comment by m0usaa** [comment]
i did it thanks howard ❤️

**Comment by m0usaa** [comment]
it finished with rooted version ..... im not using root anymore howard

**Comment by m0usaa** [comment]
how can i install unrooted version  howard ?

**Comment by m0usaa** [comment]
> `build.sh --root-sol none --magisk-custom`

thank you bro so much bro you are a hero ❤️
