### ISSUE TITLE
Can't Install using the PowerShell.exe -ExecutionPolicy Bypass -File .\Install.ps1

### ISSUE THREAD

**Issue by fyndrkraze** [LSPosed/MagiskOnWSALocal#599]
### Steps to reproduce/复现步骤

1. Open windows terminal (admin)
2. cd to wsa location
3. Run PowerShell.exe -ExecutionPolicy Bypass -File .\Install.ps1

### Expected behaviour/预期行为

Should install normally

### Actual behaviour/实际行为

I get an error saying "Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.     Windows cannot deploy to path"

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

i dont know how to get the SHA

### Linux distribution info/Linux 发行版信息

Ubuntu latest

### Windows version/Windows 版本

22621.1848

### Build Parameters/构建参数

Architecture: x64
Release Type: retail
Magisk Version: stable
GApps Brand: MindTheGapps
GApps Variant: pico
Root Solution: magisk
RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.     Windows cannot deploy to path                                                                                           WSA_2304.40000.10.0_x64_Release-Nightly-with-magisk-26.1(26100)-stable-MindTheGapps-13.0-RemovedAmazon of file system   type 9P.                                                                                                                NOTE: For additional information, look for [ActivityId] ffecc02f-9f94-0000-d40f-6800959fd901 in the Event Log or use    the command line Get-AppPackageLog -ActivityID ffecc02f-9f94-0000-d40f-6800959fd901                                     At \\wsl.localhost\Ubuntu\home\fyndr\MagiskOnWSALocal\output\WSA_2304.40000.10.0_x64_Release-Nightly-with-magisk-26.1(2 6100)-stable-MindTheGapps-13.0-RemovedAmazon\Install.ps1:167 char:1                                                     + Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (\\wsl.localhost...ppxManifest.xml:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
![Screenshot 2023-06-23 193113](https://github.com/LSPosed/MagiskOnWSALocal/assets/136185737/bd0ae832-4396-47c2-9e7e-fed41898b218)

```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
Copy to a local drive.
