### ISSUE TITLE
the last wsa on magisk project is end ???

### ISSUE THREAD

**Issue by m0usaa** [LSPosed/MagiskOnWSALocal#6]
because i can't get it what will you do in this problem ??

**Comment by Howard20181** [comment]
GitHub support does not respond to the reason for disabling. You can use the local version before this.

**Comment by m0usaa** [comment]
I suggest that you use any other platform to upload the wsa project as was the case in the past

**Comment by m0usaa** [comment]
wsa on magisk is very very very useful for me i'm using it every day in my work ... and i can't install the local version because i dont know how to install it it's very easy but not for me ... please howard choose another platform to updade the releases file like the past .... best wishes thanks ❤️
