### ISSUE TITLE
[Bug] WSA will automatically start when open web links on windows

### ISSUE THREAD

**Issue by babaolanqiu** [LSPosed/MagiskOnWSALocal#603]
### Steps to reproduce/复现步骤

Open a web link in windows applications. This issue only occur on some apps, like [Fluent Search](https://github.com/adirh3/Fluent-Search) and [SnipDo](https://snipdo-app.com/). Some other apps can still open links properly.

### Expected behaviour/预期行为

Open a webpage on Windows default browser.

### Actual behaviour/实际行为

Immediately after click the link, WSA is started. And the webpage will only be opened on Windows browser after WSA starts running.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

bbc86e1b3d27b5f7525b41dd9d8d2213511c1f09

### Linux distribution info/Linux 发行版信息

Ubuntu 22.04.2 LTS

### Windows version/Windows 版本

22621.1848

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol none --gapps-brand MindTheGapps --remove-amazon
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: none
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>
No errors in logs.
</details>

**Comment by Howard20181** [comment]
This is a feature, not a bug.

**Comment by Howard20181** [comment]
https://github.com/microsoft/WSA/discussions/293
Check chapter What’s New, point 3.
