### ISSUE TITLE
[Bug] Continue: WSA will automatically start when open web links on windows

### ISSUE THREAD

**Issue by babaolanqiu** [LSPosed/MagiskOnWSALocal#604]
### Steps to reproduce/复现步骤

**This is not a feature request! This behavior is happening in the latest commit WSA and I want to stop it.**
When opening a web link in windows applications, WSA will automatically start. This issue only occur on some apps, like [Fluent Search](https://github.com/adirh3/Fluent-Search) and [SnipDo](https://snipdo-app.com/). Some other apps can still open links properly.
I have disabled all the AppLink support in app settings.

### Expected behaviour/预期行为

Open a webpage on Windows default browser like usual.

### Actual behaviour/实际行为

Immediately after click the link, WSA is started. And the webpage will be opened on Windows browser a few seconds later when WSA starts running.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

bbc86e1b3d27b5f7525b41dd9d8d2213511c1f09

### Linux distribution info/Linux 发行版信息

Ubuntu 22.04.2 LTS

### Windows version/Windows 版本

22621.1848

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol none --gapps-brand MindTheGapps --remove-amazon
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: none
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

No errors in logs.
</details>

**Comment by Howard20181** [comment]
Report to Microsoft. This feature does not control by us.

**Comment by Howard20181** [comment]
Try these steps to disable it:
1. Run `wsa://com.android.settings` to open Android Settings for WSA
2. Navigate to "Apps"
3. Tap "Default apps", and tap "Opening links."
4. On that page you can customize which apps are allowed to open links (aka. start from links).

**Comment by babaolanqiu** [comment]
Yes I have disabled this function in all apps that could possibly open links, but it still doesn't work.

**Comment by Howard20181** [comment]
This should be a feature request to Microsoft: "Custiomize Opening links (AppLink) for WSA". This issue will close, any update should perform to Microsoft/WSA#342

**Comment by Howard20181** [comment]
Found a way to disable single apps' opening links:
1. On the left side of the Windows Subsystem for Android, click Apps
2. On the apps' list click one for the app's three-dot menu, then click App settings
3. On the "App Info" page, tap "Open by default"
4. On that page you can disable "Open supported links".
