### ISSUE TITLE
[Suggestion] Making the output be built directly in Windows

### ISSUE THREAD

**Issue by nxllxvxid** [LSPosed/MagiskOnWSALocal#606]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No it is more of an idea to make installation and files easier to work with

### Describe the solution you'd like/描述你想要的解决方案

Add an instruction telling people to cd into /mnt/ and then whichever drive they want to work with as well as folder because these folders directly connect to the Windows drives allowing you to just build it and then extract directly in Windows

### Additional context/其他信息

![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/19805594/52404479-16bd-4966-83b4-1146c3a457e9)

**Comment by Doddddd** [comment]
https://docs.microsoft.com/en-us/windows/wsl/filesystems#file-storage-and-performance-across-file-systems
