### ISSUE TITLE
[Bug] app 秒退

### ISSUE THREAD

**Issue by HE996** [LSPosed/MagiskOnWSALocal#607]
### Steps to reproduce/复现步骤

最新的release app秒退，旧版的2022 12月份的没问题。
1.安装最新的release包中的wsa.
2.安装网易狼人杀app：https://adl.netease.com/d/g/langrensha/c/gw?from=qr
3.运行，安装更新之后秒退。
很多app，比如qq等等，运行过程中也非常卡，秒退。

### Expected behaviour/预期行为

无

### Actual behaviour/实际行为

无

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

无

### Linux distribution info/Linux 发行版信息

无

### Windows version/Windows 版本

无

### Build Parameters/构建参数

无

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
# Replace this line with the log / 将此行用日志替换
```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
游戏没特别注明允许在模拟器上运行默认它反模拟器。
