### ISSUE TITLE
Allow to change the device from the default Pixel 5 to a range of Pixel devices, incl. Pixel 7 Pro and/or Pixel Fold

### ISSUE THREAD

**Issue by supermansaga** [LSPosed/MagiskOnWSALocal#609]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No.

### Describe the solution you'd like/描述你想要的解决方案

During the pink screen where we could select a lot of stuff, I wish to see the selection of devices

### Additional context/其他信息

I just don't know the difference in devices would bring what kind of functionality. Just cosmetics? Thx

**Comment by Howard20181** [comment]
Why? It is just cosmetics. There is no functional difference.

**Comment by YT-Advanced** [comment]
Huh, no need to add it, I think.
You can follow the guide in my repos if you really need it

**Comment by supermansaga** [comment]
> Why? It is just cosmetics. There is no functional difference.

Well, if it's the actual physical device, then pixel 7 pro is 64 bit only. Pixel 5 is 32 bit only. P7P is more superior for sure. Just don't know what it means when emulated. Thx

**Comment by Howard20181** [comment]
It is just a display name.
