### ISSUE TITLE
GApps Pico won't download

### ISSUE THREAD

**Issue by Zerubel** [LSPosed/MagiskOnWSALocal#61]
![image](https://user-images.githubusercontent.com/105385589/188242699-3af2476a-dd0e-4356-a6ca-6c68ad6e500c.png)
it doesn't ask me which gapps I want (pico is fine) but the download fails.
I am able to download the gapps pico zip from sourceforge via my browser.

**Comment by Cortexian** [comment]
I'm having the same issue, looks like there is some kind of SSL/TLS error with the Open GApps download link from sourceforge.

**Comment by miaulightouch** [comment]
try to execute this line to upgrade system certs
`apt install ca-certificates`

**Comment by Howard20181** [comment]
Has the problem been solved after updating the certificate? @Zerubel @Cortexian

**Comment by Howard20181** [comment]
https://github.com/aria2/aria2/issues/1636

**Comment by mueksh-b** [comment]
> Yes, after updating certificates the problem has been fixed.

**Comment by Cortexian** [comment]
> Has the problem been solved after updating the certificate? @Zerubel @Cortexian

Yes this fixed the download issue for Open GApps, thank you!

**Comment by caiohamamura** [comment]
> try to execute this line to upgrade system certs
> 
> ```shell
> apt install ca-certificates
> ```

Shouldn't it be added to the `run.sh` after all?

**Comment by Howard20181** [comment]
> > try to execute this line to upgrade system certs
> > 
> > ```shell
> > apt install ca-certificates
> > ```
> 
> Shouldn't it be added to the `run.sh` after all?

ca-certificates is installed by default, users should update the system by themselves
