### ISSUE TITLE
[Bug] Installer doesn't work properly when ran from an user without admin rights

### ISSUE THREAD

**Issue by derivativeoflog7** [LSPosed/MagiskOnWSALocal#618]
### Steps to reproduce/复现步骤

1. Create a user account without admin rights
2. Build WSA
3. Try installing WSA, WIndows will ask for credentials for an admin account

### Expected behaviour/预期行为

WSA should install in the local user

### Actual behaviour/实际行为

WSA will be installed on the admin account, not on the local account, and the ps1 script throws errors when trying to launch wsa://something (tho interestingly, it does show the "send anonymous data" window)

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

21e80a3

### Linux distribution info/Linux 发行版信息

Debian sid via WSL2

### Windows version/Windows 版本

10.0.22621.1702

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --magisk-ver stable
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

WSA Build Version=2305.40000.6.0

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/21a6f30d-0ec0-46da-92cf-04e35cf18efc?P1=1688921107&P2=404&P3=2&P4=gXYKj8j9hE8yvRt1rqKmyad1Jtv9Twvy2r%2fCRBPL3xlyyrgbVr5YDBw98M8Bq3LCux9HQSAM51ErEcHGKlmqQQ%3d%3d
path: ../download/Microsoft.UI.Xaml.2.8_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/28edaebf-8019-4844-ba32-8ab019bc9391?P1=1688921027&P2=404&P3=2&P4=ettSQaiDqTjtSsD5r56MLGYuHIFANuaRY%2bxRNZlJyGQ6P8UMoAJDSEm7yogNs3xLOugi%2beZ1vNtxzSiZSaJkxQ%3d%3d
path: ../download/Microsoft.VCLibs.140.00_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/986a8270-404c-4470-871d-5c4090dcaa79?P1=1688921137&P2=404&P3=2&P4=WubeB4%2bqXoWgJ5TDk56KlzJ%2bUvw4uMzPBW4vp6QcPIYBu2apq5Q5nu%2fxQUCe7Rjy5ePc54hUXxqpG0nqWNMOjw%3d%3d
path: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/862fe146-d265-4305-9951-f8c5983f427d?P1=1688948804&P2=404&P3=2&P4=PVm3APL6l11t9uwXIktTTP%2bYUAGQb2UujtUWuCOGlAHWFyN%2b7ExlVWDN0eN%2bmtot80xqEZvbkamn7h237o3omQ%3d%3d
path: ../download/wsa-retail.zip

Generating Magisk download link: release type=stable
download link: https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@26.1/app-release.apk
Generating MindTheGapps download link: arch=x64 variant=pico
download link: https://downloads.sourceforge.net/project/wsa-mtg/x86_64/20230323/MindTheGapps-13.0.0-x86_64-20230323.zip
Download Artifacts

07/09 18:34:02 [NOTICE] Downloading 6 item(s)

07/09 18:34:02 [NOTICE] GID#ff2be9b5fd5bb267 - Download has already completed: ../download/Microsoft.UI.Xaml.2.8_x64.appx

07/09 18:34:02 [NOTICE] GID#24b06b9c29a8380f - Download has already completed: ../download/Microsoft.VCLibs.140.00_x64.appx

07/09 18:34:02 [NOTICE] Download complete: ../download/Microsoft.UI.Xaml.2.8_x64.appx

07/09 18:34:02 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00_x64.appx

07/09 18:34:02 [NOTICE] GID#fd494e63180ec030 - Download has already completed: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

07/09 18:34:02 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

07/09 18:34:02 [NOTICE] GID#da6ebe3c3ebeea49 - Download has already completed: ../download/wsa-retail.zip

07/09 18:34:02 [NOTICE] Download complete: ../download/wsa-retail.zip

07/09 18:34:02 [NOTICE] GID#4764ad89bf72812d - Download has already completed: ../download/magisk-stable.zip

07/09 18:34:02 [NOTICE] Download complete: ../download/magisk-stable.zip

07/09 18:34:02 [NOTICE] CUID#12 - Redirecting to https://altushost-swe.dl.sourceforge.net/project/wsa-mtg/x86_64/20230323/MindTheGapps-13.0.0-x86_64-20230323.zip
[#8343ed 0B/0B CN:1 DL:0B]
07/09 18:34:03 [NOTICE] GID#8343edf3342ee7f8 - Download has already completed: ../download/MindTheGapps-x64-13.0.zip

07/09 18:34:03 [NOTICE] Download complete: ../download/MindTheGapps-x64-13.0.zip

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
ff2be9|OK  |       0B/s|../download/Microsoft.UI.Xaml.2.8_x64.appx
24b06b|OK  |       0B/s|../download/Microsoft.VCLibs.140.00_x64.appx
fd494e|OK  |       0B/s|../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
da6ebe|OK  |       0B/s|../download/wsa-retail.zip
4764ad|OK  |       0B/s|../download/magisk-stable.zip
8343ed|OK  |       0B/s|../download/MindTheGapps-x64-13.0.zip

Status Legend:
(OK):download completed.
Extract WSA
unzipping WsaPackage_2305.40000.6.0_x64_Release-Nightly.msix to /tmp/wsa-build-79SSye4BgC_/wsa
unzipping from /tmp/wsa-build-79SSye4BgC_/wsa/WsaPackage_2305.40000.6.0_x64_Release-Nightly.msix
Extract done

Extract Magisk
Magisk version: 26.1 (26100)
done

Extract MindTheGapps
Archive:  ../download/MindTheGapps-x64-13.0.zip
signed by SignApk
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/app/GoogleCalendarSyncAdapter/GoogleCalendarSyncAdapter.apk

  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk

  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/app/PrebuiltExchange3Google/PrebuiltExchange3Google.apk
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/etc/default-permissions/default-permissions-google.xml
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/etc/default-permissions/default-permissions-mtg.xml
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/etc/permissions/com.google.android.dialer.support.xml
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/etc/permissions/privapp-permissions-google-product.xml
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/etc/security/fsverity/gms_fsverity_cert.der
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/etc/sysconfig/d2d_cable_migration_feature.xml
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/etc/sysconfig/google-hiddenapi-package-allowlist.xml
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/etc/sysconfig/google.xml
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/etc/sysconfig/google_build.xml
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/framework/com.google.android.dialer.support.jar
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/lib/libjni_latinimegoogle.so
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/lib64/libjni_latinimegoogle.so
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/overlay/GmsOverlay.apk
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/overlay/GmsSettingsProviderOverlay.apk
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/priv-app/AndroidAutoStub/AndroidAutoStub.apk
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/priv-app/GmsCore/GmsCore.apk
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/priv-app/GooglePartnerSetup/GooglePartnerSetup.apk
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/priv-app/GoogleRestore/GoogleRestore.apk
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/priv-app/Phonesky/Phonesky.apk
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/product/priv-app/Velvet/Velvet.apk
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/system_ext/etc/permissions/privapp-permissions-google-system-ext.xml
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/system_ext/priv-app/GoogleFeedback/GoogleFeedback.apk
  inflating: /tmp/wsa-build-79SSye4BgC_/gapps/system/system_ext/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk
Extract done

Convert vhdx to RAW image
Convert vhdx to RAW image done

Mount images
fuse.erofs 1.6-g689372cd
disk: /tmp/wsa-build-79SSye4BgC_/wsa/x64/system.img
offset: 0
mountpoint: /tmp/wsa-build-79SSye4BgC_/erofs
dbglevel: 0
fuse.erofs 1.6-g689372cd
disk: /tmp/wsa-build-79SSye4BgC_/wsa/x64/vendor.img
offset: 0
mountpoint: /tmp/wsa-build-79SSye4BgC_/erofs/vendor
dbglevel: 0
fuse.erofs 1.6-g689372cd
disk: /tmp/wsa-build-79SSye4BgC_/wsa/x64/product.img
offset: 0
mountpoint: /tmp/wsa-build-79SSye4BgC_/erofs/product
dbglevel: 0
fuse.erofs 1.6-g689372cd
disk: /tmp/wsa-build-79SSye4BgC_/wsa/x64/system_ext.img
offset: 0
mountpoint: /tmp/wsa-build-79SSye4BgC_/erofs/system_ext
dbglevel: 0
done

Create overlayfs for EROFS
mk_overlayfs: label system
        lowerdir=/tmp/wsa-build-79SSye4BgC_/erofs
        upperdir=/tmp/wsa-build-79SSye4BgC_/upper/system
        workdir=/tmp/wsa-build-79SSye4BgC_/worker/system
        merged=/tmp/wsa-build-79SSye4BgC_/system_root_merged
mount: overlay mounted on /tmp/wsa-build-79SSye4BgC_/system_root_merged.
mk_overlayfs: label vendor
        lowerdir=/tmp/wsa-build-79SSye4BgC_/erofs/vendor
        upperdir=/tmp/wsa-build-79SSye4BgC_/upper/vendor
        workdir=/tmp/wsa-build-79SSye4BgC_/worker/vendor
        merged=/tmp/wsa-build-79SSye4BgC_/system_root_merged/vendor
mount: overlay mounted on /tmp/wsa-build-79SSye4BgC_/system_root_merged/vendor.
mk_overlayfs: label product
        lowerdir=/tmp/wsa-build-79SSye4BgC_/erofs/product
        upperdir=/tmp/wsa-build-79SSye4BgC_/upper/product
        workdir=/tmp/wsa-build-79SSye4BgC_/worker/product
        merged=/tmp/wsa-build-79SSye4BgC_/system_root_merged/product
mount: overlay mounted on /tmp/wsa-build-79SSye4BgC_/system_root_merged/product.
mk_overlayfs: label system_ext
        lowerdir=/tmp/wsa-build-79SSye4BgC_/erofs/system_ext
        upperdir=/tmp/wsa-build-79SSye4BgC_/upper/system_ext
        workdir=/tmp/wsa-build-79SSye4BgC_/worker/system_ext
        merged=/tmp/wsa-build-79SSye4BgC_/system_root_merged/system_ext
mount: overlay mounted on /tmp/wsa-build-79SSye4BgC_/system_root_merged/system_ext.
Create overlayfs for EROFS done

Remove Amazon Appstore
done

Add device administration features
done

Integrate Magisk
/debug_ramdisk(/.*)?    u:object_r:magisk_file:s0
/data/adb/magisk(/.*)?   u:object_r:magisk_file:s0
Inject zygote restart /tmp/wsa-build-79SSye4BgC_/system_root_merged/system/etc/init/hw/init.zygote32.rc
awk: not an option: -i
Inject zygote restart /tmp/wsa-build-79SSye4BgC_/system_root_merged/system/etc/init/hw/init.zygote64_32.rc
awk: not an option: -i
Inject zygote restart /tmp/wsa-build-79SSye4BgC_/system_root_merged/system/etc/init/hw/init.zygote64.rc
awk: not an option: -i
Integrate Magisk done

Add extra packages
Add extra packages done

Integrate MindTheGapps
Integrate MindTheGapps done

Fix MindTheGapps prop
fixing /tmp/wsa-build-79SSye4BgC_/system_root_merged/system/build.prop
fixing /tmp/wsa-build-79SSye4BgC_/system_root_merged/vendor/build.prop
fixing /tmp/wsa-build-79SSye4BgC_/system_root_merged/vendor/odm/etc/build.prop
done

Create EROFS images
mkfs.erofs 1.6-g689372cd
Build completed.
umount: /tmp/wsa-build-79SSye4BgC_/system_root_merged/vendor (overlay) unmounted
mkfs.erofs 1.6-g689372cd
Build completed.
umount: /tmp/wsa-build-79SSye4BgC_/system_root_merged/product (overlay) unmounted
mkfs.erofs 1.6-g689372cd
Build completed.
umount: /tmp/wsa-build-79SSye4BgC_/system_root_merged/system_ext (overlay) unmounted
mkfs.erofs 1.6-g689372cd
Build completed.
umount: /tmp/wsa-build-79SSye4BgC_/system_root_merged (overlay) unmounted
Create EROFS images done

Umount images
umount: /tmp/wsa-build-79SSye4BgC_/erofs/vendor unmounted
umount: /tmp/wsa-build-79SSye4BgC_/erofs/product unmounted
umount: /tmp/wsa-build-79SSye4BgC_/erofs/system_ext unmounted
umount: /tmp/wsa-build-79SSye4BgC_/erofs unmounted
done

Convert images to vhdx
Convert images to vhdx done

Remove signature and add scripts
Remove signature and add scripts done

Generate info
WSA_2305.40000.6.0_x64_Release-Nightly-with-magisk-26.1(26100)-stable-MindTheGapps-13.0-RemovedAmazon

Finishing building....
done

Cleanup Work Directory
done
deactivate python3 venv

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
In D:\WSA\Install.ps1:58 car:5
+     Start-Process "wsa://com.android.vending"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
Currently only support install via admin.
