### ISSUE TITLE
[Bug] WSASettings.exe DLLs missing

### ISSUE THREAD

**Issue by JM-Lemmi** [LSPosed/MagiskOnWSALocal#626]
### Steps to reproduce/复现步骤

Tried on **VMwareWS 20** VM as well as **Dell Precision 3480** bare metal.

1. Fresh Windows 11 install (with local account), install WSL 2
2. Follow Installation steps
(x64; WSA Retail; Rooted; Magisk stable; GApps; Remove Amazon Store; No compressed output)
4. Play Store starts, WSA seems to work fine
5. Start WSASettings.exe

### Expected behaviour/预期行为

WSA Settings open.

### Actual behaviour/实际行为

Cannot start because of missing DLLs:
`VCRUNTIME140_APP.DLL`, `MSVCP140_APP.DLL`, `VCRUNTIME140_1_APP.DLL`

![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/41118534/ad52ad6c-f319-402f-bcb4-07c4373ab1c9)
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/41118534/94023811-5675-451f-b607-82a2f47ea828)
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/41118534/711b353b-6d86-461b-bdb3-b6c064aa6837)

Screenshot from Process explorer showing, its looking through Path for the DLL and can't find it.

![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/41118534/b1858498-ac96-41e7-a87d-7e73733d5be3)

These DLLs can be found for example in `C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.32530.0_x64__8wekyb3d8bbwe\`.

So I added that directly to Path. It seems to find the DLL, the loading Arrow can be seen, no error message about missing DLLs, but WSASettings never start.
Tried both x86 and x64 version of the DLL.

![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/41118534/6341a95f-3a03-4837-9bc3-a88b8b422129)

At this point my knowledge stops me from further troubleshooting.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

21e80a355e9d4a7a358d2c2905f6d3bf75e4681b

### Linux distribution info/Linux 发行版信息

Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux

### Windows version/Windows 版本

Windows 11 22H2 22621.1992

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --magisk-ver stable
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

WSA Build Version=2305.40000.6.0

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/41118534/6341a95f-3a03-4837-9bc3-a88b8b422129)

[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
Report to Microsoft.
