### ISSUE TITLE
[Bug] /tmp doesn;t have enough space

### ISSUE THREAD

**Issue by mio-19** [LSPosed/MagiskOnWSALocal#632]
### Steps to reproduce/复现步骤

1. Running the script normally

### Expected behaviour/预期行为

-

### Actual behaviour/实际行为

```
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
0f65cd|OK  |   3.6MiB/s|../download/magisk-stable.zip
647e8a|OK  |   127KiB/s|../download/Microsoft.VCLibs.140.00_x64.appx
9da6a6|OK  |   194KiB/s|../download/Microsoft.UI.Xaml.2.8_x64.appx
5ff009|OK  |   194KiB/s|../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
972f2b|OK  |   5.0MiB/s|../download/MindTheGapps-x64-13.0.zip
877330|OK  |   3.0MiB/s|../download/wsa-retail.zip

Status Legend:
(OK):download completed.
Extract WSA
unzipping WsaPackage_2305.40000.6.0_x64_Release-Nightly.msix to /tmp/wsa-build-KeVhikGEWF_/wsa
unzipping from /tmp/wsa-build-KeVhikGEWF_/wsa/WsaPackage_2305.40000.6.0_x64_Release-Nightly.msix
Traceback (most recent call last):
  File "/home/user/MagiskOnWSALocal/scripts/extractWSA.py", line 112, in <module>
    zip.extractall(archdir)
  File "/usr/lib/python3.11/zipfile.py", line 1679, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/lib/python3.11/zipfile.py", line 1734, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/lib/python3.11/shutil.py", line 200, in copyfileobj
    fdst_write(buf)
OSError: [Errno 28] No space left on device
ERROR: Unzip WSA failed, is the download incomplete?
Build: an error has occurred, exit

Cleanup Work Directory
deactivate python3 venv
Cleanup Download Directory
```

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

21e80a355e9d4a7a358d2c2905f6d3bf75e4681b

### Linux distribution info/Linux 发行版信息

ArchWSL

### Windows version/Windows 版本

-

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --magisk-ver stable
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

WSA Build Version=2305.40000.6.0

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

-

**Comment by mio-19** [comment]
workaround

```
sudo umount -l /tmp
```

**Comment by zafirab19** [comment]
Convert vhdx to RAW image
Convert vhdx to RAW image done

Mount images
fuse.erofs 1.6-g689372cd
disk: /tmp/wsa-build-e7Ktg34ECG_/wsa/x64/system.img
offset: 0
mountpoint: /tmp/wsa-build-e7Ktg34ECG_/erofs
dbglevel: 0
<E> erofs: cannot find valid erofs superblock
failed to read erofs super block
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Mount Directory
umount: /tmp/wsa-build-e7Ktg34ECG_/erofs/vendor: no mount point specified.
umount: /tmp/wsa-build-e7Ktg34ECG_/erofs/system_ext: no mount point specified.
umount: /tmp/wsa-build-e7Ktg34ECG_/erofs/product: no mount point specified.
umount: /tmp/wsa-build-e7Ktg34ECG_/erofs: not mounted.
umount: /tmp/wsa-build-e7Ktg34ECG_/system_root_merged/vendor: no mount point specified.
umount: /tmp/wsa-build-e7Ktg34ECG_/system_root_merged/system_ext: no mount point specified.
umount: /tmp/wsa-build-e7Ktg34ECG_/system_root_merged/product: no mount point specified.
umount: /tmp/wsa-build-e7Ktg34ECG_/system_root_merged: no mount point specified.
Cleanup Download Directory
root@DESKTOP-S0451OQ:/home/wilhelm/MagiskOnWSALocal/scripts#

**Comment by qq280579056** [comment]
> 
我也遇到了

**Comment by qq280579056** [comment]
> 将 vhdx 转换为 RAW 图像 将 vhdx 转换为 RAW 图像 完成
> 
> 挂载映像 fuse.erofs 1.6-g689372cd 磁盘：/tmp/wsa-build-e7Ktg34ECG_/wsa/x64/system.img 偏移：0 挂载点：/tmp/wsa-build-e7Ktg34ECG_/erofs dbglevel：0 erofs：找不到有效的erofs超级块 无法读取erofs超级块 构建：发生错误，退出
> 
> 清理工作目录 清理挂载目录 umount: /tmp/wsa-build-e7Ktg34ECG_/erofs/vendor: 未指定挂载点。 umount: /tmp/wsa-build-e7Ktg34ECG_/erofs/system_ext: 未指定安装点。 umount: /tmp/wsa-build-e7Ktg34ECG_/erofs/product: 未指定安装点。 umount：/tmp/wsa-build-e7Ktg34ECG_/erofs：未安装。 umount: /tmp/wsa-build-e7Ktg34ECG_/system_root_merged/vendor: 未指定安装点。 umount: /tmp/wsa-build-e7Ktg34ECG_/system_root_merged/system_ext: 未指定安装点。 umount: /tmp/wsa-build-e7Ktg34ECG_/system_root_merged/product: 未指定安装点。 umount: /tmp/wsa-build-e7Ktg34ECG_/system_root_merged: 未指定安装点。 清理下载目录 root@DESKTOP-S0451OQ:/home/wilhelm/MagiskOnWSALocal/scripts#

我也遇到了

**Comment by YT-Advanced** [comment]
@zafirab19 Check #620

**Comment by KonpakuSyl** [comment]
> @zafirab19 Check #620

it works, thanks.I hope the maintainer can merge it could be helpful
