### ISSUE TITLE
[Bug] erofs build error

### ISSUE THREAD

**Issue by enchantable** [LSPosed/MagiskOnWSALocal#638]
### Steps to reproduce/复现步骤

1. clone directory
2. download OpenGApps android 11.0 x64 stock from https://opengapps.org/
3. follow custom gapps tutorial [here](https://github.com/LSPosed/MagiskOnWSALocal/blob/main/docs/Custom-GApps.md)

### Expected behaviour/预期行为

build succeeds and i get wsa

### Actual behaviour/实际行为

i get a perverse error: 

Create EROFS images
mkfs.erofs 1.6-g689372cd
Build completed.
umount: /tmp/wsa-build-ygSjdCSlto_/system_root_merged/vendor (overlay) unmounted
mkfs.erofs 1.6-g689372cd
Build completed.
umount: /tmp/wsa-build-ygSjdCSlto_/system_root_merged/product (overlay) unmounted
mkfs.erofs 1.6-g689372cd
Build completed.
umount: /tmp/wsa-build-ygSjdCSlto_/system_root_merged/system_ext (overlay) unmounted
mkfs.erofs 1.6-g689372cd
Processing system/priv-app/VpnDialogs/oat/x86_64/VpnDialogs.vdex ...
<E> erofs:      Could not format the device : [Error 5] Input/output error

ERROR: Failed to make erofs image from /tmp/wsa-build-ygSjdCSlto_/system_root_merged
Build: an error has occurred, exit

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

21e80a355e9d4a7a358d2c2905f6d3bf75e4681b

### Linux distribution info/Linux 发行版信息

![Screenshot 2023-07-27 233302](https://github.com/LSPosed/MagiskOnWSALocal/assets/121919654/655b9b70-b0cd-47e5-8a1a-b8ec002dd7a6)

### Windows version/Windows 版本

22621.1992

### Build Parameters/构建参数

./scripts/build.sh --offline --arch x64 --gapps-brand OpenGApps --gapps-variant stock

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```

Create EROFS images
mkfs.erofs 1.6-g689372cd
Build completed.
umount: /tmp/wsa-build-ygSjdCSlto_/system_root_merged/vendor (overlay) unmounted
mkfs.erofs 1.6-g689372cd
Build completed.
umount: /tmp/wsa-build-ygSjdCSlto_/system_root_merged/product (overlay) unmounted
mkfs.erofs 1.6-g689372cd
Build completed.
umount: /tmp/wsa-build-ygSjdCSlto_/system_root_merged/system_ext (overlay) unmounted
mkfs.erofs 1.6-g689372cd
Processing system/priv-app/VpnDialogs/oat/x86_64/VpnDialogs.vdex ...
<E> erofs:      Could not format the device : [Error 5] Input/output error

ERROR: Failed to make erofs image from /tmp/wsa-build-ygSjdCSlto_/system_root_merged
Build: an error has occurred, exit

```
[//]: <> (Don't modify below)
</details>

**Comment by enchantable** [comment]
btw i also tried to update build.sh as mentioned in #615 but that didn't work either!

**Comment by skycat2216** [comment]
[](https://github.com/LSPosed/MagiskOnWSALocal/issues/593#issue-1761874072)
