### ISSUE TITLE
Test—Path：无法将参数绑定到参数 "Path ”，因为该参数是空值。

### ISSUE THREAD

**Issue by Ckarefulon** [LSPosed/MagiskOnWSALocal#658]
### Steps to reproduce/复现步骤

1.  下载Git
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/138026126/25d15846-ad71-4011-b7a6-0f955a8427a6)

2. git clone https ://github. com/LSPosed/MagiskOnWSALocal .git-depth 1
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/138026126/7703c8d8-d7a1-4f6d-b3db-4a0f57d04a87)

3.  cd MagiskOnWSALocal     ./scripts/run.sh
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/138026126/dfb766da-da18-499e-bbab-d6fd698b77ce)

4. 运行"C:\Users\-\MagiskOnWSALocal\scripts\run.sh"
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/138026126/108dcf57-edde-480e-a9f0-12f4d5791c7e)

5. 运行"C:\Users\-\MagiskOnWSALocal\installer\Run.bat"
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/138026126/338907aa-6587-4a7e-8255-74d0a99e305d)

![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/138026126/3beb9e54-0518-4e73-9ef5-a002fd3de653)

6. 重复步骤5

### Expected behaviour/预期行为

不报错

### Actual behaviour/实际行为

报错

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

请问怎么看？

### Linux distribution info/Linux 发行版信息

?

### Windows version/Windows 版本

25926.1000

### Build Parameters/构建参数

x64

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/138026126/f89adcb0-8e0e-42cf-a9d4-837e863813ff)

[//]: <> (Don't modify below)
</details>

**Comment by skycat2216** [comment]
![螢幕擷取畫面 2023-10-08 013937](https://github.com/LSPosed/MagiskOnWSALocal/assets/33820902/d4cd7e91-87b8-435f-9670-7195a800c529)
光靠你圖裡那個PS前綴我就知道你他X壓根沒看說明

**Comment by skycat2216** [comment]
碰到LSPosed停更，回來罵一下
你是鉇🐎的RZ還是Dinner?e04你這🐕日的減重鉇🐴看不懂英文可以自覺爪巴回牆內😁🫵🏻🎠的nCov鼓揮嗎?
