### ISSUE TITLE
[Bug] Script exits with failed to read erofs super block

### ISSUE THREAD

**Issue by ajb3932** [LSPosed/MagiskOnWSALocal#670]
### Steps to reproduce/复现步骤

1. git clone https://github.com/LSPosed/MagiskOnWSALocal.git
2. ./MagiskOnWSALocal/scripts/run.sh
3. `failed to read erofs super block`

### Expected behaviour/预期行为

The built package is in the 'output' folder.

### Actual behaviour/实际行为

There is an error and the script exits.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

21e80a355e9d4a7a358d2c2905f6d3bf75e4681b refs/heads/main 21e80a355e9d4a7a358d2c2905f6d3bf75e4681b refs/remotes/origin/HEAD 21e80a355e9d4a7a358d2c2905f6d3bf75e4681b refs/remotes/origin/main 22bc69f732ee95db2061f4b7fefe8ff856a4d269 refs/remotes/origin/rebuild-ext4 d1b9489a9a4b3869d09101f358b7dfbf7d783de8 refs/remotes/origin/win-gui

### Linux distribution info/Linux 发行版信息

Ubuntu 22.04.3 LTS

### Windows version/Windows 版本

Edition	Windows 11 Pro Version	22H2 Installed on	‎27/‎11/‎2022 OS build	22621.2215 Experience	Windows Feature Experience Pack 1000.22662.1000.0

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol none --gapps-brand MindTheGapps --remove-amazon
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: none
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Mount images
fuse.erofs 1.6-g689372cd
disk: /tmp/wsa-build-FtxGPFwz6z_/wsa/x64/system.img
offset: 0
mountpoint: /tmp/wsa-build-FtxGPFwz6z_/erofs
dbglevel: 0
<E> erofs: cannot find valid erofs superblock
failed to read erofs super block
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Mount Directory
umount: /tmp/wsa-build-FtxGPFwz6z_/erofs/vendor: no mount point specified.
umount: /tmp/wsa-build-FtxGPFwz6z_/erofs/system_ext: no mount point specified.
umount: /tmp/wsa-build-FtxGPFwz6z_/erofs/product: no mount point specified.
umount: /tmp/wsa-build-FtxGPFwz6z_/erofs: not mounted.
umount: /tmp/wsa-build-FtxGPFwz6z_/system_root_merged/vendor: no mount point specified.
umount: /tmp/wsa-build-FtxGPFwz6z_/system_root_merged/system_ext: no mount point specified.
umount: /tmp/wsa-build-FtxGPFwz6z_/system_root_merged/product: no mount point specified.
umount: /tmp/wsa-build-FtxGPFwz6z_/system_root_merged: no mount point specified.
Cleanup Download Directory
❯ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy```
[//]: <> (Don't modify below)
</details>

**Comment by ajb3932** [comment]
Sorry to trouble you guys, you have done some amazing work.
I think I have seen this in #661  but I tried the fix and changed 2206 with 2207 in the build.sh and it still failed.

**Comment by Erisa** [comment]
Seems to be resolved by #665

**Comment by themachineworks** [comment]
I am getting the same error. Has the change been merged?

**Comment by chadify** [comment]
> I am getting the same error. Has the change been merged?
> 
> Mount images fuse.erofs 1.6-g689372cd disk: /tmp/wsa-build-msUIf2gjGp_/wsa/x64/system.img offset: 0 mountpoint: /tmp/wsa-build-msUIf2gjGp_/erofs dbglevel: 0 erofs: cannot find valid erofs superblock failed to read erofs super block Build: an error has occurred, exit

I'm getting the same error. How to fix?

**Comment by Erisa** [comment]
It's not merged. You need to use their fork
Try cloning this repo instead: https://github.com/sn-o-w/MagiskOnWSALocal

**Comment by chadify** [comment]
> It's not merged. You need to use their fork Try cloning this repo instead: https://github.com/sn-o-w/MagiskOnWSALocal

Done and it worked. I've a side question, is it possible to install only magisk and not the gapps, not even gapps pico.

**Comment by mgfirewater** [comment]
> It's not merged. You need to use their fork Try cloning this repo instead: https://github.com/sn-o-w/MagiskOnWSALocal
that doesn't work for me. my successful solution was that.
https://github.com/LSPosed/MagiskOnWSALocal/issues/648#issuecomment-1666931560

**Comment by ajb3932** [comment]
Worked for me, thanks to the fork owner! 🙌

Alex

-------- Original Message --------

**Comment by themachineworks** [comment]
Worked for me.

**Comment by novaflame1** [comment]
got the same error tbh

**Comment by novaflame1** [comment]
got the same error tbh

**Comment by mark-reijerkerk** [comment]
I acknowledge above solution from sn-o-w
