### ISSUE TITLE
[Feature Request] An app for auto-build and update the WSA.

### ISSUE THREAD

**Issue by shawny43** [LSPosed/MagiskOnWSALocal#681]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

This could being useful if MOWSA could bring Android Updates right in the box with an app or natively with Windows.

### Describe the solution you'd like/描述你想要的解决方案

Create an app that update the WSA and all others things like Gapps and Magisk right in the box with an help of a app. The app could download, build and automate the installation.

I guess if Arch linux can automate the git pacman installation, maybe you can do the same with an app that act the same. Just in smarter way. I know there Winget and Chocolately that could help a bit, but they include mostly already built apps. 

Pacman is a package manager made for any Arch Distro from Linux that can download, build and install apps in one command that automate the process withtout the needs to others tools. I guess this could handle a lot of users and help most users.

**Comment by YT-Advanced** [comment]
For Auto Build, you should take a look with my project:
https://github.com/YT-Advanced/WSA-Script

**Comment by shawny43** [comment]
The problem is that relay to GitHub and it's violate tos. Maybe a better tool could be better like pacman from Arch for example.

**Comment by YT-Advanced** [comment]
> The problem is that relay to GitHub and it's violate tos. Maybe a better tool could be better like pacman from Arch for example.

I know but the repos have worked for a year without any problem. I think because I have used skme bypass like instead fork and build Custom Build (which can make my repos got blocked by Github), I use Github Issues :)))
