### ISSUE TITLE
[Bug] Short description.

### ISSUE THREAD

**Issue by Hexality** [LSPosed/MagiskOnWSALocal#683]
### Steps to reproduce/复现步骤

1. Compile WSA
2. Install it
3. Install some app that can handle certain URIs (Ex.: MiX File Manager)

### Expected behaviour/预期行为

Open with the default system software (Ex.: Access files on a mobile phone plugged through usb)

### Actual behaviour/实际行为

https://github.com/LSPosed/MagiskOnWSALocal/assets/17398632/2ff9c865-7780-402b-86af-51170f5b133a

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

21e80a355e9d4a7a358d2c2905f6d3bf75e4681b

### Linux distribution info/Linux 发行版信息

Bedrock Linux (Ubuntu Restricted Stratum)

### Windows version/Windows 版本

10.0.22621.2134

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type RP --root-sol kernelsu --gapps-brand MindTheGapps --remove-amazon
INFO: Architecture: x64
INFO: Release Type: RP
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: kernelsu
Build: RELEASE_TYPE=Release Preview

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

https://github.com/LSPosed/MagiskOnWSALocal/assets/17398632/2ff9c865-7780-402b-86af-51170f5b133a

[//]: <> (Don't modify below)
</details>

**Comment by Hexality** [comment]
!reopen

**Comment by jovanzers** [comment]
[#325](https://github.com/microsoft/WSA/issues/325)

**Comment by Hexality** [comment]
> [#325](https://github.com/microsoft/WSA/issues/325)

I wish it was happening only with mtp devices, sadly that's not the case.
literally happening to every single app that does x type of action
browser - sets itself to whatever browser you have installed on wsa
files - sets whatever app you downloaded that can manage files as the default it for normal files like rar/zip
music - you get what I mean.

**Comment by jovanzers** [comment]
> I wish it was happening only with mtp devices, sadly that's not the case. literally happening to every single app that does x type of action browser - sets itself to whatever browser you have installed on wsa files - sets whatever app you downloaded that can manage files as the default it for normal files like rar/zip music - you get what I mean.

I suggest you to report the issue in their official repo so it can be fixed immediately

**Comment by Hexality** [comment]
the thing is that it only started happening with the version patched by
this script.

Em sex., 15 de dez. de 2023 às 15:12, Jovan Ferryal E. F. <
***@***.***> escreveu:

**Comment by jovanzers** [comment]
What makes you so sure this is due to the script?

**Comment by Hexality** [comment]
cause this doesn't happen on the normal wsa installed from the store, lol.

Em seg., 18 de dez. de 2023 às 15:28, Jovan Ferryal E. F. <
***@***.***> escreveu:

**Comment by jovanzers** [comment]
Well, seems like they already fixed it https://github.com/microsoft/WSA/issues/342

**Comment by Hexality** [comment]
I guess it didn't release on the main branch yet...

Em qua., 20 de dez. de 2023 às 19:27, Jovan Ferryal E. F. <
***@***.***> escreveu:
