### ISSUE TITLE
[Bug] LSPosed not showing after installed in magisk

### ISSUE THREAD

**Issue by IShiraiKurokoI** [LSPosed/MagiskOnWSALocal#687]
### Steps to reproduce/复现步骤

1. open magisk
2. copying LSPosed-v1.8.6-6712-zygisk-release.zip to downloads via wsahelper
3. select install from storage, choose zip file, install and reboot
4. nothing shows in magisk modules after reboot

### Expected behaviour/预期行为

lsposed show in start menu

### Actual behaviour/实际行为

nothing shows, no notification

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

21e80a355e9d4a7a358d2c2905f6d3bf75e4681b

### Linux distribution info/Linux 发行版信息

unbuntu 22.3 cloud server from digitalocean

### Windows version/Windows 版本

10.0.22621.2283

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --remove-amazon --root-sol magisk
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
- Copying zip to temp directory
- Installing LSPosed-v1.8.6-6712-zygisk-release.zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
***********************
 Zygisk - LSPosed 
 by LSPosed Developers 
***********************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh
*******************
 Powered by Magisk 
*******************
- LSPosed version v1.8.6 (6712)
- Extracting verify.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
   creating: META-INF/com/google/android/
  inflating: META-INF/com/google/android/update-binary.sha256
  inflating: META-INF/com/google/android/updater-script.sha256
  inflating: META-INF/com/google/android/update-binary
  inflating: META-INF/com/google/android/updater-script
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh.sha256
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh.sha256
- Verified META-INF/com/google/android/update-binary
- Verified customize.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: util_functions.sh
- Verified verify.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: util_functions.sh.sha256
- Verified util_functions.sh
- Android SDK version: 33
- Magisk version: 26300
- Installing from Magisk app
- Device platform: x64
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop.sha256
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: post-fs-data.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: post-fs-data.sh.sha256
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: service.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: service.sh.sha256
- Verified module.prop
- Verified post-fs-data.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: uninstall.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: uninstall.sh.sha256
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: framework/lspd.dex
- Verified service.sh
- Verified uninstall.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: framework/lspd.dex.sha256
- Verified framework/lspd.dex
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: daemon.apk
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: daemon.apk.sha256
- Verified daemon.apk
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: daemon
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: daemon.sha256
- Verified daemon
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: manager.apk
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: manager.apk.sha256
- Verified manager.apk
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: liblspd.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: liblspd.so.sha256
- Verified lib/x86/liblspd.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: liblspd.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: liblspd.so.sha256
- Verified lib/x86_64/liblspd.so
- Extracting dex2oat binaries
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: dex2oat
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: dex2oat.sha256
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: dex2oat
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: dex2oat.sha256
- Verified bin/x86/dex2oat
- Verified bin/x86_64/dex2oat
- Patching binaries
- Welcome to LSPosed!
- Done

```
[//]: <> (Don't modify below)
</details>

**Comment by SerujiShard** [comment]
It's happening the same to me

**Comment by abdullahO2** [comment]
same here

**Comment by streamform** [comment]
same

**Comment by beilove** [comment]
有人有解决办法吗

**Comment by meowcatluke** [comment]
same

**Comment by RingingVolcano** [comment]
same

**Comment by wuyu8512** [comment]
https://github.com/MustardChef/WSABuilds/issues/154

There is a solution here

**Comment by RingingVolcano** [comment]
> [MustardChef/WSABuilds#154](https://github.com/MustardChef/WSABuilds/issues/154)
> 
> There is a solution here

I tried this , but it didn't work. The LSPosed still prompts that the required Magisk module is not installed.
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/72140353/df192727-e40d-41ea-b86a-55ca66931115)

**Comment by BlueSkyXN** [comment]
Same more

**Comment by FeyXieXzf** [comment]
same here

**Comment by IShiraiKurokoI** [comment]
I know what the problem is!
https://github.com/MustardChef/WSABuilds/issues/154
the solution did work, but you need to install exactly the LSPosed-v1.8.6-6712 version
https://github.com/LSPosed/LSPosed/releases/tag/v1.8.6
and follow the guide ,it worked.
![dc1465c49469dee864f0eb6951d59c4a](https://github.com/LSPosed/MagiskOnWSALocal/assets/73374735/ce247cc0-9b90-43c9-8a42-cfdf5b9355ee)

> > [MustardChef/WSABuilds#154](https://github.com/MustardChef/WSABuilds/issues/154)
> > There is a solution here
> 
> I tried this , but it didn't work. The LSPosed still prompts that the required Magisk module is not installed. ![image](https://private-user-images.githubusercontent.com/72140353/277309985-df192727-e40d-41ea-b86a-55ca66931115.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTI3NzYsIm5iZiI6MTcwNjk1MjQ3NiwicGF0aCI6Ii83MjE0MDM1My8yNzczMDk5ODUtZGYxOTI3MjctZTQwZC00MWVhLWI4NmEtNTVjYTY2OTMxMTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDA5Mjc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkODlmOGY0NmJjYjFlOTcyZWMzZjM4MzBmNGQ5ZTQzZmZhOTZhNjQwNjZkODZiYWFhYzZhNWQxZGI5MzdmZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9xxiX5z4nze2jjYjAuCbAzeVzMKbOFJc7Xfg2cvTUqI)
