### ISSUE TITLE
[Bug] if Root WSA using kernelsu it will throw an error.

### ISSUE THREAD

**Issue by SteveZMTstudios** [LSPosed/MagiskOnWSALocal#689]
### Steps to reproduce/复现步骤

1. run ./run.sh
2. select root by kernelsu
3. press space key to select
4. next along the way...

### Expected behaviour/预期行为

it downloaded all packs that it in need and build it successfully.

### Actual behaviour/实际行为

it reported an error.
` Generating KernelSU download link: arch=x86_64, kernel version=5.15.104.1

Error: No KernelSU release found for arch=x86_64, kernel version=5.15.104.1

Build: an error has occurred, exit `

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

21e80a3

### Linux distribution info/Linux 发行版信息

seewo@LAUNCH-JEFFDEAN
 OS: Ubuntu 22.04 jammy
 Kernel: x86_64 Linux 5.15.90.1-microsoft-standard-WSL2
 Uptime: 1h 49m
 Packages: 526
 Shell: bash 5.1.16
 Resolution: No X Server
 WM: Not Found
 GTK Theme:  [GTK3]
 Disk: 188G / 1.3T (15%)
 CPU: Intel Core i5-8400 @ 6x 2.808GHz

 RAM: 705MiB / 3834MiB

### Windows version/Windows 版本

Windows 11 22H2 22621.2359

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol kernelsu --gapps-brand none --remove-amazon --compress --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: none
INFO: GApps Variant: pico
INFO: Root Solution: kernelsu
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

WSA Build Version=2307.40000.6.0

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Generating KernelSU download link: arch=x86_64, kernel version=5.15.104.1
Error: No KernelSU release found for arch=x86_64, kernel version=5.15.104.1
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Download Directory
```
[//]: <> (Don't modify below)
</details>

**Comment by Doddddd** [comment]
https://github.com/tiann/KernelSU/commit/25592a0614d56d83ccd1b36623d2febead7902d4
kernelsu 现在只提供5.15.104.2，可以手动修改[这一行](https://github.com/LSPosed/MagiskOnWSALocal/blob/21e80a355e9d4a7a358d2c2905f6d3bf75e4681b/scripts/build.sh#L487)，或者构建不带kernelsu 的版本，根据[教程](https://github.com/LSPosed/MagiskOnWSALocal/blob/main/docs/KernelSU.md)手动添加

**Comment by SteveZMTstudios** [comment]
> https://github.com/tiann/KernelSU/commit/25592a0614d56d83ccd1b36623d2febead7902d4
> kernelsu 现在只提供5.15.104.2，可以手动修改[这一行](https://github.com/LSPosed/MagiskOnWSALocal/blob/21e80a355e9d4a7a358d2c2905f6d3bf75e4681b/scripts/build.sh#L487)，或者构建不带kernelsu 的版本，根据[教程](https://github.com/LSPosed/MagiskOnWSALocal/blob/main/docs/KernelSU.md)手动添加

非常感谢。我并未关注关于贵项目的更新，因此未能发现这个问题。
