### ISSUE TITLE
[Bug] No output folder

### ISSUE THREAD

**Issue by bdsmcoppack** [LSPosed/MagiskOnWSALocal#697]
### Steps to reproduce/复现步骤

Followed these instructions, but no output folder appears. Have tried repeating several times now to no avail. https://www.androidauthority.com/how-to-install-google-play-store-on-windows-11-3049609/

### Expected behaviour/预期行为

run.sh creates a folder called 'output' that contains the files that need to be copied over to Windows

### Actual behaviour/实际行为

There is no output folder after running run.sh.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

WSA Build Version=2307.40000.6.0

### Linux distribution info/Linux 发行版信息

Ubuntu on Windows using the Windows Subsystem for Linux (WSL)

### Windows version/Windows 版本

Windows 11 Home

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol none --gapps-brand MindTheGapps --remove-amazon --compress --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: none
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
COMMAND_LINE=--arch x64 --release-type retail --root-sol none --gapps-brand MindTheGapps --remove-amazon --compress --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: none
INFO: Compress Format: 7z
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

WSA Build Version=2307.40000.6.0

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/28edaebf-8019-4844-ba32-8ab019bc9391?P1=1695986042&P2=404&P3=2&P4=bkAhl%2fXvGqzLJT%2bWNFVZowwSVBBTlmxjjBeXTh5arAtrzmvOlIwWNsePPeS1Re4CqbECHXk5m3X1Y0%2btj4oAMw%3d%3d
path: ../download/Microsoft.VCLibs.140.00_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/21a6f30d-0ec0-46da-92cf-04e35cf18efc?P1=1695986104&P2=404&P3=2&P4=RmYXF8EYsawC3vYjz7x8%2fFOhUBMuB7qhwAceSiROmfbvEaa9jW%2bu9yfZ%2fhC8sTvF7n8i4PSJ8JhHcirf4Esfzg%3d%3d
path: ../download/Microsoft.UI.Xaml.2.8_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/986a8270-404c-4470-871d-5c4090dcaa79?P1=1695986149&P2=404&P3=2&P4=ltvi0FGDLOmZYhA3rJW%2brtd7SNmAZKqJDK%2fgKgRbLufqlaQc6IKqFZx%2fMKxosCErsxqrouoFkl3cNn5R1Fssfw%3d%3d
path: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/942f0742-0abf-4bba-891a-8be452488f3e?P1=1696013887&P2=404&P3=2&P4=af4K9Wq2tp9ugLojAw89t%2bFwOp1%2fOBbPjiqTfACM1Duj0iyLSwVukmQH0bkMDO%2b4pEME0tmhrBIAIRvHCcs%2foA%3d%3d
path: ../download/wsa-retail.zip

Generating Magisk download link: release type=stable
download link: https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@26.3/app-release.apk
Generating MindTheGapps download link: arch=x64 variant=pico
download link: https://downloads.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip
Download Artifacts

09/29 12:04:27 [NOTICE] Downloading 6 item(s)
[DL:4.2MiB][#43e380 800KiB/872KiB(91%)][#2423be 640KiB/4.8MiB(12%)][#0e0d9f 864KiB/6.4MiB(13%)][#e0489e 4.4MiB/1.3GiB(0
09/29 12:04:29 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00_x64.appx
[DL:4.8MiB][#2423be 1.5MiB/4.8MiB(31%)][#0e0d9f 2.0MiB/6.4MiB(32%)][#e0489e 21MiB/1.3GiB(1%)][#883df8 1.1MiB/11MiB(9%)]
09/29 12:04:34 [NOTICE] CUID#51 - Redirecting to https://deac-ams.dl.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip
[DL:4.9MiB][#2423be 1.9MiB/4.8MiB(40%)][#0e0d9f 2.5MiB/6.4MiB(40%)][#e0489e 31MiB/1.3GiB(2%)][#883df8 1.4MiB/11MiB(12%)
09/29 12:04:36 [NOTICE] CUID#53 - Redirecting to https://deac-ams.dl.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip
[DL:4.8MiB][#2423be 2.3MiB/4.8MiB(47%)][#0e0d9f 3.0MiB/6.4MiB(47%)][#e0489e 39MiB/1.3GiB(2%)][#883df8 1.7MiB/11MiB(14%)
09/29 12:04:38 [NOTICE] CUID#57 - Redirecting to https://deac-riga.dl.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip
[DL:5.0MiB][#2423be 2.7MiB/4.8MiB(55%)][#0e0d9f 3.5MiB/6.4MiB(54%)][#e0489e 48MiB/1.3GiB(3%)][#883df8 2.0MiB/11MiB(16%)
09/29 12:04:40 [NOTICE] CUID#55 - Redirecting to https://deac-riga.dl.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip
[DL:4.9MiB][#2423be 2.9MiB/4.8MiB(59%)][#0e0d9f 3.7MiB/6.4MiB(58%)][#e0489e 52MiB/1.3GiB(3%)][#883df8 2.1MiB/11MiB(18%)
09/29 12:04:40 [NOTICE] CUID#57 - Redirecting to https://downloads.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip?download&failedmirror=deac-riga.dl.sourceforge.net

09/29 12:04:40 [NOTICE] CUID#55 - Redirecting to https://downloads.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip?download&failedmirror=deac-riga.dl.sourceforge.net
[DL:4.9MiB][#2423be 3.3MiB/4.8MiB(67%)][#0e0d9f 4.1MiB/6.4MiB(64%)][#e0489e 61MiB/1.3GiB(4%)][#883df8 2.4MiB/11MiB(20%)
09/29 12:04:42 [NOTICE] CUID#59 - Redirecting to https://deac-riga.dl.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip

09/29 12:04:43 [NOTICE] CUID#59 - Redirecting to https://downloads.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip?download&failedmirror=deac-riga.dl.sourceforge.net
[DL:4.9MiB][#2423be 3.5MiB/4.8MiB(71%)][#0e0d9f 4.3MiB/6.4MiB(67%)][#e0489e 65MiB/1.3GiB(4%)][#883df8 2.6MiB/11MiB(22%)
09/29 12:04:44 [NOTICE] CUID#54 - Redirecting to https://altushost-swe.dl.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip
[DL:3.2MiB][#2423be 3.6MiB/4.8MiB(74%)][#0e0d9f 4.4MiB/6.4MiB(69%)][#e0489e 68MiB/1.3GiB(4%)][#883df8 2.8MiB/11MiB(23%)
09/29 12:04:47 [NOTICE] CUID#56 - Redirecting to https://netix.dl.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip

09/29 12:04:47 [NOTICE] Download complete: ../download/Microsoft.UI.Xaml.2.8_x64.appx

09/29 12:04:48 [NOTICE] CUID#58 - Redirecting to https://altushost-swe.dl.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip
[DL:4.6MiB][#0e0d9f 5.5MiB/6.4MiB(86%)][#e0489e 88MiB/1.3GiB(6%)][#883df8 3.6MiB/11MiB(30%)][#b08fdf 624KiB/188MiB(0%)]
09/29 12:04:50 [NOTICE] CUID#57 - Redirecting to https://deac-fra.dl.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip
[DL:4.6MiB][#0e0d9f 6.0MiB/6.4MiB(94%)][#e0489e 96MiB/1.3GiB(6%)][#883df8 4.0MiB/11MiB(34%)][#b08fdf 880KiB/188MiB(0%)]
09/29 12:04:52 [NOTICE] CUID#55 - Redirecting to https://nav.dl.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip
[DL:4.4MiB][#0e0d9f 6.2MiB/6.4MiB(96%)][#e0489e 99MiB/1.3GiB(7%)][#883df8 4.2MiB/11MiB(35%)][#b08fdf 0.9MiB/188MiB(0%)]
09/29 12:04:53 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
[DL:4.5MiB][#e0489e 104MiB/1.3GiB(7%)][#883df8 4.4MiB/11MiB(37%)][#b08fdf 1.1MiB/188MiB(0%)]
09/29 12:04:54 [NOTICE] CUID#59 - Redirecting to https://altushost-swe.dl.sourceforge.net/project/wsa-mtg/x86_64/20230920/MindTheGapps-13.0.0-x86_64-20230920.zip
 *** Download Progress Summary as of Fri Sep 29 12:05:28 2023 ***
=======================================================================================================================
[#e0489e 257MiB/1.3GiB(18%) CN:16 DL:4.8MiB ETA:3m55s]
FILE: ../download/wsa-retail.zip
-----------------------------------------------------------------------------------------------------------------------
[#883df8 11MiB/11MiB(96%) CN:1 DL:271KiB ETA:1s]
FILE: ../download/magisk-stable.zip
-----------------------------------------------------------------------------------------------------------------------
[#b08fdf 6.1MiB/188MiB(3%) CN:8 DL:182KiB ETA:17m1s]
FILE: ../download/MindTheGapps-x64-13.0.zip
-----------------------------------------------------------------------------------------------------------------------

[DL:5.2MiB][#e0489e 262MiB/1.3GiB(18%)][#883df8 11MiB/11MiB(98%)][#b08fdf 6.3MiB/188MiB(3%)]
09/29 12:05:29 [NOTICE] Download complete: ../download/magisk-stable.zip
 *** Download Progress Summary as of Fri Sep 29 12:06:28 2023 ***
=======================================================================================================================
[#e0489e 559MiB/1.3GiB(40%) CN:16 DL:5.0MiB ETA:2m43s]
FILE: ../download/wsa-retail.zip
-----------------------------------------------------------------------------------------------------------------------
[#b08fdf 18MiB/188MiB(9%) CN:8 DL:179KiB ETA:16m10s]
FILE: ../download/MindTheGapps-x64-13.0.zip
-----------------------------------------------------------------------------------------------------------------------

 *** Download Progress Summary as of Fri Sep 29 12:07:29 2023 ***
=======================================================================================================================
[#e0489e 859MiB/1.3GiB(61%) CN:16 DL:4.4MiB ETA:2m]
FILE: ../download/wsa-retail.zip
-----------------------------------------------------------------------------------------------------------------------
[#b08fdf 30MiB/188MiB(15%) CN:8 DL:198KiB ETA:13m39s]
FILE: ../download/MindTheGapps-x64-13.0.zip
-----------------------------------------------------------------------------------------------------------------------

 *** Download Progress Summary as of Fri Sep 29 12:08:29 2023 ***
=======================================================================================================================
[#e0489e 1.1GiB/1.3GiB(83%) CN:15 DL:4.6MiB ETA:50s]
FILE: ../download/wsa-retail.zip
-----------------------------------------------------------------------------------------------------------------------
[#b08fdf 42MiB/188MiB(22%) CN:8 DL:210KiB ETA:11m52s]
FILE: ../download/MindTheGapps-x64-13.0.zip
-----------------------------------------------------------------------------------------------------------------------

[DL:4.9MiB][#e0489e 1.3GiB/1.3GiB(99%)][#b08fdf 78MiB/188MiB(41%)]
09/29 12:09:25 [NOTICE] Download complete: ../download/wsa-retail.zip
 *** Download Progress Summary as of Fri Sep 29 12:09:30 2023 ***
=======================================================================================================================
[#b08fdf 102MiB/188MiB(54%) CN:8 DL:3.9MiB ETA:22s]
FILE: ../download/MindTheGapps-x64-13.0.zip
-----------------------------------------------------------------------------------------------------------------------

[#b08fdf 188MiB/188MiB(99%) CN:1 DL:2.4MiB]
09/29 12:09:52 [NOTICE] Download complete: ../download/MindTheGapps-x64-13.0.zip

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
43e380|OK  |   446KiB/s|../download/Microsoft.VCLibs.140.00_x64.appx
2423be|OK  |   246KiB/s|../download/Microsoft.UI.Xaml.2.8_x64.appx
0e0d9f|OK  |   258KiB/s|../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
883df8|OK  |   196KiB/s|../download/magisk-stable.zip
e0489e|OK  |   4.6MiB/s|../download/wsa-retail.zip
b08fdf|OK  |   608KiB/s|../download/MindTheGapps-x64-13.0.zip

Status Legend:
(OK):download completed.
Extract WSA
unzipping WsaPackage_2307.40000.6.0_x64_Release-Nightly.msix to /tmp/wsa-build-Qp07DUbZTk_/wsa
unzipping from /tmp/wsa-build-Qp07DUbZTk_/wsa/WsaPackage_2307.40000.6.0_x64_Release-Nightly.msix
Extract done

Extract Magisk
Magisk version: 26.3 (26300)
done

Extract MindTheGapps
Archive:  ../download/MindTheGapps-x64-13.0.zip
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/lib/libjni_latinimegoogle.so
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/overlay/GmsSettingsProviderOverlay.apk
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/overlay/GmsOverlay.apk
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/etc/security/fsverity/gms_fsverity_cert.der
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/etc/permissions/privapp-permissions-google-product.xml
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/etc/permissions/com.google.android.dialer.support.xml
 extracting: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/etc/init/gapps.rc
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/etc/default-permissions/default-permissions-mtg.xml
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/etc/default-permissions/default-permissions-google.xml
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/etc/sysconfig/google_build.xml
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/etc/sysconfig/google.xml
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/etc/sysconfig/d2d_cable_migration_feature.xml
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/etc/sysconfig/google-hiddenapi-package-allowlist.xml
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/lib64/libjni_latinimegoogle.so
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/app/GoogleCalendarSyncAdapter/GoogleCalendarSyncAdapter.apk

  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/app/PrebuiltExchange3Google/PrebuiltExchange3Google.apk
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk

  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/priv-app/AndroidAutoStub/AndroidAutoStub.apk
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/priv-app/GooglePartnerSetup/GooglePartnerSetup.apk
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/priv-app/Phonesky/Phonesky.apk
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/priv-app/GmsCore/GmsCore.apk
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/priv-app/Velvet/Velvet.apk
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/priv-app/GoogleRestore/GoogleRestore.apk
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/product/framework/com.google.android.dialer.support.jar
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/system_ext/etc/permissions/privapp-permissions-google-system-ext.xml
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/system_ext/priv-app/GoogleFeedback/GoogleFeedback.apk
  inflating: /tmp/wsa-build-Qp07DUbZTk_/gapps/system/system_ext/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk
Extract done

Convert vhdx to RAW image
Convert vhdx to RAW image done

Mount images
fuse.erofs 1.6-g689372cd
disk: /tmp/wsa-build-Qp07DUbZTk_/wsa/x64/system.img
offset: 0
mountpoint: /tmp/wsa-build-Qp07DUbZTk_/erofs
dbglevel: 0
<E> erofs: cannot find valid erofs superblock
failed to read erofs super block
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Mount Directory
umount: /tmp/wsa-build-Qp07DUbZTk_/erofs/vendor: no mount point specified.
umount: /tmp/wsa-build-Qp07DUbZTk_/erofs/system_ext: no mount point specified.
umount: /tmp/wsa-build-Qp07DUbZTk_/erofs/product: no mount point specified.
umount: /tmp/wsa-build-Qp07DUbZTk_/erofs: not mounted.
umount: /tmp/wsa-build-Qp07DUbZTk_/system_root_merged/vendor: no mount point specified.
umount: /tmp/wsa-build-Qp07DUbZTk_/system_root_merged/system_ext: no mount point specified.
umount: /tmp/wsa-build-Qp07DUbZTk_/system_root_merged/product: no mount point specified.
umount: /tmp/wsa-build-Qp07DUbZTk_/system_root_merged: no mount point specified.
Cleanup Download Directory
simon@TABLET-6UQ8E9AU:~/MagiskOnWSALocal/scripts$ ls
build.sh          fixGappsProp.py          generateMagiskLink.py  install_deps.sh
extractMagisk.py  generateGappsLink.py     generateWSALinks.py    requirements.txt
extractWSA.py     generateKernelSULink.py  getWSAMajorVersion.py  run.sh
simon@TABLET-6UQ8E9AU:~/MagiskOnWSALocal/scripts$ cd ..
simon@TABLET-6UQ8E9AU:~/MagiskOnWSALocal$ ls
LICENSE  arm64  bin  docs  download  installer  linker  scripts  x64  xml
```
[//]: <> (Don't modify below)
</details>

**Comment by cjshrader** [comment]
Hey @sn-o-w,

I just deleted the LSPosed clone and cloned your repository instead. It did not resolve the issue, are there some files I need to clean up somewhere?

**Comment by cjshrader** [comment]
> What error are you getting now? 🤔

Same as the original poster. There is no output directory created. I do see this when the script completes:

```
Mount images
mount: /tmp/wsa-build-2Wcby0JW8V_/system_root_merged: mount failed: Operation not permitted.
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Mount Directory
umount: /tmp/wsa-build-2Wcby0JW8V_/erofs/product: no mount point specified.
umount: /tmp/wsa-build-2Wcby0JW8V_/erofs/vendor: no mount point specified.
umount: /tmp/wsa-build-2Wcby0JW8V_/erofs/system_ext: no mount point specified.
umount: /tmp/wsa-build-2Wcby0JW8V_/erofs: no mount point specified.
umount: /tmp/wsa-build-2Wcby0JW8V_/system_root_merged/product: no mount point specified.
umount: /tmp/wsa-build-2Wcby0JW8V_/system_root_merged/vendor: no mount point specified.
umount: /tmp/wsa-build-2Wcby0JW8V_/system_root_merged/system_ext: no mount point specified.
umount: /tmp/wsa-build-2Wcby0JW8V_/system_root_merged: not mounted.
Cleanup Download Directory
```

**Comment by cjshrader** [comment]
I did a complete `rm -rf` followed by `git clone https://github.com/sn-o-w/MagiskOnWSALocal.git`, would you be aware of any other files I need to remove?

Thank you for the help by the way.

**Comment by cjshrader** [comment]
Your comment that something was wrong with my machine made me suspicious, and I got a BSOD shortly after which confirmed it. 

I hadn't used WSL in some time and I was using an older version of Ubuntu. I installed the Windows store version which also had me enable virtualization (yet somehow the other Ubuntu was running?) and then cloned your repository and I now get no errors and see an output file. Thank you for your help.

**Comment by JohnRo79** [comment]
hi

i've followed your step by step guide and it seems i'm getting [some errors](https://prnt.sc/s0ZHYpGeMuiQ) half way through

**Comment by yeet-dot-org** [comment]
> hi
> 
> i've followed your step by step guide and it seems i'm getting [some errors](https://prnt.sc/s0ZHYpGeMuiQ) half way through
> 
> (dumb as a toothpick with this kind of language too)
> 
> NVM. the link from the above got it sorted, tyvm

i have the same error, how did you solve it?

**Comment by yeet-dot-org** [comment]
> > > hi
> > > i've followed your step by step guide and it seems i'm getting [some errors](https://prnt.sc/s0ZHYpGeMuiQ) half way through
> > > (dumb as a toothpick with this kind of language too)
> > > NVM. the link from the above got it sorted, tyvm
> > 
> > 
> > i have the same error, how did you solve it?
> 
> If you see same errors, delete all the contents within your build.sh file and replace them with this: https://raw.githubusercontent.com/sn-o-w/MagiskOnWSALocal/main/scripts/build.sh

is there a way to access linu fil-- nevermind i found i can access them though explorer.exe command, but now i got a different error: Checking and ensuring dependencies
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Reading package lists... Done
E: Release file for http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease is not valid yet (invalid for another 56min 38s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease is not valid yet (invalid for another 57min 5s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease is not valid yet (invalid for another 57min 50s). Updates for this repository will not be applied.
Dependencies: an error has occurred, exit
am i using a wrong version of ubuntu (im using 22.04.2), or should i delete the clone of the repo and start over?

**Comment by yeet-dot-org** [comment]
> > > > > hi
> > > > > i've followed your step by step guide and it seems i'm getting [some errors](https://prnt.sc/s0ZHYpGeMuiQ) half way through
> > > > > (dumb as a toothpick with this kind of language too)
> > > > > NVM. the link from the above got it sorted, tyvm
> > > > 
> > > > 
> > > > i have the same error, how did you solve it?
> > > 
> > > 
> > > If you see same errors, delete all the contents within your build.sh file and replace them with this: https://raw.githubusercontent.com/sn-o-w/MagiskOnWSALocal/main/scripts/build.sh
> > 
> > 
> > is there a way to access linu fil-- nevermind i found i can access them though explorer.exe command, but now i got a different error: Checking and ensuring dependencies Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB] Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB] Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB] Reading package lists... Done E: Release file for http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease is not valid yet (invalid for another 56min 38s). Updates for this repository will not be applied. E: Release file for http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease is not valid yet (invalid for another 57min 5s). Updates for this repository will not be applied. E: Release file for http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease is not valid yet (invalid for another 57min 50s). Updates for this repository will not be applied. Dependencies: an error has occurred, exit am i using a wrong version of ubuntu (im using 22.04.2), or should i delete the clone of the repo and start over?
> 
> Looks like something's wrong inside the OS, that version of Ubuntu should work fine.
> 
> Is the time set correctly within your machine? Do you have the correct time zone? 🤔
> 
> Run:
> 
> ```shell
> sudo hwclock --hctosys
> ```
> 
> And then retry to build.

i just tried it again without running that command and it seems to work as theres an output folder now. ill report on any other issues after i finish the install

**Comment by yeet-dot-org** [comment]
it wouldn't install any apps (gets stuck at pending) but after reopening the play store several times and lettings the play store update, it seems to work and install apps. however, clash of clans quits instantly after opening but that is a seperate issue.

**Comment by HironTez** [comment]
> > > > > hi
> > > > > i've followed your step by step guide and it seems i'm getting [some errors](https://prnt.sc/s0ZHYpGeMuiQ) half way through
> > > > > (dumb as a toothpick with this kind of language too)
> > > > > NVM. the link from the above got it sorted, tyvm
> > > > 
> > > > 
> > > > i have the same error, how did you solve it?
> > > 
> > > 
> > > If you see same errors, delete all the contents within your build.sh file and replace them with this: https://raw.githubusercontent.com/sn-o-w/MagiskOnWSALocal/main/scripts/build.sh
> > 
> > 
> > is there a way to access linu fil-- nevermind i found i can access them though explorer.exe command, but now i got a different error: Checking and ensuring dependencies Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB] Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB] Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB] Reading package lists... Done E: Release file for http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease is not valid yet (invalid for another 56min 38s). Updates for this repository will not be applied. E: Release file for http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease is not valid yet (invalid for another 57min 5s). Updates for this repository will not be applied. E: Release file for http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease is not valid yet (invalid for another 57min 50s). Updates for this repository will not be applied. Dependencies: an error has occurred, exit am i using a wrong version of ubuntu (im using 22.04.2), or should i delete the clone of the repo and start over?
> 
> Looks like something's wrong inside the OS, that version of Ubuntu should work fine.
> 
> Is the time set correctly within your machine? Do you have the correct time zone? 🤔
> 
> Run:
> 
> ```shell
> sudo hwclock --hctosys
> ```
> 
> And then retry to build.

This worked for me!

**Comment by alongcor1** [comment]
> Your build.sh file should have this content available here: https://raw.githubusercontent.com/sn-o-w/MagiskOnWSALocal/main/scripts/build.sh
> 
> Replace everything in your build.sh with the content in the above URL, then try building again.

I copied everything from that URL and edited the build.sh file with Notepad++ in Windows and ran the script again, and now I have an Output folder. Thanks!

**Comment by yeet-dot-org** [comment]
> I had exactly the same problem.
> 
> To fix it, as suggested, I copied everything from that URL and edited the build.sh file with Notepad++ in Windows and ran the script again, and now I have an Output folder.
> 
> I also had to move the WSA_ folder from the "Network" folder, and put it in C:\temp to be able to run the Run.bat file. I kept getting UNC path errors otherwise.

Any fix for clash of clans yet?
