### ISSUE TITLE
[Feature Request] : Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [LSPosed/MagiskOnWSALocal#727]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.

### Describe the solution you'd like/描述你想要的解决方案

![contributors](https://github.com/LSPosed/MagiskOnWSALocal/assets/147402107/411fb1a8-9fc3-443a-82ba-e67b4624972a)

**Comment by Kalyanimhala** [comment]
@Howard20181 Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by luckyzyx** [comment]
https://github.com/LSPosed/MagiskOnWSALocal/graphs/contributors
