### ISSUE TITLE
[Bug] constant IllegalStateException in google services causes high disk usage

### ISSUE THREAD

**Issue by Ulinsky** [LSPosed/MagiskOnWSALocal#739]
### Steps to reproduce/复现步骤

1. install WSA with GApps
2. have WSA running/continous resource usage
3. check AppData\Local\Packages\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\LocalState\diagnostics\logcat

### Expected behaviour/预期行为

There shouldn't be constant exceptions in google services

### Actual behaviour/实际行为

Theres constants logs in logcat folder about IllegalStateExceptions

This causes 1. huge log files over time, and 2. constant disk usage (7+ mb/s)

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

d44a77b

### Linux distribution info/Linux 发行版信息

Debian

### Windows version/Windows 版本

22H2 build 23580.1000

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico  --root-sol none
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: none
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

11-11 13:49:36.017   804  1071 I SystemUpdate: [Execution,ExecutionManager] Action pending executed for 0.03 seconds.

11-11 13:49:36.026   804  1071 I SystemUpdate: [Execution,ExecutionManager] Action pre-download-validate executed for 0.00 seconds.

11-11 13:49:36.035   804  1071 W SystemUpdate: [Execution,ExecutionManager] Unable to create the action. Restart the execution from the scratch.

11-11 13:49:36.035   804  1071 W SystemUpdate: java.lang.IllegalStateException

11-11 13:49:36.035   804  1071 W SystemUpdate: 	at aixp.l(:com.google.android.gms@234414041@23.44.14 (190800-580326705):6)

11-11 13:49:36.035   804  1071 W SystemUpdate: 	at cyax.a(:com.google.android.gms@234414041@23.44.14 (190800-580326705):324)

11-11 13:49:36.035   804  1071 W SystemUpdate: 	at com.google.android.gms.update.execution.InstallationIntentOperation.onHandleIntent(:com.google.android.gms@234414041@23.44.14 (190800-580326705):120)

11-11 13:49:36.035   804  1071 W SystemUpdate: 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@234414041@23.44.14 (190800-580326705):2)

11-11 13:49:36.035   804  1071 W SystemUpdate: 	at agjm.onHandleIntent(:com.google.android.gms@234414041@23.44.14 (190800-580326705):10)

11-11 13:49:36.035   804  1071 W SystemUpdate: 	at noz.run(:com.google.android.gms@234414041@23.44.14 (190800-580326705):70)

11-11 13:49:36.035   804  1071 W SystemUpdate: 	at noy.run(:com.google.android.gms@234414041@23.44.14 (190800-580326705):152)

11-11 13:49:36.035   804  1071 W SystemUpdate: 	at dvlp.run(:com.google.android.gms@234414041@23.44.14 (190800-580326705):13)

11-11 13:49:36.035   804  1071 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)

11-11 13:49:36.035   804  1071 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)

11-11 13:49:36.035   804  1071 W SystemUpdate: 	at java.lang.Thread.run(Thread.java:1012)

[//]: <> (Don't modify below)
</details>

**Comment by tarasverq** [comment]
Same here.


```
12-30 03:01:31.958 I/SystemUpdate(  800): [Execution,ExecutionManager] Action pending executed for 0.03 seconds.
12-30 03:01:31.966 I/SystemUpdate(  800): [Execution,ExecutionManager] Action pre-download-validate executed for 0.00 seconds.
12-30 03:01:31.973 W/SystemUpdate(  800): [Execution,ExecutionManager] Unable to create the action. Restart the execution from the scratch.
12-30 03:01:31.973 W/SystemUpdate(  800): java.lang.IllegalStateException
12-30 03:01:31.973 W/SystemUpdate(  800): 	at ajmi.l(:com.google.android.gms@234816041@23.48.16 (190800-590025996):6)
12-30 03:01:31.973 W/SystemUpdate(  800): 	at dayc.a(:com.google.android.gms@234816041@23.48.16 (190800-590025996):324)
12-30 03:01:31.973 W/SystemUpdate(  800): 	at com.google.android.gms.update.execution.InstallationIntentOperation.onHandleIntent(:com.google.android.gms@234816041@23.48.16 (190800-590025996):122)
12-30 03:01:31.973 W/SystemUpdate(  800): 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@234816041@23.48.16 (190800-590025996):2)
12-30 03:01:31.973 W/SystemUpdate(  800): 	at agxt.onHandleIntent(:com.google.android.gms@234816041@23.48.16 (190800-590025996):10)
12-30 03:01:31.973 W/SystemUpdate(  800): 	at nze.run(:com.google.android.gms@234816041@23.48.16 (190800-590025996):70)
12-30 03:01:31.973 W/SystemUpdate(  800): 	at nzd.run(:com.google.android.gms@234816041@23.48.16 (190800-590025996):152)
12-30 03:01:31.973 W/SystemUpdate(  800): 	at dyui.run(:com.google.android.gms@234816041@23.48.16 (190800-590025996):13)
12-30 03:01:31.973 W/SystemUpdate(  800): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
12-30 03:01:31.973 W/SystemUpdate(  800): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
12-30 03:01:31.973 W/SystemUpdate(  800): 	at java.lang.Thread.run(Thread.java:1012)
```
