### ISSUE TITLE
List dependencies required

### ISSUE THREAD

**Issue by soda3x** [LSPosed/MagiskOnWSALocal#74]
I'm not sure if the run script is supposed to collect the dependencies or not, but on WSL it didn't for me so I ran the install script multiple times with it stopping and complaining about missing deps and me grabbing said deps and getting closer and closer to it working each time.

Could this be added to the script? In my case I needed to manually install wine, winetricks, lzip, aria2 and patchelf

**Comment by Howard20181** [comment]
In turn, it was added long ago.
https://github.com/LSPosed/MagiskOnWSALocal/blob/70bb0fdb8f7c9f5c47baee636309641302d480cc/scripts/run.sh#L52
https://github.com/LSPosed/MagiskOnWSALocal/blob/dca2264212fc25adb6f0a69445d484d62c7ed098/scripts/run.sh#L42-L46

**Comment by soda3x** [comment]
hmm odd, it certainly didn't install those

**Comment by Howard20181** [comment]
Maybe your system's package manager is not apt or the repository is old.
Other package managers were not supported before and are not officially supported now.
I'm not very familiar with package managers other than apt, so auto-install is disabled by default.
https://github.com/LSPosed/MagiskOnWSALocal/blob/dca2264212fc25adb6f0a69445d484d62c7ed098/scripts/run.sh#L50-L72

**Comment by soda3x** [comment]
WSL2 with Ubuntu, so using APT

**Comment by Howard20181** [comment]
Same as you, Ubuntu 20.04 and 22.04 are working fine
