### ISSUE TITLE
[Bug] No output generated due to error [sed: can't read /cts/a \ <feature name="android.software.device_admin" />: No such file or directory]

### ISSUE THREAD

**Issue by kdaek21** [LSPosed/MagiskOnWSALocal#740]
### Steps to reproduce/复现步骤

1. Download the latest version
2. Go to script folder and run ./run.sh
3. Select the desired option and proceed to create WSA

### Expected behaviour/预期行为

Each part of the WSA must be downloaded and the final file created in the output folder.

### Actual behaviour/实际行为

1. Download each part: OK
2. [sed: can't read /cts/a \ <feature name="android.software.device_admin" />: No such file or directory] error occurs in the middle.
3. At the end, the message [Build: an error has occurred, exit] is output along with the error [ERROR: Not yet implemented] and then it terminates.
4. There are files downloaded while working in the download folder, but no output is created due to an error.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

d44a77be84fac312d343ac501b497828209da089

### Linux distribution info/Linux 发行版信息

Debian

### Windows version/Windows 版本

10.0.22000.2538 (The same symptoms occur regardless of 21H2, 22H2, and 23H2.)

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --compress --magisk-ver stable --compress-format zip
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: zip
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --gapps-brand MindTheGapps --remove-amazon --compress --magisk-ver stable --compress-format zip
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
INFO: Compress Format: zip
Build: RELEASE_TYPE=Retail
Generate Download Links
Generating WSA download link: arch=x64 release_type=Retail

WSA Build Version=2309.40000.10.0

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/21a6f30d-0ec0-46da-92cf-04e35cf18efc?P1=1699884883&P2=404&P3=2&P4=DVMXPhLJHeJdwpXAmhthmFIJ7pNv6OFU5ljHBc6Mk8FuXtNpepYkGfiT7ghhEqqo7%2bwj7VZpwjORUvUeDcZYoQ%3d%3d
path: ../download/Microsoft.UI.Xaml.2.8_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/986a8270-404c-4470-871d-5c4090dcaa79?P1=1699884919&P2=404&P3=2&P4=AU8bTvZrvI%2fzivL2jHd1i7Dh10IH7EC%2fGIz8qwOpJ9SFjbRWrnptlL2y3jQepF%2b3AGX3tCFbBE4%2f5hTCwO6V6g%3d%3d
path: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/28edaebf-8019-4844-ba32-8ab019bc9391?P1=1699884856&P2=404&P3=2&P4=kd2LTS5xmmLTZ%2bdMOholoD3BXBXuKT4ddCoG7VDuBPuUHZ0mwec3gZ%2fkN%2fcajjtPdWR6QVta6tGjjubPcIm6lg%3d%3d
path: ../download/Microsoft.VCLibs.140.00_x64.appx

download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/865c8919-3247-45e3-95ee-323261875078?P1=1699912990&P2=404&P3=2&P4=fRzFATrcLNBepwF3ASIXFkolQu8vL2oR5%2f9Sp8bj4Jrjd7X1v1vyYh6DS2dDC6yHMgM4on8rtTGL6BMM8EhcWA%3d%3d
path: ../download/wsa-retail.zip

Generating Magisk download link: release type=stable
download link: https://cdn.jsdelivr.net/gh/topjohnwu/magisk-files@26.4/app-release.apk
Generating MindTheGapps download link: arch=x64 variant=pico
download link: https://downloads.sourceforge.net/project/wsa-mtg/x86_64/20231028/MindTheGapps-13.0.0-x86_64-20231028.zip
Download Artifacts

11/13 23:04:12 [NOTICE] Downloading 6 item(s)

11/13 23:04:12 [NOTICE] GID#d265cf546e005cb0 - Download has already completed: ../download/magisk-stable.zip

11/13 23:04:12 [NOTICE] Download complete: ../download/magisk-stable.zip

11/13 23:04:13 [NOTICE] GID#4198565739205d6d - Download has already completed: ../download/Microsoft.UI.Xaml.2.8_x64.appx

11/13 23:04:13 [NOTICE] GID#1d4ed6989cee8986 - Download has already completed: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

11/13 23:04:13 [NOTICE] GID#eb61fe64dc74dac7 - Download has already completed: ../download/Microsoft.VCLibs.140.00_x64.appx

11/13 23:04:13 [NOTICE] Download complete: ../download/Microsoft.UI.Xaml.2.8_x64.appx

11/13 23:04:13 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx

11/13 23:04:13 [NOTICE] Download complete: ../download/Microsoft.VCLibs.140.00_x64.appx

11/13 23:04:13 [NOTICE] GID#312b234df14df940 - Download has already completed: ../download/wsa-retail.zip

11/13 23:04:13 [NOTICE] Download complete: ../download/wsa-retail.zip

11/13 23:04:13 [NOTICE] CUID#12 - Redirecting to https://jaist.dl.sourceforge.net/project/wsa-mtg/x86_64/20231028/MindTheGapps-13.0.0-x86_64-20231028.zip
[#66f8a2 0B/0B CN:1 DL:0B]
11/13 23:04:14 [NOTICE] GID#66f8a22f103a6c70 - Download has already completed: ../download/MindTheGapps-x64-13.0.zip

11/13 23:04:14 [NOTICE] Download complete: ../download/MindTheGapps-x64-13.0.zip

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
d265cf|OK  |       0B/s|../download/magisk-stable.zip
419856|OK  |       0B/s|../download/Microsoft.UI.Xaml.2.8_x64.appx
1d4ed6|OK  |       0B/s|../download/Microsoft.VCLibs.140.00.UWPDesktop_x64.appx
eb61fe|OK  |       0B/s|../download/Microsoft.VCLibs.140.00_x64.appx
312b23|OK  |       0B/s|../download/wsa-retail.zip
66f8a2|OK  |       0B/s|../download/MindTheGapps-x64-13.0.zip

Status Legend:
(OK):download completed.
Extract WSA
unzipping WsaPackage_2309.40000.10.0_x64_Release-Nightly.msix to /tmp/wsa-build-mZhyPh91dQ_/wsa
unzipping from /tmp/wsa-build-mZhyPh91dQ_/wsa/WsaPackage_2309.40000.10.0_x64_Release-Nightly.msix
Extract done

Extract Magisk
Magisk version: 26.4 (26400)
done

Extract MindTheGapps
Archive:  ../download/MindTheGapps-x64-13.0.zip
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/system_ext/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/system_ext/priv-app/GoogleFeedback/GoogleFeedback.apk
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/system_ext/etc/permissions/privapp-permissions-google-system-ext.xml
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/priv-app/Velvet/Velvet.apk
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/priv-app/GooglePartnerSetup/GooglePartnerSetup.apk
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/priv-app/GmsCore/GmsCore.apk
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/priv-app/AndroidAutoStub/AndroidAutoStub.apk
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/priv-app/GoogleRestore/GoogleRestore.apk
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/priv-app/Phonesky/Phonesky.apk
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/framework/com.google.android.dialer.support.jar
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/lib/libjni_latinimegoogle.so
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/overlay/GmsSettingsProviderOverlay.apk
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/overlay/GmsOverlay.apk
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/etc/permissions/privapp-permissions-google-product.xml
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/etc/permissions/com.google.android.dialer.support.xml
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/etc/default-permissions/default-permissions-mtg.xml
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/etc/default-permissions/default-permissions-google.xml
 extracting: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/etc/init/gapps.rc
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/etc/security/fsverity/gms_fsverity_cert.der
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/etc/sysconfig/d2d_cable_migration_feature.xml
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/etc/sysconfig/google.xml
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/etc/sysconfig/google_build.xml
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/etc/sysconfig/google-hiddenapi-package-allowlist.xml
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/app/PrebuiltExchange3Google/PrebuiltExchange3Google.apk
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/app/GoogleCalendarSyncAdapter/GoogleCalendarSyncAdapter.apk
  inflating: /tmp/wsa-build-mZhyPh91dQ_/gapps/system/product/lib64/libjni_latinimegoogle.so
caution: excluded filename not matched:  system/product/priv-app/VelvetTitan/*
Extract done

Convert vhdx to RAW image
Convert vhdx to RAW image done

Mount images
mount: /dev/loop0 mounted on /tmp/wsa-build-mZhyPh91dQ_/erofs.
mount: /dev/loop1 mounted on /tmp/wsa-build-mZhyPh91dQ_/erofs/vendor.
mount: /dev/loop2 mounted on /tmp/wsa-build-mZhyPh91dQ_/erofs/product.
mount: /dev/loop3 mounted on /tmp/wsa-build-mZhyPh91dQ_/erofs/system_ext.
done

Create overlayfs
mk_overlayfs: label system
        lowerdir=/tmp/wsa-build-mZhyPh91dQ_/erofs
        upperdir=/tmp/wsa-build-mZhyPh91dQ_/upper/system
        workdir=/tmp/wsa-build-mZhyPh91dQ_/worker/system
        merged=/tmp/wsa-build-mZhyPh91dQ_/system_root_merged
mount: overlay mounted on /tmp/wsa-build-mZhyPh91dQ_/system_root_merged.
mk_overlayfs: label vendor
        lowerdir=/tmp/wsa-build-mZhyPh91dQ_/erofs/vendor
        upperdir=/tmp/wsa-build-mZhyPh91dQ_/upper/vendor
        workdir=/tmp/wsa-build-mZhyPh91dQ_/worker/vendor
        merged=/tmp/wsa-build-mZhyPh91dQ_/system_root_merged/vendor
mount: overlay mounted on /tmp/wsa-build-mZhyPh91dQ_/system_root_merged/vendor.
mk_overlayfs: label product
        lowerdir=/tmp/wsa-build-mZhyPh91dQ_/erofs/product
        upperdir=/tmp/wsa-build-mZhyPh91dQ_/upper/product
        workdir=/tmp/wsa-build-mZhyPh91dQ_/worker/product
        merged=/tmp/wsa-build-mZhyPh91dQ_/system_root_merged/product
mount: overlay mounted on /tmp/wsa-build-mZhyPh91dQ_/system_root_merged/product.
mk_overlayfs: label system_ext
        lowerdir=/tmp/wsa-build-mZhyPh91dQ_/erofs/system_ext
        upperdir=/tmp/wsa-build-mZhyPh91dQ_/upper/system_ext
        workdir=/tmp/wsa-build-mZhyPh91dQ_/worker/system_ext
        merged=/tmp/wsa-build-mZhyPh91dQ_/system_root_merged/system_ext
mount: overlay mounted on /tmp/wsa-build-mZhyPh91dQ_/system_root_merged/system_ext.
Create overlayfs done

Remove Amazon Appstore
done

Add device administration features
sed: can't read /cts/a \    <feature name="android.software.device_admin" />: No such file or directory
done

Integrate Magisk
/debug_ramdisk(/.*)?    u:object_r:magisk_file:s0
/data/adb/magisk(/.*)?   u:object_r:magisk_file:s0
Inject zygote restart /tmp/wsa-build-mZhyPh91dQ_/system_root_merged/system/etc/init/hw/init.zygote32.rc
awk: not an option: -i
Inject zygote restart /tmp/wsa-build-mZhyPh91dQ_/system_root_merged/system/etc/init/hw/init.zygote64.rc
awk: not an option: -i
Inject zygote restart /tmp/wsa-build-mZhyPh91dQ_/system_root_merged/system/etc/init/hw/init.zygote64_32.rc
awk: not an option: -i
Integrate Magisk done

Add extra packages
Add extra packages done

Integrate MindTheGapps
Integrate MindTheGapps done

Fix MindTheGapps prop
fixing /tmp/wsa-build-mZhyPh91dQ_/system_root_merged/system/build.prop
fixing /tmp/wsa-build-mZhyPh91dQ_/system_root_merged/vendor/build.prop
fixing /tmp/wsa-build-mZhyPh91dQ_/system_root_merged/vendor/odm/etc/build.prop
done

Create system images
mk_image_umount: /tmp/wsa-build-mZhyPh91dQ_/system_root_merged/vendor /tmp/wsa-build-mZhyPh91dQ_/wsa/x64/vendor.img /tmp/wsa-build-mZhyPh91dQ_/upper/vendor ext4
ERROR: Not yet implemented
Build: an error has occurred, exit

Cleanup Work Directory
Cleanup Mount Directory
umount: /tmp/wsa-build-mZhyPh91dQ_/erofs/vendor unmounted
umount: /tmp/wsa-build-mZhyPh91dQ_/erofs/system_ext unmounted
umount: /tmp/wsa-build-mZhyPh91dQ_/erofs/product unmounted
umount: /tmp/wsa-build-mZhyPh91dQ_/erofs unmounted
umount: /tmp/wsa-build-mZhyPh91dQ_/system_root_merged/vendor (overlay) unmounted
umount: /tmp/wsa-build-mZhyPh91dQ_/system_root_merged/system_ext (overlay) unmounted
umount: /tmp/wsa-build-mZhyPh91dQ_/system_root_merged/product (overlay) unmounted
umount: /tmp/wsa-build-mZhyPh91dQ_/system_root_merged (overlay) unmounted
deactivate python3 venv
Cleanup Download Directory

[//]: <> (Don't modify below)
</details>

**Comment by kdaek21** [comment]
There is a tag section in the log, but since it is a web site, it is cut off. Attach a file.
[log.txt](https://github.com/LSPosed/MagiskOnWSALocal/files/13335779/log.txt)

**Comment by barraIhsan** [comment]
+1 here, the same problem occurs for me

**Comment by barraIhsan** [comment]
Update: [#717 (comment](https://github.com/LSPosed/MagiskOnWSALocal/issues/717#issuecomment-1779576833), Try doing this.

**Comment by jesuscastilla** [comment]
+1

**Comment by shenshouer** [comment]
+1
