### ISSUE TITLE
[Bug] Magisk module doesn't work properly. Module columns are erased when rebooting.

### ISSUE THREAD

**Issue by Chamin-programmer** [LSPosed/MagiskOnWSALocal#741]
### Steps to reproduce/复现步骤

I myself do not speak Chinese and English, so I am sorry that I may not be able to communicate well as I am writing this in translated Japanese!

# Steps to reproduce

1.  Install as usual
I downloaded the build.sh file from an external source because I could not mount VHDX in the normal way.
2. Then start the custom wsa and launch magisk
Select the module.zip you want to add from the modules section, install it, and reboot.
3. If you open Magisk again after rebooting, you will see that it is not working properly

### Expected behaviour/预期行为

I don't know what to write here, so I'll just write why this bug (which may be a specification) occurs.

But first, I'd like to digress.
I was going to use Google Play VRChat on my handheld PC, so I built this repository, but the original image file is not designed for very high spec usage, and I guess it's because the device name is Pixel 5. But the original image file was not intended for very high spec use, and I was disappointed that there were many apps that were not supported even if I put in Google Play.

So I decided to add Magisk and try to forge a terminal with MagiskHidePropConf.
Naturally, it doesn't work because I'm throwing an issue.

## Why doesn't it work?
MagiskHidePropConf uses BusyBox
This BusyBox is quite a tricky one, and if you select Magisk on the first Root app screen, it will probably start without the BusyBox.
In the case of kernel SU, there is no problem because it is built-in, but in the case of Magisk, I guess that this is probably not the cause because it does not enter by ReadOnly even if I try to enter newly.

I installed MagiskHidePropConf with the BusyBox path changed in the kernel SU once again based on these events, and it started fine (well, PropConf itself is not updated, so I could not play the smartphone version of VRChat).

### Actual behaviour/实际行为

.I don't know what to write, so for now, I'm not going to write anything here.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

I don't know what to write, so for now, I'm not going to write anything here.

### Linux distribution info/Linux 发行版信息

DE used for build is Ubuntu 20 LTS with WSL

### Windows version/Windows 版本

Well, I tried it another way and it worked, so there's nothing to describe here for now.

### Build Parameters/构建参数

Bug Param=x64 release type retail Magisk gapps brand Mind The Gapps gapps variant pico root
No Bug=x64 release type retail KernelSU gapps brand Mind The Gapps gapps variant pico root

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
# Replace this line with the log / 将此行用日志替换
```
[//]: <> (Don't modify below)
</details>

**Comment by Burgerd4sh** [comment]
duplicate with https://github.com/LSPosed/MagiskOnWSALocal/issues/687#issue-1902113045

I had the same issue too. You can try the solution below. They works to me.
1、https://github.com/MustardChef/WSABuilds/issues/154
2、Using an older version of Magisk：https://github.com/MustardChef/WSABuilds/issues/154#issuecomment-1814726301
