### ISSUE TITLE
When running Run.bat, the installation process fails.

### ISSUE THREAD

**Issue by MisterSilvereagle** [LSPosed/MagiskOnWSALocal#744]
### Steps to reproduce/复现步骤

1. Generate output folder with script
2. Copy to Hard Drive
3. Run Run.bat
4. 
Additional info: I am using [this](https://github.com/sn-o-w/MagiskOnWSALocal) fix to make the build script working.
The output folder is renamed so that it is short enough. It is placed on another Drive than Windows is installed to.

### Expected behaviour/预期行为

I guess WSA should install and the play store should launch.

### Actual behaviour/实际行为

Some Powershell progress bars appear, and then a red error message appears. It states:
```
Start-Process : This command cannot be run due to the error: A specified logon session does not exist. It may have been terminated.
At D:\wsa_rooted_gapps_noamazon\Install.ps1:58 char:5
+    Start-Process "wsa://com.android.vending"
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Proces], InvalidOperationException
    + FullQualified ErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```
After the error message the script says All Done, press any key to exit. But it is obviously not done.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

d44a77be84fac312d343ac501b497828209da089

### Linux distribution info/Linux 发行版信息

Ubuntu 22.04 WSL

### Windows version/Windows 版本

10.0.22631.2715

### Build Parameters/构建参数

INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [x] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)
![WsaKomisch](https://github.com/LSPosed/MagiskOnWSALocal/assets/58659498/d8b7bbac-ccfe-4c06-9677-626c63c3867c)

[//]: <> (Don't modify below)
</details>

**Comment by AryanAD** [comment]
hey, did you fix it? If yes, how did you do it?
