### ISSUE TITLE
[Bug] Rejecting a request to register from AppxBundleManifest.xml because the manifest is not in the package root.

### ISSUE THREAD

**Issue by rebroad** [LSPosed/MagiskOnWSALocal#767]
### Steps to reproduce/复现步骤

I used the latest "fast" android subsystem, and used the patch to allow vdhx files to be used instead of img files. However, when running run.bat as administrator, it fails (details below).

### Expected behaviour/预期行为

It should install.

### Actual behaviour/实际行为

Installing MagiskOnWSA....
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9, Install failed. Please contact your software
vendor. (Exception from HRESULT: 0x80073CF9)
Rejecting a request to register from AppxBundleManifest.xml because the manifest is not in the package root.
NOTE: For additional information, look for [ActivityId] 6e4ab5ee-52b0-0000-4473-5f6eb052da01 in the Event
Log or use the command line Get-AppPackageLog -ActivityID 6e4ab5ee-52b0-0000-4473-5f6eb052da01
At C:\Users\rebroad\Downloads\WSA_2311.40000.5.0_x64_Release-Nightly-with-magisk-26.4(26400)-beta-MindTheGap
ps-13.0\Install.ps1:167 char:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\rebroa...ppxManifest.xml:String) [Add-AppxPackage], IOE
   xception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackage
   Command

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

d44a77be84fac312d343ac501b497828209da089

### Linux distribution info/Linux 发行版信息

Linux DESKTOP-6JP1QOV 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Windows version/Windows 版本

22H2 (Build 22621.3007)

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIF --root-sol magisk --gapps-brand MindTheGapps --magisk-ver beta
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: beta
INFO: GApps Brand: MindTheGapps
INFO: GApps Variant: pico
INFO: Root Solution: magisk
Build: RELEASE_TYPE=Insider Fast

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
Output in "actual behaviour" in this issue.
```
[//]: <> (Don't modify below)
</details>

**Comment by dongle-the-gadget** [comment]
This is because you have installed the Store version. Uninstall it before running `Run.bat`.
