### ISSUE TITLE
Cant run - run.sh

### ISSUE THREAD

**Issue by Worven** [LSPosed/MagiskOnWSALocal#77]
When try open run.sh it closes after 1-2 sec. How to Execute, start run.sh properly, or there errors in this file?

**Comment by Howard20181** [comment]
Submit error messages or screenshots.

**Comment by Worven** [comment]
There is no error messages, window closes momently

**Comment by Worven** [comment]
https://user-images.githubusercontent.com/112726310/188626839-b05c7c9a-ba8b-4b4c-9654-e4f7bcd0cc67.mp4
