### ISSUE TITLE
[Bug] in build script? cpio no such file or directory

### ISSUE THREAD

**Issue by cusco** [LSPosed/MagiskOnWSALocal#775]
### Steps to reproduce/复现步骤

bash -x ./scripts/build.sh --arch x64 --release-type retail --root-sol magisk --magisk-ver stable

...

Integrating Magisk
+ /tmp/wsa-build-Qsi4GEAdVr_/magisk/magiskboot compress=xz /tmp/wsa-build-Qsi4GEAdVr_/magisk/magisk64 /tmp/wsa-build-Qsi4GEAdVr_/magisk/magisk64.xz
+ /tmp/wsa-build-Qsi4GEAdVr_/magisk/magiskboot compress=xz /tmp/wsa-build-Qsi4GEAdVr_/magisk/magisk32 /tmp/wsa-build-Qsi4GEAdVr_/magisk/magisk32.xz
+ /tmp/wsa-build-Qsi4GEAdVr_/magisk/magiskboot compress=xz ../download/magisk-stable.zip /tmp/wsa-build-Qsi4GEAdVr_/magisk/stub.xz
+ /tmp/wsa-build-Qsi4GEAdVr_/magisk/magiskboot cpio /tmp/wsa-build-Qsi4GEAdVr_/wsa/x64/Tools/initrd.img 'mv /init /wsainit' 'add 0750 /lspinit ../bin/x64/lspinit' 'ln /lspinit /init' 'add 0750 /magiskinit /tmp/wsa-build-Qsi4GEAdVr_/magisk/magiskinit' 'mkdir 0750 overlay.d' 'mkdir 0750 overlay.d/sbin' 'add 0644 overlay.d/sbin/magisk64.xz /tmp/wsa-build-Qsi4GEAdVr_/magisk/magisk64.xz' 'add 0644 overlay.d/sbin/magisk32.xz /tmp/wsa-build-Qsi4GEAdVr_/magisk/magisk32.xz' 'add 0644 overlay.d/sbin/stub.xz /tmp/wsa-build-Qsi4GEAdVr_/magisk/stub.xz' 'mkdir 000 .backup' 'add 000 overlay.d/init.lsp.magisk.rc init.lsp.magisk.rc' 'add 000 overlay.d/sbin/post-fs-data.sh post-fs-data.sh'
Loading cpio: [/tmp/wsa-build-Qsi4GEAdVr_/wsa/x64/Tools/initrd.img]
Move [/init] -> [/wsainit]
No such file or directory (os error 2)
Failed to process cpio

...

### Expected behaviour/预期行为

should not produce this error

### Actual behaviour/实际行为

produces error

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

44df7ca8ac4a755d05abe11ba44d621414b2a537

### Linux distribution info/Linux 发行版信息

Debian on WSL2

### Windows version/Windows 版本

22H2 19045.3086

### Build Parameters/构建参数

bash -x ./scripts/build.sh --arch x64 --release-type retail --root-sol magisk --magisk-ver stable

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
# Replace this line with the log / 将此行用日志替换
```
[//]: <> (Don't modify below)
</details>

**Comment by s1204IT** [comment]
This has now been resolved with the latest commit.

41aec53b2c66fb32f903645afcd70c91e8e68885
