### ISSUE TITLE
[Bug] Cannot remove Amazon Appstore

### ISSUE THREAD

**Issue by s1204IT** [LSPosed/MagiskOnWSALocal#777]
### Steps to reproduce/复现步骤

Run the build.

### Expected behaviour/预期行为

Remove Amazon Appstore using the `--remove-amazon` option.

### Actual behaviour/实际行为

That functionality has now been removed.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

41aec53b2c66fb32f903645afcd70c91e8e68885

### Linux distribution info/Linux 发行版信息

Ubuntu-22.04

### Windows version/Windows 版本

10.0.22631.3155

### Build Parameters/构建参数

--release-type WIF --install-gapps

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

It's not a log, but it's a suggestion.  

Now that I know that I have integrated it using a new method using the Magisk module, how about deleting Amazon Appstore using the same method?

**Comment by Howard20181** [comment]
730070d44ab848fcd7a3e14d0a1753ac1df0e346
