### ISSUE TITLE
[Bug] ERROR: Invalid Compress Format: --compress-format

### ISSUE THREAD

**Issue by Doddddd** [LSPosed/MagiskOnWSALocal#779]
### Steps to reproduce/复现步骤

./build.sh --arch x64 --release-type WIF --root-sol kernelsu --compress --compress-format 7z

### Expected behaviour/预期行为

INFO: Compress Format: 7z

### Actual behaviour/实际行为

ERROR: Invalid Compress Format: --compress-format

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

8950e28a08028a58c248ff4f3ac43d16a54280a8

### Linux distribution info/Linux 发行版信息

Linux Surface 6.7.6-arch1-1-surface #1 SMP PREEMPT_DYNAMIC Tue, 27 Feb 2024 19:53:26 +0000 x86_64 GNU/Linux

### Windows version/Windows 版本

null

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type WIF --root-sol kernelsu --compress --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: stable
INFO: Root Solution: kernelsu
ERROR: Invalid Compress Format: --compress-format

Usage:
    --arch              Architecture of WSA.

                        Possible values: x64, arm64
                        Default: x64

    --release-type      Release type of WSA.
                        RP means Release Preview, WIS means Insider Slow, WIF means Insider Fast.

                        Possible values: retail, RP, WIS, WIF
                        Default: retail

    --magisk-ver        Magisk version.

                        Possible values: stable, beta, canary, debug, release
                        Default: stable

    --root-sol          Root solution.
                        "none" means no root.

                        Possible values: magisk, kernelsu, none
                        Default: magisk

    --compress-format   Compress format of output file.

                        Possible values: 7z, zip, none
                        Default: none

Additional Options:
    --offline           Build WSA offline
    --magisk-custom     Install custom Magisk
    --skip-download-wsa Skip download WSA
    --help              Show this help message and exit

Example:
    ./build.sh --release-type RP --magisk-ver beta
    ./build.sh --arch arm64 --release-type WIF
    ./build.sh --release-type WIS
    ./build.sh --offline --magisk-custom
    ./build.sh --release-type WIF --magisk-custom --magisk-ver release

[✘] ~/MagiskOnWSALocal/scripts > ./run.sh^C
[✘] ~/MagiskOnWSALocal/scripts > --arch x64 --release-type WIF --root-sol kernelsu --compress --compress-format 7z^C
[✘] ~/MagiskOnWSALocal/scripts > ./build.sh --arch x64 --release-type WIF --root-sol kernelsu --compress-format 7z
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: stable
INFO: Root Solution: kernelsu
INFO: Compress Format: 7z
INFO: Release Name: Insider Fast

Generating WSA Download Links
Generating WSA download link: arch=x64 release_type=Insider Fast

^CTraceback (most recent call last):
  File "/home/test/MagiskOnWSALocal/scripts/generateWSALinks.py", line 77, in <module>
    out = session.post(
          ^^^^^^^^^^^^^
  File "/home/test/MagiskOnWSALocal/python3-env/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/MagiskOnWSALocal/python3-env/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/MagiskOnWSALocal/python3-env/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/MagiskOnWSALocal/python3-env/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1383, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
Build: an error has occurred, exit

Cleanup Work Directory
deactivate python3 venv
Cleanup Download Directory

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
# Replace this line with the log / 将此行用日志替换
```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
f78b9ea33149c8d61fbe6778186647d6b31ce748
