### ISSUE TITLE
[Bug] MindtheGapps not installing

### ISSUE THREAD

**Issue by IncompatibleW** [LSPosed/MagiskOnWSALocal#788]
### Steps to reproduce/复现步骤

1. Run ./scripts/run.sh
2. Select x64
3. Select Retail
4. Select "no" for root
5. Select "yes" for remove amazon appstore
6. Do not compress output

### Expected behaviour/预期行为

Ouput should contain GApps without Magisk or Amazon Appstore

### Actual behaviour/实际行为

File generated is a nightly build (not retail as selected) with Magisk and no GApps.

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

https://github.com/LSPosed/MagiskOnWSALocal/commit/2726a6996feaee5fc06c9a5db9bd625bec077067

### Linux distribution info/Linux 发行版信息

Ubuntu WSL2

### Windows version/Windows 版本

Win 11 23H2 22631.3235

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --remove-amazon
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: Root Solution: magisk
INFO: Compress Format: none
INFO: Release Name: Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
![image](https://github.com/LSPosed/MagiskOnWSALocal/assets/20784222/7c64330b-f371-4f2c-a8fb-587b57d911a6)

```
[//]: <> (Don't modify below)
</details>

**Comment by s1204IT** [comment]
2726a69
