### ISSUE TITLE
wsalocal is not installed and instead gives a dependency error

### ISSUE THREAD

**Issue by yeet-dot-org** [LSPosed/MagiskOnWSALocal#798]
### Steps to reproduce/复现步骤

1. install WSAlocal using the included steps on the repo and run "sudo apt install python3.11-venv

### Expected behaviour/预期行为

google play store should be installed alongside WSA

### Actual behaviour/实际行为

wsalocal is not installed and instead gives a dependency error
( The operation completed successfully.
Installing MicrosoftCorporationII.WindowsSubsystemForAndroid version: 2311.40000.5.0
Dependency package Microsoft.UI.Xaml.2.8 x64 current version: 8.2310.30001.0. Nothing to do.
Dependency package Microsoft.VCLibs.140.00.UWPDesktop x64 current version: 14.0.33728.0. Nothing to do.
Dependency package Microsoft.VCLibs.140.00 x64 current version: 14.0.33519.0. Nothing to do.
Installing MagiskOnWSA....
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.
Windows cannot install package MicrosoftCorporationII.WindowsSubsystemForAndroid_2311.40000.5.0_x64__8wekyb3d8bbwe
because this package is not compatible with the device. The package requires OS version 10.0.22000.120 or higher on
the Windows.Desktop device family. The device is currently running OS version 10.0.19045.4412.
NOTE: For additional information, look for [ActivityId] cdeb32cd-b64a-0002-2adb-24ce4ab6da01 in the Event Log or use
the command line Get-AppPackageLog -ActivityID cdeb32cd-b64a-0002-2adb-24ce4ab6da01
At D:\DownolOAD\WSA_2311.40000.5.0_x64_Release-Nightly-with-magisk-27.0(27000)-stable-NoGApps-NoAmazon\Install.ps1:162
char:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (D:\DownolOAD\WS...ppxManifest.xml:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand )

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

‌2311.40000.5.0

### Linux distribution info/Linux 发行版信息

       _,met$$$$$gg.          android@DESKTOP-N75CACV
    ,g$$$$$$$$$$$$$$$P.       -----------------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) on Windows 10 x86_64
 ,$$P'              `$$$.     Kernel: 4.4.0-19041-Microsoft
',$$P       ,ggs.     `$$b:   Uptime: 25 mins
`d$$'     ,$P"'   .    $$$    Packages: 563 (dpkg)
 $$P      d$'     ,    $$P    Shell: bash 5.2.15
 $$:      $$.   -    ,d$$'    Terminal: /dev/tty1
 $$;      Y$b._   _,d$P'      CPU: AMD Ryzen 5 5500 (12) @ 3.600GHz
 Y$$.    `.`"Y$$$$P"'         Memory: 10027MiB / 16249MiB
 `$$b      "-.__
  `Y$$
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""

### Windows version/Windows 版本

10.0.19045.4412

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --gapps-variant pico --root- sol magisk INFO: Architecture: x64 INFO: Release Type: retail INFO: Magisk Version: stable INFO: GApps Brand: MindTheGapps INFO:
GApps Variant: pico INFO: Root Solution: magisk Build: RELEASE_TYPE=Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

```
The operation completed successfully.
Installing MicrosoftCorporationII.WindowsSubsystemForAndroid version: 2311.40000.5.0
Dependency package Microsoft.UI.Xaml.2.8 x64 current version: 8.2310.30001.0. Nothing to do.
Dependency package Microsoft.VCLibs.140.00.UWPDesktop x64 current version: 14.0.33728.0. Nothing to do.
Dependency package Microsoft.VCLibs.140.00 x64 current version: 14.0.33519.0. Nothing to do.
Installing MagiskOnWSA....
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.
Windows cannot install package MicrosoftCorporationII.WindowsSubsystemForAndroid_2311.40000.5.0_x64__8wekyb3d8bbwe
because this package is not compatible with the device. The package requires OS version 10.0.22000.120 or higher on
the Windows.Desktop device family. The device is currently running OS version 10.0.19045.4412.
NOTE: For additional information, look for [ActivityId] cdeb32cd-b64a-0002-2adb-24ce4ab6da01 in the Event Log or use
the command line Get-AppPackageLog -ActivityID cdeb32cd-b64a-0002-2adb-24ce4ab6da01
At D:\DownolOAD\WSA_2311.40000.5.0_x64_Release-Nightly-with-magisk-27.0(27000)-stable-NoGApps-NoAmazon\Install.ps1:162
char:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (D:\DownolOAD\WS...ppxManifest.xml:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```
[//]: <> (Don't modify below)
</details>

**Comment by Howard20181** [comment]
Not support Windows 10
