### ISSUE TITLE
[Bug] Tool doesn't successfuly patch WSA anymore

### ISSUE THREAD

**Issue by joeyoropesa-dev** [LSPosed/MagiskOnWSALocal#813]
### Steps to reproduce/复现步骤

1. As usual I've did with older versions of WSA, cloning the repo in WSL 2 environment
2. Updating all packages 
3. Executing ./scripts/run.sh and follow instructions to build WSA

### Expected behaviour/预期行为

Successfuly builded, installed and executed

### Actual behaviour/实际行为

Build is successful (completed) but after executing run.bat and WSA Settings opens, one window loads VM for a short time and automatically crashes while WSA Settings are still open. Tried to re-run VM, but no success - it loads and closes. No error messages and MoBox reported crash in Event Logger (Applications)

When you restore initrd.img to default version (not patched by this tool), it boots successfuly (but without root and gapps installed)

### MagiskOnWSALocal commit full SHA/MagiskOnWSALocal 提交的完整哈希

599e02705417298f8f99b5d773fe92157bb7dd32/MagiskOnWSALocal

### Linux distribution info/Linux 发行版信息

PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2024.3"
VERSION="2024.3"
VERSION_CODENAME="kali-rolling"
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"

### Windows version/Windows 版本

10.0.26100.1876

### Build Parameters/构建参数

COMMAND_LINE=--arch x64 --release-type retail --root-sol magisk --magisk-ver stable --install-gapps --remove-amazon
INFO: Architecture: x64
INFO: Release Type: retail
INFO: Magisk Version: stable
INFO: Root Solution: magisk
INFO: Compress Format: none
INFO: Release Name: Retail

### Version requirement/版本要求

- [X] I am using latest commit of MagiskOnWSALocal/我正在使用最新 commit 的版本

### Logs/日志

<details>

[//]: <> (Don't modify above)

![Screenshot 2024-09-28 090118](https://github.com/user-attachments/assets/9cec2779-8996-498b-b9a5-082c03ac98a9)

```
Faulting application name: WsaClient.exe, version: 2407.40000.0.0, time stamp: 0x668f1a10
Faulting module name: WsaClient.exe, version: 2407.40000.0.0, time stamp: 0x668f1a10
Exception code: 0xc0000409
Fault offset: 0x0000000000023047
Faulting process id: 0x2730
Faulting application start time: 0x1DB1177123BD2E8
Faulting application path: D:\Others\SystemA64\WsaClient\WsaClient.exe
Faulting module path: D:\Others\SystemA64\WsaClient\WsaClient.exe
Report Id: c88b483e-88b4-4c41-8954-95b30296c51e
Faulting package full name: MicrosoftCorporationII.WindowsSubsystemForAndroid_2407.40000.0.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

Fault bucket 1628685039626230027, type 5
Event Name: MoBEX
Response: Not available
Cab Id: 0

Problem signature:
P1: MicrosoftCorporationII.WindowsSubsystemForAndroid_2407.40000.0.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 2407.40000.0.0
P4: 668f1a10
P5: WsaClient.exe
P6: 2407.40000.0.0
P7: 668f1a10
P8: 0000000000023047
P9: c0000409
P10: 0000000000000007

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.eb246ff2-90f7-4c46-9bec-da3511cdef98.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2030b70a-d72a-4360-a64c-524a578d6364.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20240808_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e86f7b9b-0e50-49bc-b9af-0ac42b995bc9.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.d56ec0c7-907a-4912-8103-c6abbc84dd4c.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6eba42fd-dfba-46ce-91f8-c266a54da8fe.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.495f482f-6fcb-4240-be41-1ffd4118c57c.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5a5ef64b-5245-433c-930b-fe6b4b930c3a.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_MicrosoftCorpora_a0b78b1a43177ce309548791101d65b9fb09d_e7463532_73a1b368-e5c6-443d-9473-ece7910c007e

Analysis symbol: 
Rechecking for solution: 0
Report Id: c88b483e-88b4-4c41-8954-95b30296c51e
Report Status: 2147487744
Hashed bucket: b90c997cc20f8f8ee69a406a15ea190b
Cab Guid: 0
```

[//]: <> (Don't modify below)
</details>

**Comment by Cr4z33** [comment]
@joeyoropesa-dev  out of curiosity are you a Windows 11 Insider?

I ask because I got the same behaviour after latest 1000.26100.28.0 update.

**Comment by Cr4z33** [comment]
I don't know why, but without doing anything (no OS updates,  no registry tweaks, nothing) WSA has started working again... 🤯

**Comment by Cr4z33** [comment]
OK I spoke too soon... today same issue again... 💀

**Comment by Spphire** [comment]
Is it possible to use low version wsa?

**Comment by joeyoropesa-dev** [comment]
> Is it possible to use low version wsa?

Older version, yes - but newer version, nope.
