### ISSUE TITLE
./build.sh: line 314: aria2c: command not found

### ISSUE THREAD

**Issue by domoaligato** [LSPosed/MagiskOnWSALocal#86]
`download link: https://downloads.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip
Download Artifacts
./build.sh: line 314: aria2c: command not found
We have encountered an error while downloading files.`

Please do a dependency test for aria2

**Comment by Howard20181** [comment]
Already added。
https://github.com/LSPosed/MagiskOnWSALocal/blob/57f242487ab9750b1c37aebae309fa35aa3db008/scripts/run.sh#L47
