### ISSUE TITLE
Script run errors

### ISSUE THREAD

**Issue by red0fireus** [LSPosed/MagiskOnWSALocal#9]
I get these errors when running the script:
run.sh: 4: function: not found
run.sh: 5: declare: not found
run.sh: 6: shift: can't shift that many

I'm running in WSL2

**Comment by Howard20181** [comment]
> I get these errors when running the script: run.sh: 4: function: not found run.sh: 5: declare: not found run.sh: 6: shift: can't shift that many
> 
> I'm running in WSL2

run `./scripts/run.sh` or `bash ./scripts/run.sh`

**Comment by red0fireus** [comment]
Got it working. 
Thank you.
