### ISSUE TITLE
构建的最后一步发生了错误，以下是日志

### ISSUE THREAD

**Issue by weitt159** [LSPosed/MagiskOnWSALocal#92]
COMMAND_LINE=--arch x64 --release-type WIF --magisk-ver stable --gapps-brand OpenGApps --gapps-variant pico --remove-amazon --root-sol none --compress
INFO: Architecture: x64
INFO: Release Type: WIF
INFO: Magisk Version: stable
INFO: GApps Brand: OpenGApps
INFO: GApps Variant: pico
INFO: Root Solution: none
build: RELEASE_TYPE=Insider Fast
[sudo] password for weitt:
Generate Download Links
Generating WSA download link: arch=x64 release_type=Insider Fast
download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/605edfa0-3ba9-423b-abb2-aa8da0b0e8f2?P1=1662715465&P2=404&P3=2&P4=e%2fng%2f%2ffFeiYpxLywZMTE%2f76tKgbjOlxKet%2b84IRwSn1qUMyuMR0wHnR7PFaCzQl4qY1RbaH%2fNKbhl60pGWmpYA%3d%3d to /mnt/d/OneDrive - bestapower/下载/MagiskOnWSALocal-main/download/xaml-x64.appx
download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/b1b323e0-7860-4609-b06b-e4667c9c8bfe?P1=1662742769&P2=404&P3=2&P4=hjrLi10VjO6Sg3Oj7ek3rCUUeFi4jG2uHq8RkYSNESq%2fGv3WQFmtvcz4bkzXvnHn3N3hZz3dS9WI5artZnuWQw%3d%3d to /mnt/d/OneDrive - bestapower/下载/MagiskOnWSALocal-main/download/wsa-x64-WIF.zip
Generating Magisk download link: release type=stable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f94e772d280>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /topjohnwu/magisk-files/raw/master/stable.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f94e772d280>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generateMagiskLink.py", line 35, in <module>
    magisk_link = json.loads(requests.get(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /topjohnwu/magisk-files/raw/master/stable.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f94e772d280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Build: an error has occurred, exit
Cleanup Download Directory

**Comment by Howard20181** [comment]
网络问题，挂代理再试
并没有到最后一步，在获取Magisk下载连接时就出错了

**Comment by weitt159** [comment]
已经挂全局代理，已将Ubuntu for windows加入UWP回环，已切换不同节点，依旧报同样错误

**Comment by Howard20181** [comment]
全局代理是什么？
Windows的代理不会生效的

**Comment by weitt159** [comment]
clash的global模式和uwp loopback

**Comment by Howard20181** [comment]
都说了不认Windows的代理
你要么开TUN模式要么在WSL里面手动设置

**Comment by weitt159** [comment]
TUN模式是打开了的。
那我一会儿用路由器代理试试。

**Comment by Howard20181** [comment]
如果想WSL使用Windows的代理要手动设置
把 https://gist.github.com/Howard20181/31e61599ecb069483448c03649810c75
引入~/.bashrc重新登录一下就行

**Comment by Howard20181** [comment]
Jsdelivr能用吗？
实在不行我换个地址

**Comment by weitt159** [comment]
稍等，刚干完饭，马上回去试试 XD

**Comment by Howard20181** [comment]
巧了，我还在干饭

**Comment by weitt159** [comment]
https://gist.github.com/Howard20181/31e61599ecb069483448c03649810c75
按照这个方法将WSL使用Windows的代理后能用了

**Comment by weitt159** [comment]
顺便问一下，怎么选择除了pico以外的opengapps版本，它没有让我选择版本就直接pico版了

**Comment by Howard20181** [comment]
OpenGApps鸽了这么久都不出支持Android 12.1的
因为其他的都bootloop所以run.sh就默认不让选了

**Comment by weitt159** [comment]
哦好的，了解了。

**Comment by Howard20181** [comment]
如果要测试的话可以把run.sh里面的DEBUG=1前面的注释去掉
或者直接用build.sh --help看看命令行怎么用

**Comment by weitt159** [comment]
执行Install.ps1，第一个部署进度条走到第三个⚪的时候就会闪退。已经确认虚拟化和hyper-v打开，且之前成功安装过MagiskOnWSA并已删除。

**Comment by Howard20181** [comment]
手动部署，看看报错是什么
`Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion -Register .\AppxManifest.xml`

**Comment by Howard20181** [comment]
试试放到路径中没有中文的文件夹
或者之前安装的位置

**Comment by weitt159** [comment]
![image](https://user-images.githubusercontent.com/104765536/189348268-63ec8550-b049-4dbe-8a5b-9f33a5019176.png)

**Comment by Howard20181** [comment]
在这个地方用脚本安装会报错吗

**Comment by weitt159** [comment]
和之前一样，直接闪退，没有报错

**Comment by Howard20181** [comment]
打开事件查看器
在左栏找到应用程序和服务日志->Microsoft -> Windows -> AppXDeployment-Server -> Microsoft-Windows-AppXDeploymentServer/Operational
找一下最新的那个错误级别的日志看看

**Comment by Howard20181** [comment]
Win+R运行`eventvwr.msc`可以快速打开事件查看器

**Comment by weitt159** [comment]
![image](https://user-images.githubusercontent.com/104765536/189350537-7e2fdf2e-2e96-47d9-8da3-0c78ed12137b.png)
程序包 MicrosoftCorporationII.WindowsSubsystemForAndroid_2207.40000.8.0_x64__8wekyb3d8bbwe 的 AppX 部署操作失败，错误为 0x80073CF9。此失败的具体错误文本是: 从  (AppxManifest.xml)  使用程序包 MicrosoftCorporationII.WindowsSubsystemForAndroid_2207.40000.8.0_x64__8wekyb3d8bbwe 中的目标卷 D: 执行的部署 Register 操作失败，错误为 0x80070003。有关诊断应用部署问题的帮助，请参阅 http://go.microsoft.com/fwlink/?LinkId=235160。

**Comment by weitt159** [comment]
![image](https://user-images.githubusercontent.com/104765536/189350989-8849e463-18b4-40ad-a675-d89a85e0f8f1.png)
这个是闪退前最后一幕

**Comment by weitt159** [comment]
在开始菜单右键卸载

**Comment by weitt159** [comment]
我刚刚发现wsa重新出现在了开始菜单，但不在最新安装的app列表里。该应用无法打开，没有大小。我在“设置”的详细信息里无法卸载，但是可以在开始菜单右键卸载。卸载后重新尝试运行脚本，情况依旧，但事件查看器报错如下
![image](https://user-images.githubusercontent.com/104765536/189352250-c7774faa-8197-4471-9ccc-f8cb19c2c54c.png)
AppxManifest.xml(205,6): 错误 0x80070002: 无法注册 MicrosoftCorporationII.WindowsSubsystemForAndroid 程序包，因为在分析 windows.firewallRules 扩展时遇到以下错误: 系统找不到指定的文件。
。请重试，如果问题仍然存在，请联系程序包发布者。

**Comment by Howard20181** [comment]
试试重新构建？

**Comment by Howard20181** [comment]
有没有试过把文件放回上一次成功安装的地方安装一次

**Comment by weitt159** [comment]
上一回成功安装已经是数月前了，不记得位置了T o T

**Comment by Howard20181** [comment]
powershell下运行
$(Get-AppxPackage -Name 'MicrosoftCorporationII.WindowsSubsystemForAndroid')
有输出吗？

**Comment by weitt159** [comment]
无输出

**Comment by weitt159** [comment]
以前MagiskOnWSA装好之后貌似Microsoft store自动更新了WSA，不知道会不会有这个因素

**Comment by Howard20181** [comment]
不会的，MagiskOnWSA的安装脚本是以开发者模式安装的
商店不会升级
微软这错误日志为什么这么不清楚，注册失败原因写得这么模糊

**Comment by weitt159** [comment]
但我卸载之前瞄了一眼Microsoft store上面写WSA最近更新时间为8/30

**Comment by weitt159** [comment]
重新构建的还是会闪退

**Comment by Howard20181** [comment]
刚刚我试了，即使不正常卸载直接删文件夹，改另一个地方直接运行脚本是可以成功安装的

**Comment by weitt159** [comment]
[events.zip](https://github.com/LSPosed/MagiskOnWSALocal/files/9535623/events.zip)
这个是运行一次脚本之后产生的所有新事件

**Comment by weitt159** [comment]
看起来可以用了，谢谢大佬🥰

**Comment by weitt159** [comment]
坏消息是Google play打开之后没法登录，可以从右上角的入口正常更新应用，但是点击登录的话应用标题会从“Google play商店”变成“Google play服务”，再变成“账号设置”，但画面不变，也没有弹出登录窗口

**Comment by Howard20181** [comment]
因为2207版本的微软搞坏了WebView导致Play服务崩溃
2206版本没有这个问题

**Comment by weitt159** [comment]
那有什么补救方法吗，卸载掉重新装回上一个版本？还是手动重装webview？

**Comment by weitt159** [comment]
但是我没装magisk，卸不了😭

**Comment by weitt159** [comment]
我还是重新构建一个带magisk的吧

**Comment by Howard20181** [comment]
不是卸载Play服务或WebView
是要降级WSA

**Comment by weitt159** [comment]
但是构建的时候默认是最新的一版，需要加什么参数吗，还是选择slow或者release的渠道（我目前是dev渠道的）

**Comment by Howard20181** [comment]
用release的

**Comment by weitt159** [comment]
我测试出来了，是手动部署
Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion -Register .\AppxManifest.xml
的时候安装成功了

**Comment by Howard20181** [comment]
脚本的失败吗？
内容应该一样的

**Comment by weitt159** [comment]
脚本的不行，进度条走不完，用管理员打开也不行。手动部署的能走完进度条

**Comment by Howard20181** [comment]
系统版本是多少？
有手动安装过新版本的Powershell吗？

**Comment by Howard20181** [comment]
说起来，没测过脚本是否在Preview版本正常工作

**Comment by weitt159** [comment]
release也是2207😭
![image](https://user-images.githubusercontent.com/104765536/189373129-95d2af86-1203-4a09-9285-9d37d9bb32af.png)

**Comment by Howard20181** [comment]
![image](https://user-images.githubusercontent.com/40033067/189373587-5e0750cc-8407-4983-ba79-11535d2d401f.png)

**Comment by Howard20181** [comment]
构建生成的文件夹名称有写版本号的，也是2207？

**Comment by weitt159** [comment]
WSA-OpenGApps-pico_2207.40000.8.0_x64_Release-Nightly

**Comment by Howard20181** [comment]
选 retail

**Comment by weitt159** [comment]
> 卸载重装上一个版本，登录后可以升级 还不知道微软是特意的还是不小心的

这个登陆后可升级，是升级WSA还是webview，升级后是不是webview依然正常

**Comment by Howard20181** [comment]
可以升级WSA
虽然WebView还是崩的
所以管理Google账户还是是崩的
但是Play商店能用

**Comment by weitt159** [comment]
😢好吧，那就先这么用着吧，就看微软什么时候修复这玩意儿了

**Comment by weitt159** [comment]
谢谢大佬🥰，今天太麻烦你了

**Comment by weitt159** [comment]
微软修复BUG日，家祭勿忘告鄙人🥲

**Comment by Howard20181** [comment]
修复了
搞半天不是微软的问题

**Comment by weitt159** [comment]
嗯？那是哪儿的问题

**Comment by weitt159** [comment]
我干完饭回去就重新构建部署试试

**Comment by Howard20181** [comment]
新版本WSA的WebView支持GPU加速
被SELinux挡了

**Comment by weitt159** [comment]
果然好用了，好耶
